### ISSUE TITLE
Send a Single Email to a Single Recipient

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-ruby#100]
Acceptance Criteria:
- A email object that represents the response body payload
- A mail object that handles sending email objects, data validation and error handling

Reference:
- https://github.com/sendgrid/sendgrid-ruby/tree/master/lib/sendgrid/helpers/mail
- https://github.com/sendgrid/sendgrid-ruby/blob/master/CONTRIBUTING.md
- https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html

**Comment by ssonal** [comment]
Hi,

I'm looking to help out, but I'm not sure what's required of this issue. From what I can tell, ruby-http-client manages the actual request, returning the status code, errors and body payload.

**Comment by thinkingserious** [comment]
Hi @ssonal,

This issue is part of a bigger project: [Mail Helper Enhancement (v3 mail/send)](https://github.com/sendgrid/sendgrid-ruby/projects).

Specifically, we want to refactor the Mail Helper so that it is much easier to use. I would start by proposing a new method signature. For example, we currently have:

```ruby
require 'sendgrid-ruby'
include SendGrid

from = Email.new(email: 'test@example.com')
subject = 'Hello World from the SendGrid Ruby Library!'
to = Email.new(email: 'test@example.com')
content = Content.new(type: 'text/plain', value: 'Hello, Email!')
mail = Mail.new(from, subject, to, content)

sg = SendGrid::API.new(api_key: ENV['SENDGRID_API_KEY'])
response = sg.client.mail._('send').post(request_body: mail.to_json)
puts response.status_code
puts response.body
puts response.headers
```

Perhaps a new version would be:

```ruby
require 'sendgrid-ruby'
include SendGrid


from = Email.new(email: 'test@example.com')
subject = 'Hello World from the SendGrid Ruby Library!'
to = Email.new(email: 'test@example.com')
content = Content.new(type: 'text/plain', value: 'Hello, Email!')
mail = Mail.new(from, subject, to, content)

sg = SendGrid::API.new(api_key: ENV['SENDGRID_API_KEY'])
response = sg.client.send(mail)
puts response.status_code
puts response.body
puts response.headers
```

**Comment by hanumakanthvvn** [comment]
@thinkingserious So in this case for new method signature, we can add new method in `lib/sendgrid/client.rb` as
``` ruby
def send(mail)
  data = mail.kind_of?(Mail) ? mail.to_json : mail
  @client.mail._("send").post(request_body: data)
end
```
And we can call it as 
```ruby
sg = SendGrid::API.new(api_key: ENV['SENDGRID_API_KEY'])
response = sg.send(mail)
```
Am i correct?

**Comment by thinkingserious** [comment]
This has been moved [here](https://github.com/sendgrid/sendgrid-ruby/issues/177).
