### ISSUE TITLE
Utilize Transactional Templates

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-ruby#103]
Acceptance Criteria:
- Demonstration of usage with all three cases: Send a Single Email to a Single Recipient, Send a Single Email to Multiple Recipients, Send Multiple Emails to Multiple Recipients and

Reference:
- https://github.com/sendgrid/sendgrid-ruby/blob/master/USE_CASES.md#transactional_templates
- https://github.com/sendgrid/sendgrid-ruby/tree/master/lib/sendgrid/helpers/mail
- https://github.com/sendgrid/sendgrid-ruby/blob/master/CONTRIBUTING.md
- https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html

**Comment by mmahalwy** [comment]
Any idea about whether you can specify a version?

**Comment by thinkingserious** [comment]
Hi @mmahalwy,

That's a great idea!

For reference: 
- https://sendgrid.com/docs/API_Reference/Web_API_v3/Transactional_Templates/versions.html
- https://github.com/sendgrid/sendgrid-ruby/blob/master/examples/templates/templates.rb#L79

**Comment by mmahalwy** [comment]
Speaking of which, maybe I missed it, but is there currently a way to do so?

**Comment by thinkingserious** [comment]
@mmahalwy,

Yes, the code linked above can set the version and the documentation link explains how that works.

**Comment by neyp** [comment]
Is there an example demonstrating how to specify a template for sending an email using this gem? It would be great when implementing template redesigns.

**Comment by SendGridDX** [comment]
Hi @neyp,

I believe you would just need to activate the version you require, like so: https://github.com/sendgrid/sendgrid-ruby/blob/master/examples/templates/templates.rb#L119

With Best Regards,

Elmer

**Comment by neyp** [comment]
Hi @SendGridDX,
What about testing a non-finished template redesign? If I activate it, it would be immediately used in production.

**Comment by audreythomas** [comment]
Hi @neyp,

In that case I would create a separate template first, do your testing, then add it to your original template as a version.

**Comment by thinkingserious** [comment]
This has been moved [here](https://github.com/sendgrid/sendgrid-ruby/issues/177).
