### ISSUE TITLE
NoMethodError undefined method `personalizations='

### ISSUE THREAD

**Issue by treycaliva** [sendgrid/sendgrid-ruby#104]
#### Issue Summary

Issues with personalizations and transactional templates
#### Steps to Reproduce

When using transactional template example I am receiving the following error message
`NoMethodError: undefined method`personalizations=' for #Mail::Message:0x007fa0e2bef750`
#### Technical details:
- sendgrid-ruby Version: master
- Ruby Version: 2.3.1

**Comment by thinkingserious** [comment]
Hi @treycaliva,

Please take a look at these examples: https://github.com/sendgrid/sendgrid-ruby/blob/master/USE_CASES.md#transactional_templates

If you are still having issues, please shoot over your source code so I can try to reproduce. Thanks!

**Comment by pwgustafson** [comment]
Hello, I am also having this same issue.  I have written a small ruby class to help me with building the sendgrid mail objects: 

```
require 'sendgrid-ruby'
include SendGrid

class MySendgridMailer::Base
  attr_accessor :mail

  def initialize
    @mail = Mail.new
  end

  def deliver!
    mail.from = Email.new(email: 'support@cloudagentleads.com')
    mail.subject = 'I\'m replacing the subject tag'
    personalization = Personalization.new
    personalization.to = Email.new(email: 'pwgustasfon@gmail.com')
    mail.personalizations = personalization
    mail.contents = Content.new(type: 'text/html', value: 'I\'m replacing the <strong>body tag</strong>')
    mail.template_id = 'TEMPLATE_ID'

    sg = SendGrid::API.new(api_key: 'API_KEY')
    begin
        response = sg.client.mail._("send").post(request_body: mail.to_json)
    rescue Exception => e
        puts e.message
    end
    puts response.status_code
    puts response.body
    puts response.headers
    
  end

end

```

I get undefined method errors for `mail.personalizations` along with `mail.template_id`

sendgrid-ruby (4.0.6)
ruby 2.3.1

I have followed this example: https://github.com/sendgrid/sendgrid-ruby/blob/master/USE_CASES.md#transactional_templates

but still am getting the same issues.   Am i doing something wrong creating the `Mail` object? is it possibly not what the sendgrid-ruby gem provides?

Thanks!

**Comment by thinkingserious** [comment]
Hello @pwgustafson,

I tried to reproduce your error with the following code:

```ruby
require 'sendgrid-ruby'
include SendGrid

class MySendgridMailer
  attr_accessor :mail

  def initialize
    @mail = Mail.new
  end

  def deliver!
      mail.from = Email.new(email: 'test@example.com')
      mail.subject = 'I\'m replacing the subject tag'
      personalization = Personalization.new
      personalization.to = Email.new(email: 'test@example.com')
      mail.personalizations = personalization
      mail.contents = Content.new(type: 'text/html', value: 'I\'m replacing the <strong>body tag</strong>')
      mail.template_id = 'TEMPLATE_ID'

      sg = SendGrid::API.new(api_key: ENV['SENDGRID_API_KEY'])
      begin
          response = sg.client.mail._("send").post(request_body: mail.to_json)
      rescue Exception => e
          puts e.message
      end
      puts response.status_code
      puts response.body
      puts response.headers
  end

end

sg = MySendgridMailer.new
sg.deliver!
```

and the email sent without error.

My ruby version is ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin15]
sendgrid-ruby 4.0.6

Do you have any suggestions on how I can try to verify your issue?

**Comment by pwgustafson** [comment]
Hi @thinkingserious,

I actually figured out what was going on, and I forgot to update this ticket.  It was actually because the `@mail = Mail.new` was not a sendgrid mail object, probably an ActionMailer object.

Thanks for getting back to me.

**Comment by thinkingserious** [comment]
Thanks for the follow up!
