### ISSUE TITLE
Version Missmatch

### ISSUE THREAD

**Issue by perobertson** [sendgrid/sendgrid-ruby#117]
#### Issue Summary

Version 4.0.6 is deployed to rubygems https://rubygems.org/gems/sendgrid-ruby but it appears that whatever was deployed there was not checked into the code base https://github.com/sendgrid/sendgrid-ruby/blob/d2d42c140ee78bd78f400724e7c78670fd15d94e/lib/sendgrid/version.rb#L2

Currently 4.0.5 is checked into the codebase.

#### Technical details:

* sendgrid-ruby Version: master (latest commit: d2d42c140ee78bd78f400724e7c78670fd15d94e)

**Comment by thinkingserious** [comment]
Apologies @perobertson!

I've just pushed it: https://github.com/sendgrid/sendgrid-ruby/commits/master

**Comment by perobertson** [comment]
excellent, thanks!
