### ISSUE TITLE
embed erb.html file to SendGrid template

### ISSUE THREAD

**Issue by trieulh-ict** [sendgrid/sendgrid-ruby#118]
#### Issue Summary

As the title, is there any way to embed my local erb.html file in my project to SendGrid template?
Thank in advance.

#### Technical details:

* sendgrid-ruby Version: master 
* Ruby Version: 2.3.1
* Rails Version: 5.0.0

**Comment by thinkingserious** [comment]
Hello @trieulh-ict,

I'm thinking you are asking how to use your erb.html as the template when you send an email. If so, you can pass the contents of the erb.html file into the Content object of type 'text/html', like so: https://github.com/sendgrid/sendgrid-ruby/blob/master/examples/helpers/mail/example.rb#L9

If not, please elaborate. Thanks!

**Comment by trieulh-ict** [comment]
Oh yes, That's what I mean, sorry for bad english.
But I tried this:

`mail = SendGrid::Mail.new`
...
`mail.contents = SendGrid::Content.new(type: 'text/plain', value: 'Thank you for sign up')`
`mail.contents = SendGrid::Content.new(type: 'text/html', value: '<html><body>Thank you for sign up</body></html>')`

My Sidekiq notified that ActionMailer delivered but I got no mail. It just works after I add template by this line:

`mail.template_id = get_template(temp_id)`

And this is my post request:

`sg = SendGrid::API.new(api_key: ENV['SENDGRID_API_KEY'], host: 'https://api.sendgrid.com')`
`response = sg.client.mail._('send').post(request_body: mail.to_json)`

**Comment by thinkingserious** [comment]
Can you please provide the full code? If you are not comfortable doing so in public, please send to dx@sendgrid.com. Thanks!

**Comment by trieulh-ict** [comment]
Sorry for "super-slow" reply. 
I've already resolved my issue by using multi templates. I think It's better, isn't it? Thank you in advance.
