### ISSUE TITLE
Error on README 

### ISSUE THREAD

**Issue by KleverMarketing** [sendgrid/sendgrid-ruby#12]
Thank you for the nice Gem. 
The example in X-SMTPAPI Header section doesn't work. The added filter should be "templates" instead of "template" 

`header.add_filter('templates', 'enable', 1) `
`header.add_filter('templates', 'template_id', '1234-5678-9100-abcd')`

**Comment by bfischer1121** [comment]
+1

Ran into this as well. It will send a blank email without any error. Maybe note that "template" is for legacy templates and "templates" is for new templates. Throwing an error at the SendGrid level would be even better.

**Comment by eddiezane** [comment]
Thanks so much for reporting this and sorry for the delay!
