### ISSUE TITLE
Incorrect handling of recipient names with special characters

### ISSUE THREAD

**Issue by maxpark-jd** [sendgrid/sendgrid-ruby#120]
#### Issue Summary

Either sendgrid-ruby or Sendgrid is incorrectly handling recipient names with special characters

#### Steps to Reproduce

1. Use a name with special characters in personalization.to code. For example:
personalization.to = SendGrid::Email.new(email: "test@example.com", name: "Attn: Accounts Payable, Corp,")
2. Sendgrid drops the email because it receives a request with email address as "attn:accounts" (refer to attached screenshot.)
![screen shot 2016-11-11 at 4 20 50 pm](https://cloud.githubusercontent.com/assets/14076524/20230684/2d62a000-a82b-11e6-8ad6-076e3e3a8039.png)

#### Technical details:

* sendgrid-ruby Version: 4.0.2
* Ruby Version: 2.2.3p173

**Comment by thinkingserious** [comment]
Hello @maxpark-jd,

This is a limitation of the SendGrid API. Currently, we do not support commas in the from name.

**Comment by maxpark-jd** [comment]
Thank you for this information @thinkingserious ! So it is only the comma in the from name. It will be helpful if it is in the [document](https://github.com/sendgrid/sendgrid-ruby#quick-start) as it can be tricky to figure out when that happens in a client's production server.

**Comment by thinkingserious** [comment]
Thanks for the follow up, I'm going to verify and check back in with you.

**Comment by thinkingserious** [comment]
Hello @maxpark-jd,

You can view the full list of limitations here: https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html#-Limitations

Thanks!
