### ISSUE TITLE
Sending to multiple emails with personalized substitutions

### ISSUE THREAD

**Issue by trieulh-ict** [sendgrid/sendgrid-ruby#125]
#### Issue Summary

As the topic, is there any **best performance** way to send a personalized content to multiple emails (around thousands of emails) in one call?

Currently I create one personalization for each recipient and add it to mail.personalizations.

My code:

`mail = SendGrid::Mail.new`
`mail.from = SendGrid::Email.new(email: @admin_mail)`

...
`personalization = Personalization.new`
`personalization.to = Email.new(email: subscriber.email)`
`personalization.substitutions = Substitution.new(key: '%mail%', value: subscriber.email)`
`mail.personalizations = personalization`
`mail.template_id = get_template(subscriber.language)`
...          
`sg.client.mail._('send').post(request_body: mail.to_json)`

* sendgrid-ruby Version: master
* Ruby Version: 2.3.1

**Comment by trieulh-ict** [comment]
My solution is to create

**Comment by jrectenwald** [comment]
I think the best way to avoid creating individual personalizations for each recipient is to add an X-SMTPAPI header to the message. You can pass in a list of email recipients and a hash of substitutions that you want to make.

https://sendgrid.com/docs/API_Reference/SMTP_API/index.html
https://sendgrid.com/docs/Integrate/Code_Examples/SMTP_API_Header_Examples/ruby.html

This example is from 2009 though, so I'm not sure if there is a better way to do it within this gem.

**Comment by thinkingserious** [comment]
@trieulh-ict,

Thank you for reaching out to us!

I suggest you reach out to our [support team](https://support.sendgrid.com) on this one. 

With Best Regards,

Elmer
