### ISSUE TITLE
Does "X-SMTPAPI" header with "to" option work?

### ISSUE THREAD

**Issue by xxswingxx** [sendgrid/sendgrid-ruby#126]
I'm trying to send an email to multiple recipients but hiding the email addresses from each other on a development environment. It seems the docs are telling that it should be possible with something like this:

```ruby
headers['X-SMTPAPI'] = { to: [email_address1, email_address2] }
```
I thought it would work with this code, but only email1@test.com receives the email

```ruby
  mail = SendGrid::Mail.new
  mail.from = SendGrid::Email.new(email: 'notifications@myapp.com')
  mail.reply_to = SendGrid::Email.new(email: 'john@doe.com')
  mail.subject = 'A test email'
  mail.contents = SendGrid::Content.new(type: 'text/html', value: '<html><body>Some text here</body></html>')

  to = { to: ['email1@test.com', 'email2@test.com'] }
  mail.headers = SendGrid::Header.new(key: 'X-SMTPAPI', value: to.to_json)

  personalization = SendGrid::Personalization.new
  personalization.custom_args = SendGrid::CustomArg.new(key: 'document_id', value: model.id.to_s)
  personalization.to = SendGrid::Email.new(email: 'email1@test.com')

  mail.personalizations = personalization

  sg = SendGrid::API.new(api_key: 'SG.api_key')
  response = sg.client.mail._('send').post(request_body: mail.to_json)

```
I'm currently using Rails 4.1 and   sendgrid-ruby 4.0.6

**Comment by trieulh-ict** [comment]
It seems because of this line 

`personalization.to = SendGrid::Email.new(email: 'email1@test.com')`

You only add `email1@test.com` to the personalization. 
Though I dont understand clearly the difference between `to` in header and in personalization.

**Comment by xxswingxx** [comment]
@trieulh-ict , the idea is to send multiple emails in a single request while hidding the email addresses to the rest of the recipients so each recipient would receive an email with a single address in the "to". According to the docs this should be possible with the X-SMTPAPI header. For the previous gem version it looked like the other "to" (`personalization.to ` in my case) was ignored, not in this case tho. I also have a validation error if I try to send the mail without setting `personalization.to` , so I'm a bit lost now on how to do this with this version of the gem

**Comment by trieulh-ict** [comment]
To hide the addresses, I'm considering about using header or bcc. 
But does any solutions work well?
I'm also dealing with huge list of recipients (abt 10k) and none of them works in my case.

Waiting for response from dev team.

**Comment by thinkingserious** [comment]
@trieulh-ict ,

You do not need the X-SMTPAPI header, as it's now included within the new v3 API. To achieve the result of having multiple emails in the single request while hiding the emails you need multiple personalization objects.

Here is a working example:

```ruby
require 'sendgrid-ruby'
include SendGrid

mail = Mail.new
mail.from = Email.new(email: 'test1@example.com')
mail.subject = 'Hello World from the SendGrid Ruby Library'

personalization = Personalization.new
personalization.to = Email.new(email: 'test2@example.com', name: 'Example User 2')
mail.personalizations = personalization

personalization2 = Personalization.new
personalization2.to = Email.new(email: 'test3@example.com', name: 'Example User 3')
mail.personalizations = personalization2

puts JSON.pretty_generate(mail.to_json)

mail.contents = Content.new(type: 'text/html', value: '<html><body>Testing from Ruby</body></html>')
sg = SendGrid::API.new(api_key: ENV['SENDGRID_API_KEY'], host: 'https://api.sendgrid.com')
response = sg.client.mail._('send').post(request_body: mail.to_json)
puts response.status_code
puts response.body
puts response.headers
```

With Best Regards,

Elmer

**Comment by xxswingxx** [comment]
I think I've got it. I've ended up creating a `personalization` per recipient:
 
```ruby
['email1@test.com', 'email2@test.com'].each do |email|
   personalization = SendGrid::Personalization.new
   personalization.custom_args = SendGrid::CustomArg.new(key: 'document_id', value: model.id.to_s)
   personalization.to = SendGrid::Email.new(email: email)
   mail.personalization = personalization
end
```
Is this the correct way?
