### ISSUE TITLE
The results of some methods seem not to be equal to Sendgrid db.

### ISSUE THREAD

**Issue by trieulh-ict** [sendgrid/sendgrid-ruby#127]
#### Issue Summary

I used 2 method to retrieve info of all contacts and bounce mails, but The result is not enough.

`sg.client.contactdb.recipients.get()`
`sg.client.suppression.bounces.get()`

Currently on my dashboard, I reached the limit of 2000 contacts, but the result of query only gives me 978 contacts (I parsed from response)
Same with bounce mails, 12 bounce pages but only receive 500 bounce mails.

Is there any ideas?
Thank in advance.
* sendgrid-ruby Version: master (latest commit: [commit number])
* Ruby Version: 2.3.1

**Comment by thinkingserious** [comment]
Hello @trieulh-ict,

Thank you for reaching out us!

To best help you on this issue, please <a href="mailto:support@sendgrid.com?subject=%5BDX%20Support%20Request%5D%20-%20The%20results%20of%20some%20methods%20seem%20not%20to%20be%20equal%20to%20Sendgrid%20db.&body=Please%20see%20this%20GitHub%20Issue%20for%20reference%3A%20https%3A//github.com/sendgrid/sendgrid-ruby/issues/127%0A%0AIssue%20Summary%0AI%20used%202%20method%20to%20retrieve%20info%20of%20all%20contacts%20and%20bounce%20mails%2C%20but%20The%20result%20is%20not%20enough.%0Asg.client.contactdb.recipients.get%28%29%0Asg.client.suppression.bounces.get%28%29%0ACurrently%20on%20my%20dashboard%2C%20I%20reached%20the%20limit%20of%202000%20contacts%2C%20but%20the%20result%20of%20query%20only%20gives%20me%20978%20contacts%20%28I%20parsed%20from%20response%29%0ASame%20with%20bounce%20mails%2C%2012%20bounce%20pages%20but%20only%20receive%20500%20bounce%20mails.%0AIs%20there%20any%20ideas%3F%0AThank%20in%20advance.%0A%0Asendgrid-ruby%20Version%3A%20master%20%28latest%20commit%3A%20%5Bcommit%20number%5D%29%0ARuby%20Version%3A%202.3.1">email our support team</a> or open a ticket at our <a href="https://support.sendgrid.com">support website</a>.

Thank you!

Elmer
