### ISSUE TITLE
Delete all contacts having mails in bounces

### ISSUE THREAD

**Issue by trieulh-ict** [sendgrid/sendgrid-ruby#128]
#### Issue Summary

I want to delete all emails which is in bounce. But when I retrieve list in bounce, each item only contains email, not recipient_id. And I see no API to delete contact by email, only by recipient_id.

Any ideas to delete thousand of contacts which are in bounce in 1 API call, or I have to retrieve recipient_id one by one? The second solution need to call API thousand times, not best in performance.

Thank in advance.

#### Technical details:

* sendgrid-ruby Version: 4.0.6
* Ruby Version: 2.3.1

**Comment by thinkingserious** [comment]
Hello @trieulh-ict,

Thank you for reaching out us!

To best help you on this issue, please <a href="mailto:support@sendgrid.com?subject=%5BDX%20Support%20Request%5D%20-%20Delete%20all%20contacts%20having%20mails%20in%20bounces&body=Please%20see%20this%20GitHub%20Issue%20for%20reference%3A%20https%3A//github.com/sendgrid/sendgrid-ruby/issues/128%0A%0AIssue%20Summary%0AI%20want%20to%20delete%20all%20emails%20which%20is%20in%20bounce.%20But%20when%20I%20retrieve%20list%20in%20bounce%2C%20each%20item%20only%20contains%20email%2C%20not%20recipient_id.%20And%20I%20see%20no%20API%20to%20delete%20contact%20by%20email%2C%20only%20by%20recipient_id.%0AAny%20ideas%20to%20delete%20thousand%20of%20contacts%20which%20are%20in%20bounce%20in%201%20API%20call%2C%20or%20I%20have%20to%20retrieve%20recipient_id%20one%20by%20one%3F%20The%20second%20solution%20need%20to%20call%20API%20thousand%20times%2C%20not%20best%20in%20performance.%0AThank%20in%20advance.%0ATechnical%20details%3A%0A%0Asendgrid-ruby%20Version%3A%204.0.6%0ARuby%20Version%3A%202.3.1">email our support team</a> or open a ticket at our <a href="https://support.sendgrid.com">support website</a>.

Thank you!

Elmer

**Comment by thinkingserious** [comment]
Hello @trieulh-ict,

Thank you for reaching out us!

To best help you on this issue, please <a href="mailto:support@sendgrid.com?subject=%5BDX%20Support%20Request%5D%20-%20Delete%20all%20contacts%20having%20mails%20in%20bounces&body=Please%20see%20this%20GitHub%20Issue%20for%20reference%3A%20https%3A//github.com/sendgrid/sendgrid-ruby/issues/128%0A%0AIssue%20Summary%0AI%20want%20to%20delete%20all%20emails%20which%20is%20in%20bounce.%20But%20when%20I%20retrieve%20list%20in%20bounce%2C%20each%20item%20only%20contains%20email%2C%20not%20recipient_id.%20And%20I%20see%20no%20API%20to%20delete%20contact%20by%20email%2C%20only%20by%20recipient_id.%0AAny%20ideas%20to%20delete%20thousand%20of%20contacts%20which%20are%20in%20bounce%20in%201%20API%20call%2C%20or%20I%20have%20to%20retrieve%20recipient_id%20one%20by%20one%3F%20The%20second%20solution%20need%20to%20call%20API%20thousand%20times%2C%20not%20best%20in%20performance.%0AThank%20in%20advance.%0ATechnical%20details%3A%0A%0Asendgrid-ruby%20Version%3A%204.0.6%0ARuby%20Version%3A%202.3.1">email our support team</a> or open a ticket at our <a href="https://support.sendgrid.com">support website</a>.

Thank you!

Elmer
