### ISSUE TITLE
Subject encoding in email is different when sending from preview vs sending by V3 api

### ISSUE THREAD

**Issue by milep** [sendgrid/sendgrid-ruby#135]
#### Issue Summary

When sending transactional template from api, subject is not encoded.

#### Steps to Reproduce

1. Create template with a subject: `Terveisiä rannalta`
2. Send preview
Subject in the received email: `Subject: =?UTF-8?Q?Test_-_Terveisi=C3=A4_rannalta?=`
3. Send the same template through V3 api
Subject in the received email: `Subject: Terveisiä rannalta`

As a workaround, if you add substitution to the subject, then it becomes Base64 encoded. 
I think it should probably encode the subject with UTF-8 quoted-printable as a default.

#### Technical details:

* sendgrid-ruby Version: 4.0.6
* Ruby Version: 2.3.1

**Comment by thinkingserious** [comment]
Thanks for submitting this issue @milep, we have added it to our backlog for review.

**Comment by quantson** [comment]
Thanks for the workaround @milep, was really helpful. I've also noticed that removing all personalizations did the trick, might be correlated.

**Comment by thinkingserious** [comment]
@milep, @quantson,

We have discovered that this is an API level problem and our engineering team is working on a fix now. 

Thanks for your patience and I'll update this thread when the fix is live.

**Comment by thinkingserious** [comment]
@milep, @quantson,

Apologies for my delayed update.

This issue has been resolved at the API level as of 12/14/16.

Thanks!
