### ISSUE TITLE
Sending mail with subuser account

### ISSUE THREAD

**Issue by mepiphany** [sendgrid/sendgrid-ruby#136]
#### Issue Summary

Sending an email with the subuser's account works, however, when I go into subuser management section inside the dash board all my requests are displayed 0. If I visit activity panel on the dash board it shows all the emails sent. I have no idea why I can't get any statistics on my subusers?
please help

**Comment by thinkingserious** [comment]
Hello @mepiphany,

Thank you for reaching out us!

To best help you on this issue, please <a href="mailto:support@sendgrid.com?subject=%5BDX%20Support%20Request%5D%20-%20Sending%20mail%20with%20subuser%20account&body=Please%20see%20this%20GitHub%20Issue%20for%20reference%3A%20https%3A//github.com/sendgrid/sendgrid-ruby/issues/136%0A%0AIssue%20Summary%0ASending%20an%20email%20with%20the%20subuser%27s%20account%20works%2C%20however%2C%20when%20I%20go%20into%20subuser%20management%20section%20inside%20the%20dash%20board%20all%20my%20requests%20are%20displayed%200.%20If%20I%20visit%20activity%20panel%20on%20the%20dash%20board%20it%20shows%20all%20the%20emails%20sent.%20I%20have%20no%20idea%20why%20I%20can%27t%20get%20any%20statistics%20on%20my%20subusers%3F%0Aplease%20help">email our support team</a> or open a ticket at our <a href="https://support.sendgrid.com">support website</a>.

Thank you!

Elmer
