### ISSUE TITLE
MailHelper returning InvalidType error message from server for from and to fields.

### ISSUE THREAD

**Issue by alikhan-io** [sendgrid/sendgrid-ruby#138]
#### Issue Summary

When using the mail helper only we are getting an error on from and to emails.

{"errors":[{"message":"Invalid type. Expected: object, given: string.","field":"from","help":"http://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/errors.html#message.from"},{"message":"Invalid type. Expected: object, given: string.","field":"personalizations.0.to.0","help":"http://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/errors.html#message.personalizations.to"}]}

This seems quite surprising as we are following the standard practices outlined in the gem.
```

    mail = Mail.new
    mail.from = Email.new(email: "akhan@example.com")
    mail.subject = 'Welcome'
    personalization = Personalization.new
    #Below should be changed
    personalization.to = Email.new(email: "akhan@example.com")
    mail.contents = Content.new(type: 'text/html', value: '')
    mail.template_id = 'XXXX'

    sg = SendGrid::API.new(api_key: 'XXXXXX')
    begin
response = sg.client.mail._("send").post(request_body: mail.to_json)
    rescue Exception => e
      puts e.message
    end
    puts response.status_code
    puts response.body
    puts response.headers

```

* sendgrid-ruby Version: master (latest commit)
* Ruby Version: 2.3.1
* Rails Version: 5.0.0.1

**Comment by akki209** [comment]
Hi @alikhan-io are you sure you have the right code pasted above?
I tried with that and it gave me two errors.

`{
    "errors": [
        {
            "message": "The personalizations field is required and must have at least one personalization.",
            "field": "personalizations",
            "help": "http://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/errors.html#-Personalizations-Errors"
        },
        {
            "message": "The content value must be a string at least one character in length.",
            "field": "content.0.value",
            "help": "http://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/errors.html#message.content.value"
        }
    ]
}`



to Solve first add  personalizations values to mail object
`mail.personalizations = personalization` 
before calling `sg = SendGrid::API.new(api_key: 'XXXXXX')`
And for the second error
replace `mail.contents = Content.new(type: 'text/html', value: '')`
with `mail.contents = Content.new(type: 'text/html', value: 'test')`
As it states in error that  

> The content value must be a string at least one character in length


This should work. Here is working example.

```
mail = Mail.new
mail.from = Email.new(email: "test@example.com")
mail.subject = 'Welcome'
personalization = Personalization.new
personalization.to = Email.new(email: "myemail@mail.com")
mail.contents = Content.new(type: 'text/html', value: 'test')
mail.template_id = 'XXX'

mail.personalizations = personalization
sg = SendGrid::API.new(api_key: 'XXX')
begin
response = sg.client.mail._("send").post(request_body: mail.to_json)
rescue Exception => e
  puts e.message
end
puts response.status_code 
```

**Comment by alikhan-io** [comment]
I will attempt this fix tomorrow - thanks!

**Comment by thinkingserious** [comment]
Thanks for taking the time to help out @alikhan-io!

Please fill out this [form](https://docs.google.com/forms/d/e/1FAIpQLSelP4uF-wGJebxVYq1DYw5WzHomEUauab3YiqrshyCkRs0fqw/viewform#start=invite) and we will send you some swag :)
