### ISSUE TITLE
Namespace conflict with Email model

### ISSUE THREAD

**Issue by alikhan-io** [sendgrid/sendgrid-ruby#139]
#### Issue Summary

We have am model named Email in our application. When including SendGrid, our application errors as it believes us to be referencing SendGrid::Email rather than our own.
```

require 'sendgrid-ruby'
include SendGrid

class Notifications::WelcomeWorker
  include Sidekiq::Worker

  def perform(email_id)

    emailAddr = Email.find(email_id)
    ...
  end
end
```

We get

```undefined method `find' for SendGrid::Email:Class```

Refer to http://stackoverflow.com/questions/41508464/rails-model-name-conflict-with-included-gem?noredirect=1#comment70223099_41508464 for more details

Note we attempetd using the :: prepender to break out of this but that too failed with the same error.

``` emailAddr = ::Email.find(email_id)```

#### Technical details:

Latest SendGrid Gem Version
* Ruby Version: 2.3.1
* Rails 5.0.0.1

**Comment by alikhan-io** [comment]
To note - with the help of SO I was able to resolve this by removing the "include SendGrid" line. Apparently with Rails this is not needed. I'm keeping this issue here though for now as it may be worth exploring modifying the instructions to clarify the include portion in the README's first two examples.

**Comment by thinkingserious** [comment]
Thank you @alikhan-io,

We will add this use case to our TROUBLESHOOTING.md section.

**Comment by OrthoDex** [comment]
Hey @thinkingserious , I happened to run into the same issue a while ago. Do you mind if I update the Troubleshooting section and submit a PR?

**Comment by thinkingserious** [comment]
That would be great @OrthoDex, thanks!

**Comment by OrthoDex** [comment]
Hey @thinkingserious I opened a PR at #221 🙂
