### ISSUE TITLE
No test

### ISSUE THREAD

**Issue by JoshMcKin** [sendgrid/sendgrid-ruby#14]
Restclient is slow, so I'd like to create a pull request to use https://github.com/nahi/httpclient instead, but there are no tests to verify functionality. Are there tests that can be checked into the repo to aid in opensource development?

Thanks,
Josh

**Comment by eddiezane** [comment]
I actually have some changes that include tests that I need to push up. Thanks for the reminder!

I am definitely not opposed to the idea of swapping restclient for httpclient. Is there data on the speed comparison? It looks like the included benchmarks don't include it. Though it is simply based off net/http and that's there.

**Comment by JoshMcKin** [comment]
http://stackoverflow.com/questions/17619028/ruby-rails-performance-openuri-vs-nethttp-vs-curb-vs-rest-client
https://bibwild.wordpress.com/2012/04/30/ruby-http-performance-shootout-redux/
http://www.slideshare.net/HiroshiNakamura/rubyhttp-clients-comparison

The last 2 are a bit old but I've heard Net::Http has not changed enough to make a big difference in performance.

There are faster clients that HTTPClient, like curb but libraries that use curl can be difficult to install and with an API gem like yours you probably want cross platform compatibility. In a perfect world I'd use Excon but it lacks multi-part posts.  

The link example above by Hiroshi Nakamura describes all the benefits of HTTPClient far better than I can.

**Comment by thinkingserious** [comment]
We are now using faraday.
