### ISSUE TITLE
Message won't send when attachment is present

### ISSUE THREAD

**Issue by tommybstitch** [sendgrid/sendgrid-ruby#140]
#### Issue Summary

When I try to attach a PDF file to the message being sent, I don't get any errors or warnings but the message I am attempting to send never gets sent. When I comment out the attachment code, the message sends just fine. 

#### Steps to Reproduce

1. Create a mail object in Ruby to be sent using the Sendgrid SDK
2. Attach a PDF file to the message
3. Attempt to send the message

```
response = Curl.get(@params[:pdf_url])
attachment = SendGrid::Attachment.new
attachment.type = 'application/pdf'
attachment.content = Base64.strict_encode64(response.body)
filename = "foo_bar"
attachment.filename = "#{filename}.pdf"
attachment.disposition = 'attachment'
attachment.content_id = @params[:subject]
mail.attachments = attachment
```

#### Technical details:

* sendgrid-ruby Version: 3.0.3 
* Ruby Version: 2.0

**Comment by thinkingserious** [comment]
Hello @tommybstitch, 

Would you mind providing the rest of the code so that I may try to reproduce the error. Also, could you send us the pdf to dx@sendgrid.com?

Thanks!

**Comment by thinkingserious** [comment]
Hello @tommybstitch,

Are you still having trouble? Please let us know. Thanks!

**Comment by thinkingserious** [comment]
@tommybstitch,

Here is a [full attachment example](https://github.com/sendgrid/sendgrid-ruby/blob/master/USE_CASES.md#transactional_templates).
