### ISSUE TITLE
Numeric values cause 400 Bad Request with no explanation

### ISSUE THREAD

**Issue by brian4d** [sendgrid/sendgrid-ruby#142]
#### Issue Summary

Was stumped briefly while upgrading to Ver 3 of the API. I had followed the example code but was getting "400 Bad Request" without any other explanation. 

`mail.custom_args = CustomArg.new(:key => 'list_id', :value => self.list_id)`
`mail.custom_args = CustomArg.new(:key => 'message_id', :value => self.id)`
`personalization.substitutions = Substitution.new(:key => '-person_id-', :value => subscriber.id)
`

Finally figured it might be caused by a few numeric values in the CustomArgs and Substitutions. Voila!

`mail.custom_args = CustomArg.new(:key => 'list_id', :value => self.list_id.to_s)`
`mail.custom_args = CustomArg.new(:key => 'message_id', :value => self.id.to_s)`
`personalization.substitutions = Substitution.new(:key => '-person_id-', :value => subscriber.id.to_s)`

It would be great if the gem automatically converted these values to strings -- particularly since the error message is so generic. Thanks.

#### Technical details:

* sendgrid-ruby Version: master (latest commit: 4.0.6)
* Ruby Version: 2.2

**Comment by thinkingserious** [comment]
Hi @brian4d,

Agreed and thanks for taking the time to spell out the issue in detail!

I have added this to our backlog for implementation.

With Best Regards,

Elmer

**Comment by percyhanna** [comment]
Any word on fixing this? Ideally the API would just return a better error message, and/or accept any valid JSON in `custom_args` (or at least any scalar values).

**Comment by thinkingserious** [comment]
Hi @percyhanna,

I've added your vote to this issue to help it rise in our backlog. It can continue to rise with additional +1s, comments or a PR. A PR would cause the greatest impact.

Thanks!

Elmer

**Comment by sitaramshelke** [comment]
Hey @thinkingserious can I help with this?
It looks like a simple fix in `initialize` in `custom_arg.rb` 
I guess sometimes `id` fields are ruby objects and not string which caused the issue.

**Comment by thinkingserious** [comment]
Thanks @sitaramshelke! It's all yours :)

**Comment by percyhanna** [comment]
Thanks @sitaramshelke !
