### ISSUE TITLE
Multiple categories in categories stats request

### ISSUE THREAD

**Issue by jeyboy** [sendgrid/sendgrid-ruby#145]
Hi!

I'm trying to send a request 'categories.stats.get' with several categories in the form ['cat1', 'cat2'], but this leads to the error: '{"errors":[{"message":"category does not exist","field":"categories"}]}'. The examples in gem don't contain the answer. On sending one category everything work ok.

Will be grateful for your help

**Comment by thinkingserious** [comment]
Hello @jeyboy,

Do you mind posting the request body so I can attempt to reproduce? Thanks!

**Comment by jeyboy** [comment]
Hi. 

Please check next request:
client= SendGrid::API.new(api_key: 'api key')).client
client.categories.stats.get(start_date: '2016-12-31', categories: ['cat1', 'cat2'])

Thanks.

**Comment by thinkingserious** [comment]
Hello @jeyboy,

Here is how you make that call for 1 category:

```ruby
sg = SendGrid::API.new(api_key: ENV['SENDGRID_API_KEY'])
params = JSON.parse('{"start_date": "2016-12-31", "categories": "category1"}')
response = sg.client.categories.stats.get(query_params: params)
puts response.status_code
puts response.body
puts response.headers
```

According to the docs, we can have up to 10 categories in the `categories` field as a string, but I'm not sure what the format should be. Once I find an answer, I will post here.

Thanks!

With Best Regards,

Elmer

**Comment by thinkingserious** [comment]
And for multiple categories:

```ruby
sg = SendGrid::API.new(api_key: ENV['SENDGRID_API_KEY'])
params = JSON.parse('{"start_date": "2016-12-31", "categories": "category1&category2&category3"}')
response = sg.client.categories.stats.get(query_params: params)
puts response.status_code
puts response.body
puts response.headers
```

**Comment by jeyboy** [comment]
Hello @thinkingserious

Thank you very much for your help!!!!!.

**Comment by xiaoboa** [comment]
@thinkingserious the multiple categories way you provided doesn't seems working, the generated query params is `start_date=2016-12-31&categories=category1&category2&category3` and this only returns the first category stats.

But instead, `start_date=2016-12-31&categories=category1&categories=category2&categories=category3` returns all categories stats, and is working as expected.

The gem version I'm using is `5.0.0`
