### ISSUE TITLE
Setup Env Variables

### ISSUE THREAD

**Issue by laynetrain** [sendgrid/sendgrid-ruby#149]
Shouldn't the key go in a `/config/secrets.yml` file?   
```
common: &common
  sendgrid:
      api_key: YOUR_API_KEY
```
And then get initialized in `/config/initializers/sendgrid.rb`?
```
SendGrid.configure do |config|
  config.log_level = :debug
  config.api_key = Rails.application.secrets.sendgrid['api_key']
end
```
My worry is that I would have to do this every time I switched to my sendgrid branch and that this setup wouldn't work on staging/ production.
```
Update the development environment with your SENDGRID_API_KEY, for example:

echo "export SENDGRID_API_KEY='YOUR_API_KEY'" > sendgrid.env
echo "sendgrid.env" >> .gitignore
source ./sendgrid.env
```

**Comment by laynetrain** [comment]
However, I get `undefined method `configure' for SendGrid:Module` when I attempt this

**Comment by thinkingserious** [comment]
Hello @laynetrain,

You can store your API key in any secure location. Our example is meant to encourage that best practice.

In your case, something similar to the following should work:

```ruby
config.api_key = Rails.application.secrets.sendgrid['api_key']
sg = SendGrid::API.new(api_key: config.api_key)
```

I hope that helps.

Thanks!

With Best Regards,

Elmer
