### ISSUE TITLE
Mail parameter aliases or examples

### ISSUE THREAD

**Issue by bfischer1121** [sendgrid/sendgrid-ruby#15]
Just spent the longest time trying to get the "fromname" param to work because I was referencing the Web API docs and, since most params are identical, just assumed it'd be set using "fromname". It needed to be set using "from_name".

I think aliasing the names or adding examples of every transformed param to the readme would help others have a smoother time using the gem.

**Comment by eddiezane** [comment]
Thanks for the feedback! We have all the available params listed [here](https://github.com/sendgrid/sendgrid-ruby#available-params), but it could use some improvements.
