### ISSUE TITLE
NoMethodError: undefined method `default_sg_unique_args'

### ISSUE THREAD

**Issue by asimisoft** [sendgrid/sendgrid-ruby#151]
Hi, I read the article https://github.com/sendgrid/sendgrid-ruby/blob/master/examples/helpers/mail/example.rb#L21 , i implemented similar hello_world method as shown below, i am getting some errors which are explained below.

    require 'sendgrid-ruby'
    include SendGrid

    class HelloMailer
	    def self.deliver
		from = Email.new(email: 'testuser1@example.com')
		subject = 'Hello World from the SendGrid Ruby Library!'
		to = Email.new(email: 'testuser@example.com')
		content = Content.new(type: 'text/plain', value: 'Hello, Email!')
		mail = Mail.new(from, subject, to, content)

		sg = SendGrid::API.new(api_key: ENV['SENDGRID_API_KEY'], host: 'https://api.sendgrid.com'))
		
		response = sg.client.mail._('send').post(request_body: mail.to_json)
		puts response.status_code
		puts response.body
		puts response.headers
	    end
    end

##### Error:
[2] pry(main)> HelloMailer.deliver
NoMethodError: undefined method `default_sg_unique_args' for SendGrid::Client:Class
from /home/siv/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/sendgrid-1.2.4/lib/sendgrid.rb:211:in `sendgrid_json_headers'

#### Technical details:
* sendgrid-ruby Version: 4.0.8
* Ruby Version: 2.2.4

**Comment by asimisoft** [comment]
Seems issue occurred when we use sendgrid and sendgrid-ruby gems together

**Comment by thinkingserious** [comment]
Hello @asimisoft,

The officially supported SendGrid gem is [sendgrid-ruby](https://github.com/sendgrid/sendgrid-ruby).

You would either use the sendgrid-ruby gem or the third party sendgrid gem.

Thanks!

With Best Regards,

Elmer

**Comment by asimisoft** [comment]
@thinkingserious Thanks for all these infos. I have opened new ticket with new issue.
