### ISSUE TITLE
Sending an audio file from the browser through SendGrid

### ISSUE THREAD

**Issue by spyeadon** [sendgrid/sendgrid-ruby#153]
I'm trying to send a content-type "audio/webm" through send grid as either an attachment or as content on the helper.Mail object. Req.body was sent through the below axios request. The recordedBlob is equal to the blob of a MIME type audio/webm file and was recorded using the RecordRTC API. I am also having some trouble with the SG attachment API. Would that be better than sending as content? It seems like if you give the content a filetype, it will coerce the data you send into an attachment anyway...

axios.post('/api/mail', recordedBlob, {headers: {'Content-Type': 'audio/webm'}})

let contentFILE = req.body;
let content = new helper.Content("audio/webm", contentFILE, 'test.weba');

**Comment by thinkingserious** [comment]
Hello @spyeadon,

Please see this example for how to use attachments with this library: https://github.com/sendgrid/sendgrid-ruby/blob/master/examples/helpers/mail/example.rb#L69 Note that the `content` is base64 encoded.

With Best Regards,

Elmer

**Comment by spyeadon** [comment]
Thanks. Figured this out.
