### ISSUE TITLE
Problematic Sinatra dependency

### ISSUE THREAD

**Issue by skalee** [sendgrid/sendgrid-ruby#159]
#### Issue Summary

Recently released version 4.1 introduces Sinatra ~> 1.4.7 as a dependency, and that Sinatra version depends on Rack ~> 1.5. In the result, Sendgrid-Ruby is now incompatible with Rails 5 which requires Rack ~> 2.0.

Sinatra 2 works with Rack 2.0. Two release candidates have been pushed to RubyGems already.

#### Technical details:

* sendgrid-ruby Version: 4.1, master (latest commit: 59484d9)
* Ruby Version: any

**Comment by thinkingserious** [comment]
Thanks @skalee! I've added this to our backlog for further review.

@awwa, do you have any thoughts on this one? 

Reference: http://guides.rubyonrails.org/5_0_release_notes.html (requires ruby 2.2.2+)

**Comment by awwa** [comment]
Hi @thinkingserious , @skalee, 
Sinatra ~> 1.4.7 is not compatible with rails 5. It is better to investigate the compatibility with sinatra 2.0 rc and rails 5 because there might be conflict any other gems. I will check.

**Comment by awwa** [comment]
@thinkingserious 
I checked with ruby 2.3.3 and 2.4.0. It seems no problem. All process was fine. Here is the report.

1. Update the `sendgrid-ruby.gemspec` file.

``` ruby
#  spec.add_dependency 'sinatra', '~> 1.4.7'
  spec.add_dependency 'sinatra', '2.0.0.rc2'
```

2. Install sinatra 2.0.0.rc2.

```
bundle install
bundle update
:
Using sinatra 2.0.0.rc2
:
```

3. Test sendgrid-ruby
All tests are fine.

```
rake test
:
234 runs, 238 assertions, 0 failures, 0 errors, 0 skips
```

4. Build package

```
rake build
sendgrid-ruby 4.2.1 built to pkg/sendgrid-ruby-4.2.1.gem.
```

5. Create rails 5 sample application

```
cd /path/to/workspace
gem install rails -v 5.0.0
1 gem installed
rails new rails5_example
cd rails5_example
```

6. Add local sendgrid-ruby package to the Gemfile

```
gem 'sendgrid-ruby', :path => '/Users/awwa/github/sendgrid-ruby'
```

7. Install the local sendgrid-ruby package

```
bundle install
bundle update
:
Using sendgrid-ruby 4.2.1 from source at `/Users/awwa/github/sendgrid-ruby`
:
```

8. Run Rails

```
rails s

```

9. Run Sinatra

```
cd sendgrid-ruby
rackup
:
[2017-04-20 00:44:16] INFO  WEBrick::HTTPServer#start: pid=78410 port=9292
```

**Comment by gkats** [comment]
Hello, just experienced the same problem that @skalee mentioned. Is there a plan for a release soon? How can we help?

__Technical details__:
- sendgrid-ruby v4.3.0
- ruby v2.3.1
- rails v5.0.0
- actionpack v5.0.0.1

**Comment by skalee** [comment]
Guys, it really seems to be a no-brainer. You have CI on Travis, don't you? Then you can test against both Sinatra versions: 1.4 and 2.0 if you relax the dependency.

**Comment by thinkingserious** [comment]
Hi @gkats,

The best way to help is with a PR.

For now, I've added your vote to the issue to help it rise faster through our backlog.

Thanks!

With Best Regards,

Elmer

**Comment by gkats** [comment]
@thinkingserious On it :smile:

**Comment by skalee** [comment]
Now the only allowed dependency is a Sinatra's release candidate, which isn't good at all. And the Rack 1.x applications compatibility is broken (that is, still popular Rails 4 won't work).

**Comment by thinkingserious** [comment]
Thanks for the fix @skalee!

**Comment by mull** [comment]
Why is the Sinatra dependency even there at all? It seems like that should be in a separate gem(?)

**Comment by thinkingserious** [comment]
@mull, 

You are correct, in the new version of this library, we will likely break out the inbound parser into its own gem like we just did with [Node.js](https://www.npmjs.com/org/sendgrid). If you have further feedback about the this SDKs refactor, please let us know [here](https://github.com/sendgrid/sendgrid-ruby/issues/169).

Thanks for taking the time to give us some feedback!

With Best Regards,

Elmer
