### ISSUE TITLE
Error 400 while testing email sending

### ISSUE THREAD

**Issue by PedroVinicius** [sendgrid/sendgrid-ruby#163]
Howdy guys!

I need to use this library in order to send billing messages to my customers. At this moment, I have the following code:

````ruby
require 'sendgrid-ruby'

include SendGrid

from = Email.new({ email: 'flkjgflkklgfkljgfkjgf@gmail.com', name: 'My name' })

message = Mail.new(from)
message.subject = 'Teste, somente um teste.'

personalization = Personalization.new
personalization.to = Email.new(email: 'lgkfkjgfkjgjfgf@lfkjglfkjgjfgf.com.br')
personalization.substitutions = Substitution.new(key: '%bank_slip_link%', value: 'http://')

message.personalizations = personalization

message.contents = Content.new(type: 'text/html', value: '<h1>Test</h1>')
message.contents = Content.new(type: 'text/plain', value: 'Test')

message.template_id = '8afbf221-3bc8-48b1-9b7b-466017bd4dd5'

sendgrid = SendGrid::API.new(api_key: 'my-api-key-here')

response = sendgrid.client.mail._('send').post(request_body: message.to_json)

puts response.status_code
puts response.body
puts response.headers
````

I'm following the examples provided by you in this repo, but when I execute my code, I receive the following error message:

````
{"errors":[{"message":"Invalid type. Expected: object, given: string.","field":"personalizations.0.to.0","help":"http://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/errors.html#message.personalizations.to"},{"message":"Invalid type. Expected: object, given: string.","field":"content.0","help":null}]}
{"server"=>["nginx"], "date"=>["Thu, 18 May 2017 22:38:05 GMT"], "content-type"=>["application/json"], "content-length"=>["304"], "connection"=>["close"], "x-frame-options"=>["DENY"], "access-control-allow-origin"=>["https://sendgrid.api-docs.io"], "access-control-allow-methods"=>["POST"], "access-control-allow-headers"=>["Authorization, Content-Type, On-behalf-of, x-sg-elas-acl"], "access-control-max-age"=>["600"], "x-no-cors-reason"=>["https://sendgrid.com/docs/Classroom/Basics/API/cors.html"]
````
Looking at my code, I can't find anything wrong. Can you point me where is my mistake?

I'm using Ruby 2.4.0 and this library's 4.3.3 version.

**Comment by thinkingserious** [comment]
Hi @PedroVinicius,

Thanks for reaching out!

Could you please provide the value of `message.to_json` before you call `sendgrid.client.mail._('send').post(request_body: message.to_json)`?

Thanks!

**Comment by PedroVinicius** [comment]
Yes, of course!

See:
````json
{"from" : { "email" : "xxxxxxxxxxx@gmail.com", "name" : "Pedro Vinícius"}, "subject" : "Teste, somente um teste.", "personalizations" : [{"to" : ["null"]}, {"to" : [{"email" : "xxxxxxxxx@xxxxxx.com.br"}], "substitutions":{"%bank_slip_link%" : "http://xxxxxxxx.xxx"}}], "content" : ["null", {"type" : "text/html", "value" : "<h1>Test</h1>"}, {"type" : "text/plain", "value" : "Test"}], "template_id" : "8afbf221-3bc8-48b1-9b7b-466017bd4dd5"}
````

**Comment by thinkingserious** [comment]
Hi @PedroVinicius,

Can you please replace: 

`message = Mail.new(from)`

with

```ruby
message = Mail.new

message.from = from
```

When you call `Mail.new` with parameters, [the constructor creates the personalization object](https://github.com/sendgrid/sendgrid-ruby/blob/master/lib/sendgrid/helpers/mail/mail.rb#L820) for you. Then you created a second personalization object, causing the first object to have null values. [Here](https://github.com/sendgrid/sendgrid-ruby/blob/master/examples/helpers/mail/example.rb#L21) is a full example.

I apologize for the confusion.

Please let me know how that goes. Thanks!

**Comment by PedroVinicius** [comment]
This worked well! Thank you so much @thinkingserious! :smiley:

**Comment by thinkingserious** [comment]
Awesome, thanks for the follow up @PedroVinicius!

**Comment by NiekPas** [comment]
In case anyone is still running into this issue (like I was), changing `Mail.new(your, params, go, here)` to `SendGrid::Mail.new(your, params, go, here)` fixed it for me.

**Comment by thinkingserious** [comment]
Hi @NiekPas,

Do you mind adding your solution [here](https://github.com/sendgrid/sendgrid-ruby/blob/master/TROUBLESHOOTING.md) as part of [hacktoberfest](https://sendgrid.com/blog/announcing-hacktoberfest-2017/)?

With Best Regards,

Elmer

**Comment by dangerrg** [comment]
Hi guys,

I'm running my Rails 5.1.7 app (Ruby v.2.6.3) with SendGrid(6.0.0)+ Heroku.

I've set up a contact_us form for the Users to send a message (email). Add everything works perfectly well in the development environment with the basic Sendgrid setup. 

But, I'm having an ``error 400`` when I try to run my production environment:

`{"errors":[{"message":"The provided authorization grant is invalid, expired, or revoked","field":null,"help":null}]}
{"server"=>["nginx"], "date"=>["Sat, 16 Nov 2019 13:52:51 GMT"], "content-type"=>["application/json"], "content-length"=>["116"], "connection"=>["close"], "access-control-allow-origin"=>["https://sendgrid.api-docs.io"], "access-control-allow-methods"=>["POST"], "access-control-allow-headers"=>["Authorization, Content-Type, On-behalf-of, x-sg-elas-acl"], "access-control-max-age"=>["600"], "x-no-cors-reason"=>["https://sendgrid.com/docs/Classroom/Basics/API/cors.html"]}`

So, I try creating a new upgraded SENDGRID_API_KEY, but it still not working I get the same error

here is my code:

`class MessageMailer < ApplicationMailer`
  `require "sendgrid-ruby"`
  `include SendGrid`

 ` def contact(message)`
    `@message = message`

    from = Email.new(email: "no-reply@casineros-cubanos.com")
    to = Email.new(email: @message.email)
    subject = 'casineros cubanos Blog'
    content = Content.new(type: 'text/plain', value: "Hi dear #{@message.name}! Thanks for your massage, we will get back to you soon.")
    mail = SendGrid::Mail.new(from, subject, to, content)

    sg = SendGrid::API.new(api_key: ENV['SENDGRID_API_KEY'])
    begin # to read error messages
        response = sg.client.mail._("send").post(request_body: mail.to_json)
    rescue Exception => e
        puts e.message
    end

    puts response.status_code
    puts response.body
    puts response.headers

   `end`
`end`

Any help or hint would be appreciated.

Thanks
