### ISSUE TITLE
Error: The attachment content must be base64 encoded

### ISSUE THREAD

**Issue by poorva29** [sendgrid/sendgrid-ruby#174]
I have -
`attachment = Attachment.new`
`attachment.content = Base64.encode64(File.open(fpath, 'rb').read)`
`attachment.type = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'`
`attachment.filename = fname`
`attachment.disposition = 'attachment'`
`attachment.content_id = 'Reports Sheet'`
`mail.add_attachment(attachment)`

Where 'content' is base64 encoded (verified that it is valid).
It does not exceeded the limit for content too , the length is 209
on calling `sg.client.mail._('send').post(request_body: mail.to_json)`

still I receive error -
`{"errors":[{"message":"The attachment content must be base64 encoded.","field":"attachments.0.content","help":"http://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/errors.html#message.attachments.content"}]} {"server"=>["nginx"], "date"=>["Tue, 05 Sep 2017 06:34:36 GMT"], "content-type"=>["application/json"], "content-length"=>["209"], "connection"=>["close"], "access-control-allow-origin"=>["https://sendgrid.api-docs.io"], "access-control-allow-methods"=>["POST"], "access-control-allow-headers"=>["Authorization, Content-Type, On-behalf-of, x-sg-elas-acl"], "access-control-max-age"=>["600"], "x-no-cors-reason"=>["https://sendgrid.com/docs/Classroom/Basics/API/cors.html"]}`

Ruby Version: 2.4
senfgrid-ruby: 5.1.0

**Comment by thinkingserious** [comment]
Hi @poorva29,

Do you mind sending the original attachment + the base64 encoded version (in a .txt file) to dx@sendgrid.com?

Thanks!

With Best Regards,

Elmer

**Comment by poorva29** [comment]
@thinkingserious 

My problem was solved by using `Base64.strict_encode64` which removes `\n` which is introduced by `encoded_64` just to maintain backward compatibility with applications which still cannot accept a long line of more than 60 characters.

**Comment by thinkingserious** [comment]
That's awesome @poorva29,

Thanks for sharing your result with us. Would you mind creating a PR to add that use case here? https://github.com/sendgrid/sendgrid-ruby/blob/master/USE_CASES.md

You can refer [here](https://github.com/sendgrid/sendgrid-csharp/blob/master/USE_CASES.md#attachments) and [here](https://github.com/sendgrid/sendgrid-ruby/blob/master/examples/helpers/mail/example.rb#L62) for a completed example.

If you do not wish to do, no worries. I'll make sure to add it to our back log to help others :)

With Best Regards,

Elmer

**Comment by poorva29** [comment]
Thanks for getting back @thinkingserious , I will create a PR and add this in the use cases.

**Comment by ryzokuken** [comment]
@thinkingserious where should I add the code inside the `USE_CASES.md` file?

**Comment by mbernier** [comment]
@poorva29 check #241 and make sure this matches with your PR!
