### ISSUE TITLE
cannot actually assign an array to mail.to 

### ISSUE THREAD

**Issue by RichardGrossman** [sendgrid/sendgrid-ruby#19]
Readme.md states this:

```mail.to = ['Example Dude <example@email.com>', 'john@email.com']```

That exact example throws an error on send: invalid email address.  Even using pure email addresses.

```
mail_client = SendGrid::Client.new do |c|
      c.api_user = ENV['SENDGRID_USERNAME']
      c.api_key = ENV['SENDGRID_PASSWORD']
end
outbound.each do |o|
        mail = SendGrid::Mail.new do |m|
          mailstr = o.email_to
          m.to = ['Example Dude <example@email.com>', 'john@email.com']
          m.from = o.email_from
          m.subject = o.email_subject
          m.html = o.email_content
        end
        send_result = mail_client.send(mail)
end```

#SendGrid::Exception: {"message": "error", "errors": ["Invalid email address Example Dude <example@email.com>"]}

**Comment by VictorAcatrinei** [comment]
Hi there,
I have also tested the code and also the code we have on our docs page, and it is throwing the same error. Did we have any kind of changes in our library lately ?

**Comment by coderdave** [comment]
This works for me in version 1.1.6

**Comment by jeffblake** [comment]
Doesn't work for me.


I'm not getting errors, its delivering to the correct email, but its not setting the `to_name`... leaving the email unpersonalized.

**Comment by coderdave** [comment]
@jeffblake Yeah, that's not working but the array works.

**Comment by thinkingserious** [comment]
@RichardGrossman,

Thanks for the feedback!

This should no longer be an issue with the new version of this library, which will replace this library in a few weeks. The new library uses the v3 /mail/send endpoint: https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html

You can check out the new library here: https://github.com/sendgrid/sendgrid-ruby/tree/v3beta

With Best Regards,

Elmer
