### ISSUE TITLE
Create a tutorial to create a Slack event integration with Ruby using this SDK

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-ruby#191]
Create a tutorial that explains how to create a simple [integration with Slack](https://api.slack.com/events-api) that allows an email to be triggered based on some [defined event](https://api.slack.com/events).

The example should utilize best practices for storing credentials.

Please add the tutorial to USE_CASES.md.

**Comment by sitaramshelke** [comment]
Hey @thinkingserious, I can try this out. Can you mention what should an example do?

**Comment by thinkingserious** [comment]
[Here](https://github.com/sendgrid/sendgrid-go/pull/182) you go. Thanks!
