### ISSUE TITLE
Add a Code Of Conduct

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-ruby#195]
Add a file to the root of this repo called CODE_OF_CONDUCT.md, with the content from the [same file in our docs repo](https://github.com/sendgrid/docs/pull/3048).

**Comment by rahulbajaj0509** [comment]
i can handle this :)

**Comment by mbernier** [comment]
Hey @rahulbajaj0509 it looks like this one is complete! I should have closed the issue, my apologies
