### ISSUE TITLE
Make SendGrid permissions management easy

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-ruby#197]
Create a class for managing permission scopes that has the following features:

- Allow you to add create, delete, read, update permissions for each of the groups defined [here](https://sendgrid.com/docs/API_Reference/Web_API_v3/API_Keys/api_key_permissions_list.html)  -- these can be hard coded in
- Allow for creating an array of all the scopes possible, as a "create admin permissions" method
- Allow for "read only" which pulls only read permissions
- Create a method for each of the example groups [here](https://sendgrid.com/docs/Classroom/Basics/API/api_key_permissions.html#-Example-Permissions-for-Common-API-Key-Use-Cases), which provide the appropriate permissions. Note: Some of these are redundant with the previous requests on this issue.

**Comment by rahulbajaj0509** [comment]
i want to contribute but i am new, can you help me resolve this bug? 
What are permission scopes? (If possible please provide me some links that i can refer for solving this bug)

**Comment by thinkingserious** [comment]
Hi @rahulbajaj0509,

Thanks for offering to help!

The links are included in the bullets above, for example:
https://sendgrid.com/docs/API_Reference/Web_API_v3/API_Keys/api_key_permissions_list.html
https://sendgrid.com/docs/Classroom/Basics/API/api_key_permissions.html#-Example-Permissions-for-Common-API-Key-Use-Cases

You will want to read through those before beginning. 

Thanks!

With Best Regards,

Elmer

**Comment by sony-mathew** [comment]
Hey if @rahulbajaj0509  is not taking this up, I can.

**Comment by thinkingserious** [comment]
Thank you @sony-mathew!

**Comment by sony-mathew** [comment]
Hey @thinkingserious, I have a doubt. Is this is the API that should be used for updating scopes? 

[https://sendgrid.com/docs/API_Reference/Web_API_v3/API_Keys/index.html#Update-the-name-amp-scopes-of-an-API-Key-PUT](https://sendgrid.com/docs/API_Reference/Web_API_v3/API_Keys/index.html#Update-the-name-amp-scopes-of-an-API-Key-PUT)

**Comment by thinkingserious** [comment]
Hi @sony-mathew,

Yes, that's correct. Thanks!

**Comment by sony-mathew** [comment]
Hi @thinkingserious, really sorry to bother you again. But this scopes in this link [https://sendgrid.com/docs/API_Reference/Web_API_v3/API_Keys/api_key_permissions_list.html](https://sendgrid.com/docs/API_Reference/Web_API_v3/API_Keys/api_key_permissions_list.html) and the scopes in this one, [https://sendgrid.com/docs/Classroom/Basics/API/api_key_permissions.html](https://sendgrid.com/docs/Classroom/Basics/API/api_key_permissions.html) have some differences. Shall I go with the complete scopes given in first link?

**Comment by sony-mathew** [comment]
Hi @thinkingserious, sorry to bother you again and being silly. So with this class, do you intend to fire request to update an api_key with the new scopes or just return an array of scopes. 
For eg: say when I call `create_admin_scopes` do i need to fire an api call to give full access for a particular api_key or just return the admin scopes as an array?

**Comment by thinkingserious** [comment]
Hi @sony-mathew,

No problem :)

For this particular issue, all we are asking is for the implementation of the features described in the issue. Any other features should probably be in a new issue.

With Best Regards,

Elmer
