### ISSUE TITLE
Add How to Setup a Domain Whitelabel and How to View Email Statistics to USE_CASES.md

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-ruby#204]
Please see [this](https://github.com/sendgrid/sendgrid-csharp/blob/master/USE_CASES.md#how-to-setup-a-domain-whitelabel) for an example.

**Comment by alanunruh** [comment]
Hey @thinkingserious - I'd like to pitch in here. For clarification, this PR looks to be documentation that could be replicated from the existing doc with relevant links. Just want to make sure I'm not missing anything. Thanks!

**Comment by thinkingserious** [comment]
You got it @alanunruh, thanks!

**Comment by alanunruh** [comment]
Submitted in PR #205.

**Comment by thinkingserious** [comment]
Thank you!

**Comment by ryzokuken** [comment]
@thinkingserious should this be closed?
