### ISSUE TITLE
Attach files to email from S3

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-ruby#207]
This should be added to the Mail helper method, where the file that is attached can be sitting on an S3 bucket.
In most circumstances, for Spam detection reasons, it would be better to link to the file- however, there are legitimate use cases for attaching a file. Exaple: Receipt PDFs

**Comment by eliotsykes** [comment]
Until this is implemented, do you recommend any ways to do this currently? Where only an s3 URL is supplied to sendgrid (via SMTP or v2/v3 API or using this sendgrid-ruby gem), and SendGrid attaches the file (unfortunately inserting the URL into the email body isn't an option).

**Comment by ThePraveen** [comment]
Has this been solved?
I need this  in sendgrid-ruby gem

**Comment by eliotsykes** [comment]
@ThePraveen I don't think it has yet as this issue is open. In case it helps, it looks like v2 of the API supports attaching s3 URLs: https://github.com/sendgrid/sendgrid-nodejs/issues/280

**Comment by thinkingserious** [comment]
@ThePraveen,

Thanks for the comment! Your comment adds a vote to the priority of this issue to help it rise up our backlog.

With Best Regards,

Elmer

**Comment by PanMan** [comment]
I guess this isn't possible yet?

**Comment by childish-sambino** [comment]
I've created an internal ticket to track this request (_reference ID: EID-2818_). I will circle back here when there's an update, but closing the issue here as it's not something that can be done in client-side code (w/o download/uploading/streaming the files).
