### ISSUE TITLE
Template Engine support

### ISSUE THREAD

**Issue by yez** [sendgrid/sendgrid-ruby#21]
I was wondering if there were plans to support your [Template Engine](https://sendgrid.com/docs/API_Reference/Web_API_v3/Template_Engine/index.html). If there is not I'd be happy to get involved and build the features I would like to use.

**Comment by simkessy** [comment]
+1

**Comment by Timbinous** [comment]
+1

**Comment by thinkingserious** [comment]
We plan to include template engine support, currently via https://github.com/sendgrid/sendgrid-ruby/pull/23
