### ISSUE TITLE
Get all the stats for a date range

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-ruby#213]
We have various types of stats global stats, category stats, and subuser stats.
For some users, being able to pull these stats and send them somewhere is ideal.
Please create a nice helper for pulling stats from each of these locations so that the data can be sent to a database.

**Comment by awinabi** [comment]
Working on this issue. The following is the public api for this helper.

```ruby
sg_client = SendGrid::API.new(api_key: ENV['SENDGRID_API_KEY']).client
stats = SendGrid::EmailStats.new(sendgrid_client: sg_client)

# Fetch stats by day, between 2 dates
from = Date.new(2017, 10, 01)
to = Date.new(2017, 10, 12)

email_stats = stats.by_day(from, to)
email_stats.metrics

```
