### ISSUE TITLE
API Key support

### ISSUE THREAD

**Issue by plockxng** [sendgrid/sendgrid-ruby#22]
Hi, documentation denotes that for the api_user and api_key, it requires the actual account name and password. Could you please implement the feature to use an API key instead of the SendGrid password?

```ruby

require 'sendgrid-ruby'

# As a hash
client = SendGrid::Client.new(api_user: 'SENDGRID_USERNAME', api_key: 'SENDGRID_PASSWORD')

# Or as a block
client = SendGrid::Client.new do |c|
  c.api_user = 'SENDGRID_USERNAME'
  c.api_key = 'SENDGRID_PASSWORD'
end
```
Thanks,
Preston

**Comment by mgrecar** [comment]
:+1

**Comment by thinkingserious** [comment]
We are implementing this in an upcoming release, you can check the progress here: https://github.com/sendgrid/sendgrid-ruby/tree/1.0.0.wip

Thanks!

**Comment by gawin** [comment]
+1

**Comment by thinkingserious** [comment]
@plockxng @mgrecar @gawin 

That change is live: https://github.com/sendgrid/sendgrid-ruby#usage

Please let me know if you run into any issues. Thanks!

**Comment by plockxng** [comment]
@thinkingserious, works great for me, thanks a bunch!
