### ISSUE TITLE
Add CodeCov support to .travis.yml

### ISSUE THREAD

**Issue by mbernier** [sendgrid/sendgrid-ruby#258]
Issue Summary

Add this to our travis.ci configuration so that code coverage tests will run!

https://github.com/codecov/example-ruby/blob/master/.travis.yml

**Comment by alanunruh** [comment]
Hey @mbernier - I'll take this one!

**Comment by rahulpuroht** [comment]
#261

**Comment by alanunruh** [comment]
Alright, well, I was just getting ready to submit my PR for this issue but it looks like @rahulpuroht just submitted one. So, I guess I'll remove myself from this issue. I'll take a look and see if there's something else I can contribute to in a timely manner.

**Comment by childish-sambino** [comment]
Fixed by https://github.com/sendgrid/sendgrid-ruby/pull/368
