### ISSUE TITLE
Update ruby-http-client dependency to support v3.3.0

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-ruby#259]
https://github.com/sendgrid/ruby-http-client/releases/tag/v3.3.0
https://github.com/sendgrid/sendgrid-ruby/blob/master/sendgrid-ruby.gemspec#L22

We should probably update this such that minor version bumps are always updated.

**Comment by mptap** [comment]
@thinkingserious: PR: #260
