### ISSUE TITLE
how to send an email with an image via the API?

### ISSUE THREAD

**Issue by arsewizz** [sendgrid/sendgrid-ruby#279]
how to send an email with an image via the API? I can send text easily but the problem that I have is the images

**Comment by abury** [comment]
@arsewizz, assuming you're sending a HTML email, you would just include an `img` tag in the HTML body.

The image itself would have to be hosted somewhere else, and the img would just reference it.

**Comment by arsewizz** [comment]
I'm using angular2 for frontend ans rails for backend. My API is rest

**Comment by abury** [comment]
The architecture doesn't really make much of a difference. If you send a HTML email, you just need to include the img reference inside the body of the email. What's the confusion exactly?

**Comment by thinkingserious** [comment]
Hello @arsewizz,

Do you want the image to be attached or inline?

With Best Regards,

Elmer

**Comment by arsewizz** [comment]
hey @thinkingserious , i want to send pictures via curl. possible ?

e.g : http.post("urlApi","picture")

**Comment by arsewizz** [comment]
I created an API with rails, but my frontend is ionic and my problem is to send a photo with a post by the method http

**Comment by thinkingserious** [comment]
Hello @arsewizz,

How are you currently sending email through SendGrid in your app?

**Comment by arsewizz** [comment]
yes, only text but i want to be able to send images...

**Comment by thinkingserious** [comment]
Hi @arsewizz,

My apologies for not being clear. What I mean is, what version of this library are you using and how are you implementing the code? If you can provide a code sample, that would be wonderful.

Thank you!

With Best Regards,

Elmer

**Comment by arsewizz** [comment]
from = params[:from]
				to = params[:to]
				body = params[:body]
				content = params[:content]
				photo = parse_image_data(params[:photo]) if params[:photo]
				#params[:image] = parse_image_data(params[:image]) if params[:image]
				message = Message.new(params.permit(:from,:to,:body,:content,:photo))
				if message.save
					from = Email.new(email: params[:from])
					to = Email.new(email: params[:to])
					subject = params[:body]
					content = Content.new(type: 'text/plain', value: params[:content])
					mail = Mail.new(from, subject, to, content)
					sg = SendGrid::API.new(api_key: '**********')
					response = sg.client.mail._('send').post(request_body: mail.to_json)
					puts response.status_code
					puts response.body
					puts response.headers
					render json: {data:message,message:'success'}
				else
					render json: {message:'error'}
				end

**Comment by arsewizz** [comment]
sorry for the late

**Comment by arsewizz** [comment]
here is the reference but my concern is to do it with an image
https://sendgrid.com/docs/Classroom/Build/Add_Content/attachments.html

**Comment by thinkingserious** [comment]
Hi @arsewizz,

I believe this documentation is what you need:
https://github.com/sendgrid/sendgrid-ruby/blob/master/examples/helpers/mail/example.rb#L70
https://github.com/sendgrid/sendgrid-ruby/blob/master/USE_CASES.md#adding-attachments

Please take a look and let me know if you need further assistance.

Thank you!

Elmer
