### ISSUE TITLE
Error 400 Invalid Type Expected: object, given: string.

### ISSUE THREAD

**Issue by arnoldmarunda** [sendgrid/sendgrid-ruby#285]
My Code:
```
require 'sendgrid-ruby'
require 'dotenv/load'

include SendGrid

body = <<EOF
   <h4>Hello,</h4>
   <br/>
   <p>Regards</p>
EOF

to = Email.new(email: "#{emailGuide}")
from = Email.new(email: 'user@domain.com')
subject = "Test Email"
content = Content.new(type: 'text/html', value: body)
mail = Mail.new(from, subject, to, content)
sg = SendGrid::API.new(api_key: ENV['SENDGRID_API_KEY'])
response = sg.client.mail._('send').post(request_body: mail.to_json)
```
Error:
`{"errors":[{"message":"Invalid type. Expected: object, given: string.","field":"(root)","help":"http://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/errors.html#-Request-Body-Parameters"}]}`

JSON i.e mail.to_json
`{"body":{"boundary":null,"preamble":null,"epilogue":null,"charset":"US-ASCII","part_sort_order":["text/plain","text/enriched","text/html","multipart/alternative"],"parts":[],"raw_source":"","ascii_only":true,"encoding":"7bit"},"body_raw":null,"separate_parts":false,"text_part":null,"html_part":null,"errors":null,"header":[{"name":"#\u003cSendGrid","unparsed_value":":Email:0x00007ff3c7d13bf8\u003e","charset":"UTF-8","field":{"errors":[],"charset":"UTF-8","name":"#\u003cSendGrid","length":null,"element":null,"value":":Email:0x00007ff3c7d13bf8\u003e"}}],"charset":"UTF-8","defaulted_charset":true,"smtp_envelope_from":null,"smtp_envelope_to":null,"perform_deliveries":true,"raise_delivery_errors":true,"delivery_handler":null,"delivery_method":{"settings":{"address":"localhost","port":25,"domain":"localhost.localdomain","user_name":null,"password":null,"authentication":null,"enable_starttls":null,"enable_starttls_auto":true,"openssl_verify_mode":null,"ssl":null,"tls":null,"open_timeout":null,"read_timeout":null}},"transport_encoding":{},"mark_for_delete":false,"raw_source":"#\u003cSendGrid::Email:0x00007ff3c7d13bf8\u003e"}`

**Comment by thinkingserious** [comment]
Hi @arnoldmarunda,

Could you please try the following:

```ruby
require 'sendgrid-ruby'
require 'dotenv/load'

include SendGrid

body = '<h4>Hello,</h4><br/><p>Regards</p>'

to = Email.new(email: "#{emailGuide}")
from = Email.new(email: 'user@domain.com')
subject = "Test Email"
content = Content.new(type: 'text/html', value: body)
mail = Mail.new(from, subject, to, content)
sg = SendGrid::API.new(api_key: ENV['SENDGRID_API_KEY'])
response = sg.client.mail._('send').post(request_body: mail.to_json)
```

Thanks!

With Best Regards,

Elmer

**Comment by RogerPodacter** [comment]
@arnoldmarunda were you ever able to solve this? @thinkingserious's solution doesn't work for me—I get the same error.

Also does `http://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/errors.html#-Request-Body-Parameters` even go anywhere? Seems like it refers to an anchor that doesn't exist?

**Comment by thinkingserious** [comment]
Hello @RogerPodacter,

Do you mind sharing your code so that I may try to reproduce the error?

With Best Regards,

Elmer

**Comment by optilyze** [comment]
Hey, I get this error just cut and pasting the example from https://app.sendgrid.com/guide/integrate/langs/ruby

i.e., 
require 'sendgrid-ruby'
include SendGrid

from = Email.new(email: 'test@example.com')
to = Email.new(email: 'test@example.com')
subject = 'Sending with SendGrid is Fun'
content = Content.new(type: 'text/plain', value: 'and easy to do anywhere, even with Ruby')
mail = Mail.new(from, subject, to, content)

sg = SendGrid::API.new(api_key: ENV['SENDGRID_API_KEY'])
response = sg.client.mail._('send').post(request_body: mail.to_json)
puts response.status_code
puts response.body
puts response.headers

**Comment by optilyze** [comment]
Oh, and if anyone like me ends up here, the answer seems to be that Mail is some other Module/Class/Whatever (maybe from Action Mailer?) so you need to replace mail = Mail.new... with mail = SendGrip::Mail.new...

From https://github.com/sendgrid/sendgrid-ruby/issues/163

**Comment by thinkingserious** [comment]
Thanks for sharing the solution @optilyze!

**Comment by slothbear** [comment]
Thanks @optilyze! Any chance the example code could be enhanced? For a short example like this, I'd rather not `include SendGrid`. That way all of the SendGrid stuff must be qualified and cannot conflict with other names. Those who know how to use `include` will figure out that part.

**Comment by kplimack** [comment]
@slothbear the `Include` directive is used for mixing in _modules_ to your class. You can also instantiate a `SendGrid::Mail` object an use that object directly without mixing.  By default your class is looking for definitions inside of it, in order to access classes outside of your current context, you can use `::Mail` or `::SendGrid::Mail` to access the correct classes.

**Comment by jmoon90** [comment]
`SendGrid::Mail` fixed my issue too. However, the example did not work in my `rails console`. It worked locally from `binding.pry``

**Comment by dangerrg** [comment]
Hi guys,

I'm running my Rails 5.1.7 app (Ruby v.2.6.3) with SendGrid(6.0.0)+ Heroku.

I've set up a contact_us form for the Users to send a message (email). Add everything works perfectly well in the development environment with the basic Sendgrid setup. 

But, I'm having this ``error 400`` when I try to run my production environment:

`{"errors":[{"message":"The provided authorization grant is invalid, expired, or revoked","field":null,"help":null}]}
{"server"=>["nginx"], "date"=>["Sat, 16 Nov 2019 13:52:51 GMT"], "content-type"=>["application/json"], "content-length"=>["116"], "connection"=>["close"], "access-control-allow-origin"=>["https://sendgrid.api-docs.io"], "access-control-allow-methods"=>["POST"], "access-control-allow-headers"=>["Authorization, Content-Type, On-behalf-of, x-sg-elas-acl"], "access-control-max-age"=>["600"], "x-no-cors-reason"=>["https://sendgrid.com/docs/Classroom/Basics/API/cors.html"]}`

So, I try creating a new upgraded SENDGRID_API_KEY, but it still not working, I get the same error new error:

`{"errors":[{"message":"Invalid type. Expected: object, given: string.","field":"(root)","help":"http://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/errors.html#-Request-Body-Parameters"}]}
{"server"=>["nginx"], "date"=>["Sat, 16 Nov 2019 14:45:55 GMT"], "content-type"=>["application/json"], "content-length"=>["191"], "connection"=>["close"], "access-control-allow-origin"=>["https://sendgrid.api-docs.io"], "access-control-allow-methods"=>["POST"], "access-control-allow-headers"=>["Authorization, Content-Type, On-behalf-of, x-sg-elas-acl"], "access-control-max-age"=>["600"], "x-no-cors-reason"=>["https://sendgrid.com/docs/Classroom/Basics/API/cors.html"]}`

here is my code:

`class MessageMailer < ApplicationMailer`
  `require "sendgrid-ruby"`
  `include SendGrid`

 ` def contact(message)`
    `@message = message`

    from = Email.new(email: "no-reply@casineros-cubanos.com")
    to = Email.new(email: @message.email)
    subject = 'casineros cubanos Blog'
    content = Content.new(type: 'text/plain', value: "Hi dear #{@message.name}! Thanks for your massage, we will get back to you soon.")
    mail = SendGrid::Mail.new(from, subject, to, content)

    sg = SendGrid::API.new(api_key: ENV['SENDGRID_API_KEY'])
    begin # to read error messages
        response = sg.client.mail._("send").post(request_body: mail.to_json)
    rescue Exception => e
        puts e.message
    end

    puts response.status_code
    puts response.body
    puts response.headers

   `end`
`end`

Any help or hint would be appreciated.

Thanks

**Comment by viral810** [comment]
This has worked for me
```ruby
require 'sendgrid-ruby'
include SendGrid

from = Email.new(email: 'pviral810@gmail.com')
to = Email.new(email: 'pviral810@gmail.com')
subject = 'Sending with SendGrid is Fun'
content = Content.new(type: 'text/plain', value: 'and easy to do anywhere, even with Ruby')
mail = SendGrid::Mail.new(from, subject, to, content)

sg = SendGrid::API.new(api_key: ENV['SENDGRID_API_KEY'])
response = sg.client.mail._('send').post(request_body: mail.to_json)
puts response.status_code
puts response.body
puts response.headers
```
The error is in this line, as
`mail = Mail.new(from, subject, to, content)`
should be
`mail = SendGrid::Mail.new(from, subject, to, content)`
