### ISSUE TITLE
substitution tags gets replaced only sometimes

### ISSUE THREAD

**Issue by Elyahou** [sendgrid/sendgrid-ruby#286]
#### Issue Summary

I am sending the same email multiple times to check the substitution functionality. I see that in result the substitution tags are replaced only sometimes on the received email.

#### Steps to Reproduce

1. Create a template with substition tags for example: -link1- and -link2-
2. Send a mail using sendgrid-ruby gem see code below
3. The received email not always contains the substition tags, for the same template, same data and same parameters

I can see tht the generated json looks good:

```ruby
{"from"=>{"email"=>"***@gmail.com"},
 "subject"=>"test email",
 "personalizations"=>
  [{"to"=>[{"email"=>"***@gmail.com"}],
    "substitutions"=>
     {"-link1-"=>
       "***",
      "-link2-"=>
       "***"}
```

```ruby
def send_template_email(id, from, to, subject, params = {})
    mail = Mail.new
    mail.from = Email.new(email: from)
    mail.subject = subject
    personalization = Personalization.new
    personalization.add_to(Email.new(email: to))
    params.each { |key, value| personalization.add_substitution(Substitution.new(key: "-#{key.to_s}-", value: value)) }
    mail.add_personalization(personalization)
    mail.template_id = id
    response = client.mail._('send').post(request_body: mail.to_json)
  end
```

#### Technical details:

* sendgrid-ruby: 5.2.0
* Ruby Version: 2.5.0

**Comment by thinkingserious** [comment]
Thanks for taking the time to report this @Elyahou,

I've added this to our backlog for further investigation.

With Best Regards,

Elmer

**Comment by thinkingserious** [comment]
Hello @Elyahou,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
