### ISSUE TITLE
How use http proxy to send mails?

### ISSUE THREAD

**Issue by gowthamsadasivam** [sendgrid/sendgrid-ruby#287]
#### Issue Summary

My rails web application runs behind a corporate firewall which doesn't allow direct internet access. The usual tools like apt, curl are just working fine by setting the environment variable "http_proxy" and "https_proxy".

The rails application uses "sendgrid-ruby" gem to send emails, unfortunately the application doesn't respect the "http_proxy" variable and always tries to send the emails by directly connecting to the internet. which eventually fails due to no direct internet connections are allowed.

I would like to know, Is there a way to use the proxy servers to send emails using SendGrid API. 

I have searched on other SendGrid packages and could relate to the following issues:

Java Example:
https://github.com/sendgrid/sendgrid-java/issues/138
https://github.com/sendgrid/sendgrid-java/issues/182

CSharp Example:
https://github.com/sendgrid/sendgrid-csharp/issues/197

Is there a similar solution exists for SendGrid-ruby library?

#### Steps to Reproduce

1. Disconnect direct internet access from the server.
2. Setup a working portforward/proxy server and set "http_proxy" and "https_proxy" environment variables using "/etc/environment" and source it to the current shell.
3. Try sending email using SendGrid API.
4. Now you will be able to see that mail sending failed in either stdout/stderr or the log file.

#### Technical details:

* sendgrid-ruby Version: sendgrid-ruby-5.2.0
* Ruby Version: 2.2.6p396 (2016-11-15 revision 56800) [x86_64-linux]
* RVM Version: 1.29.3

**Comment by thinkingserious** [comment]
Hi @gowthamsadasivam,

Thanks for the heads up, I have [created an issue](https://github.com/sendgrid/ruby-http-client/issues/70) (please follow along there) to allow for setting a proxy.

With Best Regards,

Elmer
