### ISSUE TITLE
Updates for the new Email Activity API (beta)

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-ruby#288]
SendGrid has added an API to download information from the Email Activity feed. There are four new endpoints:
* [GET /messages](https://sendgrid.api-docs.io/v3.0/email-activity/filter-all-messages)
* [GET /messages/{msg_id}](https://sendgrid.api-docs.io/v3.0/email-activity/filter-messages-by-message-id)
* [POST /messages/download/](https://sendgrid.api-docs.io/v3.0/email-activity/request-csv)
* [GET /messages/download/{download_uuid}](https://sendgrid.api-docs.io/v3.0/email-activity/download-csv)

A getting started doc for the API is [here](https://sendgrid.com/docs/API_Reference/Web_API_v3/Tutorials/getting_started_email_activity_api.html).

The following items need to be updated in this repo:
* [USAGE.md](https://github.com/sendgrid/sendgrid-python/blob/master/USAGE.md)
* [/examples](https://github.com/sendgrid/sendgrid-python/tree/master/examples) (create a `messages` folder with a file `messages.py`)
* [Tests](https://github.com/sendgrid/sendgrid-python/blob/master/test/test_sendgrid.py)
* [USE_CASES.md](https://github.com/sendgrid/sendgrid-python/blob/master/USE_CASES.md)

**Comment by mlabarca** [comment]
Would this be considered for #hacktoberfest 2018? I actually used this api manually making requests with thypoeus, this would be handy.

**Comment by thinkingserious** [comment]
Yes. However, I think the PR needs to be submitted in the month of October for it to officially count.

**Comment by dhoeric** [comment]
I can handle in this week if you're not available! @mlabarca

**Comment by mlabarca** [comment]
Go for it Eric, I haven't been able to get to it. 👍

**Comment by thinkingserious** [comment]
Thanks @dhoeric and @mlabarca!

**Comment by jeremygpeterson** [comment]
What's the status of this Feature request?

**Comment by amsimon** [comment]
Any update on this?

**Comment by jeremygpeterson** [comment]
This is what I had to do to get this working:
