### ISSUE TITLE
how can I send multipart mail?

### ISSUE THREAD

**Issue by hanahiroAze** [sendgrid/sendgrid-ruby#289]
#### Issue Summary

I'm trying to send multipart(text/html) mail like below. 

```rb
from = SendGrid::Email.new(email: "from_mail", name: "name")
to = SendGrid::Email.new(email: "to_mail")
subject = "subject"
contents = [::SendGrid::Content.new(type: "text/plain", value: "text"), ::SendGrid::Content.new(type: "text/html", value: "html")]

mail = SendGrid::Mail.new
mail.from = from
mail.subject = subject
personalization = SendGrid::Personalization.new
personalization.add_to(to)
mail.add_personalization(personalization)
mail.add_content(contents.first)
mail.add_content(contents.second)
mail.add_category(SendGrid::Category.new(name: BoronSettings.smtp.user))

sg = SendGrid::API.new(api_key: "api key")
sg.client.mail._("send").post(request_body: mail.to_json)
```

#### Steps to Reproduce

~~1. when I try like this 2mail have sent, is this expected behavior?~~
2. when I try like below `"{\"errors\":[{\"message\":\"Invalid type. Expected: object, given: string.\",\"field\":\"content.0\",\"help\":null}]}",` has been occurred. is this expected behavior?

```rb
mail.add_content(contents)
```

~~3. can I send multipart email?~~
~~https://sendgrid.kke.co.jp/docs/Tutorials/A_Transaction_Mail/send_transaction_mail.html~~

#### Technical details:

* sendgrid-ruby Version: 5.2.0
* Ruby Version: 2.4.2

**Comment by thinkingserious** [comment]
Hello,

Currently, [`add_content`](https://github.com/sendgrid/sendgrid-ruby/blob/master/lib/sendgrid/helpers/mail/mail.rb#L59) does not support passing in an array.

However, the [next version](https://github.com/sendgrid/sendgrid-ruby/issues/177) of this SDK will support an `add_contents` method that will accept an array.

If you have a moment, your feedback on issue #177 would be most appreciated.

Thanks!

With Best Regards,

Elmer
