### ISSUE TITLE
Message won't send when attachment is present

### ISSUE THREAD

**Issue by robapavas** [sendgrid/sendgrid-ruby#294]
Issue Summary

im using sendgrid for sending mails. when i attach a file (pdf or doc) i can't send it. when i comment on the $attachment it sends succesfully. when i use localhost it does attach the file and send correctly. i don't get any errors or warnings. the $response i use for debug doesn't appear either. here is the code im using

	require 'vendor/autoload.php';

	$name = $_POST['Name'];
	$email = $_POST['Email'];
	$phone = $_POST['Telephone'];
	$state = $_POST['State'];
	$manufacturing = $_POST['ManufacturingP'];
	$about = $_POST['about'];
	$manufacturing2 = implode(', ', $manufacturing);
	$file1 = $_FILES['upfile']['name'];
                      

	$from = new SendGrid\Email("domain name", "test@mydomain.com");
	$subject = 'Candidates for Manufacturing';
	$to = new SendGrid\Email("domain name", "test@mydomain.com");;
	$content = new SendGrid\Content("text/html","
	<html>
	<head>
		<title>domain</title>
	</head>
	<body>
	Name : {$name}<br>
	Email : {$email}<br>
	Telephone : {$phone}<br>
	State : {$state}<br>
	Manufacturing : {$manufacturing2}<br>
	About : {$about} 
	</body>
	</html>");

	$attachment = new SendGrid\Attachment();
	$attachment->setContentPath($file1);
	$attachment->setType('application/vnd.openxmlformats-officedocument.wordprocessingml.document');
	$attachment->setType('application/pdf');
	$attachment->setType('application/msword');
	$attachment->setDisposition("attachment");

	$mail = new SendGrid\Mail($from, $subject, $to, $content);
	$mail->addAttachment($attachment);

	$apiKey = '###########';
	$sg = new \SendGrid($apiKey);
	
	$response = $sg->client->mail()->send()->post($mail);

	echo $response->statusCode();
	print_r($response->headers());
	echo $response->body();

Technical details:

- sendgrid v3 api
- php
- godaddy hosting service

**Comment by thinkingserious** [comment]
Hello @robapavas,

It looks like posted this in the wrong repo. Please [post this issue here](https://github.com/sendgrid/sendgrid-php/issues).

Here is an [example of adding an attachment in PHP](https://github.com/sendgrid/sendgrid-php/blob/master/USE_CASES.md#attachments).

With Best Regards,

Elmer
