### ISSUE TITLE
Retrieve email clicks stats per campaign

### ISSUE THREAD

**Issue by fringify** [sendgrid/sendgrid-ruby#296]
1. There's no way to retrieve the stats for single campaign

2. There's no way to retrieve the stats for each email linked in the email. This information is available in the UI.  http://take.ms/B7V52

**Comment by thinkingserious** [comment]
Hello @fringify,

I'm checking with our product team on this one and I'll get back to you when I learn more.

Thanks!

With Best Regards,

Elmer

**Comment by thinkingserious** [comment]
Hello @fringify,

This feature is on the radar, but I don't have a firm timeline. I'll keep this issue open to notify you when there is further information. Thanks!

With Best Regards,

Elmer

**Comment by eshanholtz** [comment]
Closing as this is a non-library issue.
