### ISSUE TITLE
Unable to find or use Template Ids 

### ISSUE THREAD

**Issue by faizaankhan** [sendgrid/sendgrid-ruby#297]
I am using a trial account and currently setting up things with sendgrid. [RAILS5, RUBY 2.3.3]

While  trying to send emails using a custom template, I was unable to find the  template id, there's no such place where I could find it easily, though  I looked up into the URL and that was having an id similar to my  requirement I was searching for, when used it throws SMTP API Error, and  I received the mail below.

The template id must be a valid template id for your account. 
You provided 1b656da9-6864-463e-8c1a-e0491f900b2f

`Please tell me where to find the working template id.` also, I am unable to figure out that after doing all sender authentication etc, I am still getting my mails in spam.

P.S.: It is a Marketing Custom Template

**Comment by thinkingserious** [comment]
Hello @faizaankhan,

This SDK supports transactional templates, for which the documentation can be found [here](https://sendgrid.com/docs/API_Reference/Web_API_v3/Transactional_Templates/index.html).

With Best Regards,

Elmer

**Comment by vijeetgv** [comment]
@faizaankhan marketing templates are different from transactional templates. On the dashboard go to Templates -> Transactional (direct link if you're logged in: https://sendgrid.com/dynamic_templates ) and create a template there. Try taking the template id from its url.

**Comment by FrenchMajesty** [comment]
Running into the same issue. This is very poorly documented. 

As of 2021 there is only 1 section for templates on the website and this is what it displays.

![Screen Shot 2021-03-30 at 6 55 13 PM](https://user-images.githubusercontent.com/24761660/113071088-a6357380-9189-11eb-881f-398cabe80691.png)

However attempting to use this ID in the SDK will give you a `400 error` with the message:
> "message":"The template_id must be a valid GUID, you provided 'insertTemplateIdHere'

**Comment by SaiOduri** [comment]
@FrenchMajesty This worked for me! Thanks!!

**Comment by philmitchell** [comment]
The UI is pretty janky, but after logging out and logging back in, I found my template had an "INACTIVE" label on it. I was able to click the label (I think) and select "Make active". After that, the listed template ID (d-etc.) worked.

It now shows an "ACTIVE" label, but I no longer see any UI that lets you toggle active/inactive.
