### ISSUE TITLE
Support for the v3 Campaign API?

### ISSUE THREAD

**Issue by davidray** [sendgrid/sendgrid-ruby#30]
Do you have plans to add support for the campaign and contact API end points in this gem?

**Comment by thinkingserious** [comment]
Yes, we will be adding support for all Web API v3 endpoints, across all libraries: https://sendgrid.com/docs/API_Reference/Web_API_v3/index.html

I don't have a firm timeline right now, but it is on our roadmap.

**Comment by davidray** [comment]
Awesome thanks!
