### ISSUE TITLE
Add Dynamic Template Support

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-ruby#301]
#### Issue Summary

On 7/24/2018, our team publicly launched dynamic content for transactional templates. It is now available for all customers sending over v3 of our Mail Send API. Iterate over lists, handle conditionals and more, thanks to native support for a subset of Handlebars syntax!

More information can be found in our [blog post announcement](https://sendgrid.com/blog/how-to-use-sendgrids-dynamic-templates-for-your-transactional-emails/).

You can currently use this feature by manually creating the request body as [shown here](https://github.com/sendgrid/sendgrid-ruby/blob/master/USAGE.md#v3-mail-send). 

Now, we need to create helper code and examples for this SDK.

#### Acceptance Criteria

* [Implement a helper similar to what we have for the legacy templates](https://github.com/sendgrid/sendgrid-ruby/blob/master/USE_CASES.md#transactional-templates)
* Update the [USE_CASES.md](https://github.com/sendgrid/sendgrid-ruby/blob/master/USE_CASES.md#transactional-templates) example to demonstrate the new *Dynamic Templates* using the helper and re-name the current example to *Legacy*

#### Documentation
- [Reference Implementation](https://github.com/sendgrid/sendgrid-nodejs/pull/691#issuecomment-407490342)
- [How to Send an Email With Dynamic Transactional Templates](https://sendgrid.com/docs/User_Guide/Transactional_Templates/how_to_send_an_email_with_transactional_templates.html)
- [Using Handlebars](https://sendgrid.com/docs/User_Guide/Transactional_Templates/Using_handlebars.html)
- [Interactive API Docs](https://dynamic-templates.api-docs.io/3.0/mail-send-with-dynamic-transactional-templates/v3-mail-send)

**Comment by thinkingserious** [comment]
Please see #300 for WIP

**Comment by metaskills** [comment]
I'd like to point out the the docs and the article have the `template_id` in the wrong spot. It should be outside the `personalizations` array at the root.

**Comment by thinkingserious** [comment]
Hi @metaskills,

Are you referring this [documentation](https://sendgrid.com/docs/User_Guide/Transactional_Templates/how_to_send_an_email_with_transactional_templates.html)? If so, it looks like a fix will be deployed soon.

Thanks!

With Best Regards,

Elmer

**Comment by metaskills** [comment]
Yes, I found that `template_id` is in the wrong spot there.

**Comment by thinkingserious** [comment]
Thanks for confirming @metaskills. I'm double checking with the docs team to make sure the fix is deployed.

**Comment by heindrik** [comment]
Hi all, 

Would like to confirm if the method `add_dynamic_template_data` has not been pushed to prod. I am asking cause I am using gem version 5.2 and I am getting the following error

```
Exception encountered: NoMethodError - undefined method `add_dynamic_template_data' for #<SendGrid::Personalization:0x00005615d7b5ae08>
```

**Comment by thinkingserious** [comment]
Not yet @heindrik, please [follow this page](https://github.com/sendgrid/sendgrid-ruby/releases) for updates or you can subscribe to our [release notification emails here](https://dx.sendgrid.com/newsletter/ruby). Thanks!

**Comment by hiroshi** [comment]
For those who want to use helpers for other parts
```ruby
mail = SendGrid::Mail.new
...
body = mail.to_json
# TODO: use helper after the issue resolved https://github.com/sendgrid/sendgrid-ruby/issues/301             
body['personalizations'][0]['dynamic_template_data'] = {                                                   
  foo: 'bar'
}                                                                                                          
sg_client = SendGrid::API.new(api_key: YOUR_API_KEY).client
resp = sg_client.mail._('send').post(request_body: body)
unless resp.status_code == '202'
  raise "Error response from sendgrid API: status_code: #{resp.status_code}, body: #{resp.body}"
end
```

**Comment by Davidslv** [comment]
I can't understand how it can take so long to release this, specially when the information given is that we are waiting because of other languages.
Anyway, I'm using the code straight from master branch which includes the dynamic template data.
There was no need to make us wait so long.

**Comment by devsi** [comment]
Docs are still out of date. I had to search for this PR and [https://github.com/sendgrid/sendgrid-ruby/pull/300](url) this related link to realize I couldn't use "substitutions". How is this a year out of date and not in the docs yet?!

**Comment by courtsimas** [comment]
It blows my mind that a company as large as SendGrid still hasn't updated their docs to reflect this, nor have they updated this gem to work with their new API.

**Comment by evandertino** [comment]
I think this ticket should be closed, dynamic templates work. See https://github.com/sendgrid/sendgrid-ruby/blob/main/examples/helpers/mail/example.rb

**Comment by childish-sambino** [comment]
Example here as well: https://github.com/sendgrid/sendgrid-ruby/blob/main/use-cases/transactional-templates.md#with-mail-helper-class

Closing.

Please open a new ticket to track any additional docs work needed.
