### ISSUE TITLE
Dynamic templates with special characters

### ISSUE THREAD

**Issue by warna720** [sendgrid/sendgrid-ruby#302]
Dynamic templates does not work with åäöÅÄÖ, even though setting charset=UTF-8 in template.
The workaround was to use their respective html entity (å = `&aring;`).

The workaround does not work with variables. When not using the html entity they resolve to ? (�) and when using the html entity they are displayed as plain text.

Using following POST-data:
`{
                "from" => {
        "email" => "<from>"
    },
    "personalizations" => [
        [0] {
                               "to" => [
                [0] {
                    "email" => "<mail>"
                }
            ],
            "dynamic_template_data" => {
                    :name => "&aring;&auml;&ouml;&Aring;&Auml;&Ouml;åäöÅÄÖ",
            }
        }
    ],
         "template_id" => "<template-id>"
}
`

#### Technical details:
* sendgrid-ruby (5.2.0)
* ruby_http_client (~> 3.2)
* sinatra (>= 1.4.7, < 3)

**Comment by thinkingserious** [comment]
Have you tried encoding the strings with ISO-8859-1 encoding?

e.g. `:name => "&aring;&auml;&ouml;&Aring;&Auml;&Ouml;åäöÅÄÖ".encode(Encoding::ISO_8859_1)`

**Comment by kylearoberts** [comment]
@warna720 

I think this issue is resolved. I tested this myself and could not create any issues:

Template:
```html
    <html>
    <head>
      <title></title>
    </head>
    <body>
      <p>{{content}}</p>
      <p>{{{content}}}</p>
    </body>
    </html>
```

API Call:

```curl
curl -X POST \
  https://api.sendgrid.com/v3/mail/send \
  -H 'Authorization: Bearer XXX' \
  -H 'Content-Type: application/json' \
  -H 'cache-control: no-cache' \
  -d '{
  "personalizations": [{
    "to": [{
      "email": "to_email@domain.com",
      "name": "to_email"
    }],
    "dynamic_template_data": {
      "content": "åäöÅÄÖ"
    }
  }],
  "from": {
    "email": "from_email@domain.com",
    "name": "from_email"
  },
  "reply_to": {
    "email": "reply_to@domain.com",
    "name": "reply_to"
  },
  "template_id": "d-XXXXXXXXXXXXXX"
}'
```

Can you retest and let us know if you are still having issues?

**Comment by warna720** [comment]
@kylearoberts Sorry cannot retest. Im not contracted anymore on the project where this was a problem.
But you could not reproduce it so im closing this! :+1:
