### ISSUE TITLE
Do dynamic templates work with SMTP/smtpapi/Rails/ActionMailer?

### ISSUE THREAD

**Issue by rhuang** [sendgrid/sendgrid-ruby#305]
#### Issue Summary

Do the new dynamic templates work with SMTP? I am using the gem `smtpapi` and integrating SendGrid into the Rails `ActionMailer`.

My header code looks like this:

```
    headers_json = {
      'filters': {
        'templates': {
          'settings': {
            'enable': 1,
            'template_id': template_id  
          }
        }
      }
    }.to_json
    headers 'X-SMTPAPI' => headers_json
```

If I replace `template_id` with the new id of a new dynamic template, I get the error ""This email was not sent because the SMTPAPI header was invalid." in the activity feed. If I use the legacy template id, it works.

I'm reading this documentation (https://sendgrid.com/docs/API_Reference/SMTP_API/how_to_use_a_transactional_template_with_smtp.html) and it says:

> "If you are using the Web API v3 mail send endpoint, you can specify which transactional template you would like to use simply by setting the template ID in the template_id parameter of your JSON payload."

I can't tell whether this documentation applies to the dynamic templates or not.

I also saw this documentation (https://sendgrid.com/docs/User_Guide/Transactional_Templates/how_to_send_an_email_with_transactional_templates.html) and I'm not sure whether I need to add the new `dynamic_template_data` field to get the `handlebars` replacement working?

#### Technical details:

* sendgrid-ruby Version: `Using sendgrid-ruby 5.2.0`
* Ruby Version: ruby 2.3.3p222
* Rails Version: Rails 5.1.3

**Comment by kylearoberts** [comment]
Hello @rhuang 

Unfortunately [Transactional Templates](https://sendgrid.com/docs/User_Guide/Transactional_Templates/how_to_send_an_email_with_transactional_templates.html#-Send-a-transactional-email) were not designed to work with anything other then our [v3 Mail Send](https://dynamic-templates.api-docs.io/3.0/mail-send-with-dynamic-transactional-templates/v3-mail-send). The reason for this is that our v3 Mail Send can do checks on the data you are passing that SMTP cannot. The same is true when comparing to our v2 Mail Send. v3 Mail Send is the only method that met with our requirements for sending the new Transactional Templates. 

I'll talk with our docs team to see if we can get things to be more clear in the future. Sorry for any trouble this may cause.

Kyle

**Comment by rhuang** [comment]
Thanks @kylearoberts.

Is there a way to use the new transactional templates with v3 Mail Send and Rails ActionMailer? If not, are there plans for this?

**Comment by kylearoberts** [comment]
Hey @rhuang 

If I am not mistaken ActionMailer is only for SMTP, so the likely hood of any plan to integrate v3 Mail Send with it are likely none. I would recommend taking a look at the regular [ruby library](https://github.com/sendgrid/sendgrid-ruby) that makes v3 Mail Send calls. Also you may want to follow the issue [here](https://github.com/sendgrid/sendgrid-ruby/issues/301) where we are working to get the new templates integrated into the ruby library.

Kyle

**Comment by rhuang** [comment]
Yes, ActionMailer is only for SMTP. Got it Kyle, thanks for the input.

**Comment by thinkingserious** [comment]
Hello @rhuang,

Dynamic Templates can be used currently with the Ruby SDK. Please see [this issue](https://github.com/sendgrid/sendgrid-ruby/issues/301) for details. What we are missing is updated documentation and helper code.

With Best Regards,

Elmer

**Comment by rhuang** [comment]
@paulodeleo 

The legacy templates only work with the v2 mail send call, which also works with SMTP. The new Dynamic templates only work with the v3 API and not SMTP, because:

> The reason for this is that our v3 Mail Send can do checks on the data you are passing that SMTP cannot. The same is true when comparing to our v2 Mail Send. v3 Mail Send is the only method that met with our requirements for sending the new Transactional Templates.

https://github.com/sendgrid/sendgrid-ruby/issues/305#issuecomment-414382789

There's no way to use the new Dynamic templates with SMTP. You'll have to manually use the API from this Ruby library if you want to use Dynamic templates. If you want to send mail via SendGrid and SMTP, then you'll have to use the legacy templates.

The article that you linked still works - it's more or less my setup, with the legacy templates.

**Comment by paulodeleo** [comment]
Oh, it makes more sense now, thanks @rhuang . The SMTP API should be updated to refer only to "**Legacy** Transactional Templates" then.

**Comment by haffla** [comment]
In order to use ActionMailer with the SendGrid v3 HTTP API you can use `sendgrid-actionmailer`. There is actually a [pull request](https://github.com/eddiezane/sendgrid-actionmailer/pull/31) to support dynamic template data that is just waiting for `sendgrid-ruby` to support it.
