### ISSUE TITLE
Update integration tests to utilize StopLight.io's Prism version v2.X

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-ruby#310]
#### Issue Summary

We use a mock server for integration/contract testing that is driven by our OpenAPI specification and StopLight.io's Prism service. The service is spun up utilizing the prism.sh script in this repo.

Before writing any code, we suggest you review our `CONTRIBUTING.md` file and propose your solution for discussion here in the comments. Thank you!

#### Aceptance Criteria

* we automatically use the latest v2.X version of Prism locally, in Travis CI and in Docker
* tests pass locally, in Travis CI and using Docker
* update `CONTRIBUTING.md` documentation, if necessary

#### Notes & References

* [Prism GitHub Repo](https://github.com/stoplightio/prism)

**Comment by dipil-saud** [comment]
@thinkingserious I can take up this issue. 

- I've setup to fetch the latest prism (2.0.14) locally and run the tests. 
- All examples are passing but one (test/sendgrid/test_sendgrid-ruby#test_suppression_spam_report__email__delete) which I'll fix. 
- I'll need to then update the Dockerfile and `test/prism.sh` to install the 2.x prism.

**Comment by childish-sambino** [comment]
Closing as prism integration has been moved to https://github.com/sendgrid/sendgrid-oai/
