### ISSUE TITLE
Implement auto-deploy to package manager

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-ruby#312]
#### Issue Summary

When all tests on the master branch pass in Travis CI, we would like to auto-deploy the release to the package manager.

Before writing any code, we suggest you review our `CONTRIBUTING.md` file and propose your solution for discussion here in the comments. Thank you!

#### Aceptance Criteria

* when Travis CI passes all tests on the master branch we auto-deploy to the package manager
* the version is determined by the `CHANGELOG.md`

**Comment by dhoeric** [comment]
Hi, I would like to pick up this project.
Since the version is determined by `CHANGELOG.md`, how about we do the auto-deploy when a tag is pushed or a release is created in GitHub?

**Comment by thinkingserious** [comment]
Thanks for taking this on @dhoeric!

We also update the version [here](https://github.com/sendgrid/sendgrid-ruby/blob/master/lib/sendgrid/version.rb), if that's easier.

With Best Regards,

Elmer

**Comment by childish-sambino** [comment]
Fixed by https://github.com/sendgrid/sendgrid-ruby/pull/400
