### ISSUE TITLE
How to send context specific values like name, prices and other invoice details

### ISSUE THREAD

**Issue by shivabhusal** [sendgrid/sendgrid-ruby#32]
In transactional email 
```
<%body%>
Hello :name!, what's up
your number is :number.
This is the transactional footer
```

how to pass the variables `:number`, `:name`??

thanks,

**Comment by mklemme** [comment]
Those are passed in the sendgrid smtp headers defined in `X_mailer.rb` as an array of strings. The format you define the placeholders in your email content should match the substitution tag's key. So ":name" wouldn't work if your headers had "%name%"

```
headers "X-SMTPAPI" => {
    "sub": {
      ":name" => [user.name],
      ":number" => [amount]
    }.to_json

# the 'to' email can be overridden per action
mail(
  from: 'test@test.com',
  to: 'recipient@test.com',
  subject: "Hello World"
)
```
source: http://stackoverflow.com/questions/32790963/rails-mailer-using-sendgrid-template/34169292#34169292

documentation: https://sendgrid.com/docs/API_Reference/SMTP_API/substitution_tags.html
