### ISSUE TITLE
Refactor Getters/Setters to use Ruby Accessors

### ISSUE THREAD

**Issue by kplimack** [sendgrid/sendgrid-ruby#326]
#### Issue Summary

Many of the classes can be simplified greatly if we use _Ruby Accessors_ to replace the getters/setters for the class/instance variables. Its a simple change, but touches nearly every file in the repo's lib directory.

**Comment by RaphaelAddile** [comment]
Seems like something I can do without much ruby knowledge. I'll work on this if nobody else is doing it yet.

**Comment by rohandaxini** [comment]
@kplimack @thinkingserious Is anybody already working on this or its available for picking up to implement?

**Comment by childish-sambino** [comment]
#338 is in the backlog for review. We're (slowly) working through open PRs. Note that PRs where tests are passing are prioritized first.
