### ISSUE TITLE
Create a Use Case demonstrating the use of Dynamic Templates

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-ruby#342]
#### Issue Summary

Currently we only have a use case demonstrating the [legacy template usage](https://github.com/sendgrid/sendgrid-ruby/blob/master/USE_CASES.md#legacy-transactional-templates). We need the same for the current dynamic templates ([Java example](https://github.com/sendgrid/sendgrid-java/blob/master/USE_CASES.md), [Node.js example](https://github.com/sendgrid/sendgrid-nodejs/blob/master/packages/mail/USE_CASES.md#transactional-templates)).

#### Acceptance Criteria

* An update USE_CASES.md file with an example of how to use the new dynamic templates with and without helpers.

**Comment by thinkingserious** [comment]
For reference, support was add with [this PR](https://github.com/sendgrid/sendgrid-ruby/pull/300).

**Comment by kylearoberts** [comment]
@thinkingserious 
Ruby example should be all set.
https://github.com/sendgrid/sendgrid-ruby/pull/343
