### ISSUE TITLE
Address line not being substituted

### ISSUE THREAD

**Issue by shaqq** [sendgrid/sendgrid-ruby#371]
#### Issue Summary

When using the Email Design tool for Transactional emails, the `Unsubscribe` module has an option to add Address lines to the email. This looks like so:

![image](https://user-images.githubusercontent.com/1438493/48527057-781c9680-e84f-11e8-9348-b54fd7006dc9.png)

In the email body:
![image](https://user-images.githubusercontent.com/1438493/48527084-85d21c00-e84f-11e8-8780-3a16ea200bbf.png)

I've created a Sender Address (under the Marketing email campaigns). But, there doesn't seem to be a way to add a `sender_id` to my transactional email. And as result, the fields like `[Sender_Name]` are not being replaced.

#### Steps to Reproduce

1. Create a transactional email template
2. In the email design tool, add an unsubscribe module
3. Make sure the Address Line switch is selected, in the toolbar on the left

#### Technical details:

* sendgrid-ruby Version: 5.3.0
* Ruby Version: 2.3.1

**Comment by thinkingserious** [comment]
Hello @shaqq,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team

**Comment by NHuebner1983** [comment]
There's a thread open here as well: https://github.com/sendgrid/sendgrid-python/issues/735

It's not really related to sendgrid packages (php, ruby, python) but related to SendGrid in general.  I personally don't agree that these fields should be filled by API. I would prefer to have the option to hardcode them in the template, as my company doesn't have multiple addresses.
