### ISSUE TITLE
Unsubscribe tags not working in marketing campaign templates

### ISSUE THREAD

**Issue by dennyluan** [sendgrid/sendgrid-ruby#372]
#### Issue Summary

I'm using `sendgrid-ruby` to generate a campaign with `html_content` like so.

```ruby

    sg = SendGrid::API.new(api_key: Rails.application.secrets.sendgrid.api_key)
    html = "<html><head><title>Test</title></head><body><a href=[Unsubscribe]>Unsubscribe</a><a href=[unsubscribe]>Unsubscribe</a></body></html>"
    data = {
        "html_content": html, 
        "plain_content": "Test plain content.", 
        "segment_ids": [ 3354233 ], 
        "sender_id": 364387, 
        "subject": "Test Newsletter", 
        "suppression_group_id": 7364, 
        "title": "Template test"
     }
     response = sg.client.campaigns.post(request_body: data)
```

This works fine creating the campaign with the html_content, however, trying to schedule or send a test email from the Editor UI in the dashboard fails with:

> Please add an [unsubscribe] tag to your content. Providing an unsubscribe option is required per commercial email regulations.

![image](https://user-images.githubusercontent.com/929010/48702534-02ddf800-eba6-11e8-9fea-57f19bf89449.png)

It's only when the actual code is changed in the campaign's template that it works. 

I'm not sure if there is another preferred way of including the `[Unsubscribe]` tag in the html_content, but based on the docs, it seems that this should work and is not currently working.

* sendgrid-ruby Version: 5.3.0
* Ruby Version: 2.5.1

**Comment by dennyluan** [comment]
Somehow found this issue, which shows that this has been unclear/broken for a long time: https://github.com/sendgrid/sendgrid-ruby/issues/59

**Comment by thinkingserious** [comment]
Hello @dennyluan,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team

**Comment by Nottt** [comment]
How did you solved it?

I'm having the same issue...

**Comment by jpgoem** [comment]
How did you solved it?

I'm also having the same issue...

**Comment by dennyluan** [comment]
@jpgoem Sorry, it was a while ago but I vaguely remembered it being a simple typo, and I had to do something like `<a href=[unsubscribe]></a>`

**Comment by thinkingserious** [comment]
Thanks for helping out @dennyluan!

@jpgoem,

Has your issue been resolved?

**Comment by jpgoem** [comment]
Yes, the problem was solved by using the correct [unsubsribe] tag.
Thanks.

**Comment by MG84** [comment]
I have the same problem here. Unfortunately, I cannot find any typos.
I've noticed a really strange behavior: 
- If the campaign is in draft and I go the the html edit in my Sendgrid account, and I try to send it, it gaves me the error shown in the picture posted before. BUT, if I modify something (but not changing anything (i.e. just touching the html code)), and then try to send it, it actually sends it...

The following is the html code I use:
`<h1>Hello [%first_name | Default Value%] [%last_name | Default Value%]!</h1><div><a href=[unsubscribe]>Unsubscribe</a></div>`
