### ISSUE TITLE
How to use cc?

### ISSUE THREAD

**Issue by georgeu2000** [sendgrid/sendgrid-ruby#373]
It's not clear from the readme, examples or docs how to add a cc.

The following returned an error from the API:

```
    from = Email.new(email: 'test@example.com')
    subject = 'Test'
    to = Email.new( email: 'test@example.com' )
    body = "Email body"
    content = Content.new(type: 'text/html', value: body )
    mail = Mail.new(from, subject, to, content)

    personalization = Personalization.new
    personalization.add_cc( Email.new( email: 'test2@example.com' ))
    mail.add_personalization personalization
    
    sg = API.new(api_key: ENV['SENDGRID_API_KEY'])
    response = sg.client.mail._('send').post(request_body: mail.to_json)
```

**Comment by thinkingserious** [comment]
Hello @georgeu2000,

What was the [error returned](https://github.com/sendgrid/sendgrid-ruby/blob/master/TROUBLESHOOTING.md#error)?

Thanks!

With Best Regards,

Elmer

**Comment by georgeu2000** [comment]
Something about the email being invalid. I assumed that this is not the correct way of doing because it is complicated and cc is a basic feature. Is there some documentation of how to do it?

**Comment by kylearoberts** [comment]
@georgeu2000 

I think your issue is that you put the To outside of the personalization. You can see an example [here](https://github.com/sendgrid/sendgrid-ruby/blob/master/examples/helpers/mail/example.rb) and down below:

```
require 'sendgrid-ruby'
include SendGrid
require 'json'

def testing_cc
  mail = SendGrid::Mail.new
  mail.from = Email.new(email: 'test@example.com')
  mail.subject = 'Hello World from the SendGrid Ruby Library'
  personalization = Personalization.new
  personalization.add_to(Email.new(email: 'test1@example.com', name: 'Example User'))
  personalization.add_cc(Email.new(email: 'test3@example.com', name: 'Example User'))
  mail.add_personalization(personalization)


  mail.add_content(Content.new(type: 'text/plain', value: 'some text here'))
  mail.add_content(Content.new(type: 'text/html', value: '<html><body>some text here</body></html>'))

  mail.reply_to = Email.new(email: 'test@example.com')

  # puts JSON.pretty_generate(mail.to_json)
  puts mail.to_json

  sg = SendGrid::API.new(api_key: ENV['SENDGRID_API_KEY'], host: 'https://api.sendgrid.com')
  response = sg.client.mail._('send').post(request_body: mail.to_json)
  puts response.status_code
  puts response.body
  puts response.headers
end


testing_cc
```

**Comment by andrew-koster-** [comment]
It's **_REALLY WEIRD_** that I have to:

- Create this whole Personalizations object, call a bunch of methods on it, and add it back into the Mail object.
- Specify the `to` address in the `to` parameter of `Mail.new` **and** in the `add_to` method of the Personalizations object.
- Write a bunch of wrapper code with type checks and such, in order to keep this boilerplate junk out of my business logic.

All just to perform the extremely common operation of sending an email to more than one address.
