### ISSUE TITLE
Create Dynamic Template using gem [only creates legacy]

### ISSUE THREAD

**Issue by sergio-rivas** [sendgrid/sendgrid-ruby#376]
#### Issue Summary

Whenever I follow the steps in sendgrid/USAGE.md for creating a template, it only creates a Legacy Template. However, I want to make use of Sendgrid's Dynamic Template features for personalization. After I follow the steps below, if I retrieve the template using the ruby gem, I retrieve a template with "generation": "legacy" . Thus, if I try to follow the use-case for sending dynamic template emails, it fails with an error saying that I cannot send dynamic template data with a legacy template.

#### Steps to Reproduce

```
data = {"name"=>"some_template_name"}
sg = SendGrid::API.new(api_key: ENV[:sendgrid_apikey])
response = sg.client.templates.post(request_body: data)
puts response.status_code
puts response.body
puts response.headers
```

What I expected:
((Follow Usage Instructions template creation)) --> Create Dynamic Template

#### Technical details:

* sendgrid-ruby Version: 5.3.0
* Ruby Version: 2.5.1

**Comment by thinkingserious** [comment]
Hello @sergio-rivas,

Could you please try the example [here](https://github.com/sendgrid/sendgrid-ruby/blob/master/USE_CASES.md#transactional-templates)? Thank you!

With Best Regards,

Elmer

**Comment by sergio-rivas** [comment]
Hey Elmer,

Thanks so much for your response. However, that is not an example of **creating** a dynamic template. It is an exmaple of using a currently existing template. There is currently no documentation of _creating_ a dynamic template in the documentation.

**Comment by thinkingserious** [comment]
Hello @sergio-rivasl

I hope [this](https://sendgrid.com/docs/glossary/transactional-email-templates/) is the documentation you need.

With Best Regards,

Elmer

**Comment by sergio-rivas** [comment]
Unfortunately, that still doesn't address the question of how to create the email template using the gem. 

Our usecase is that we would like to make a WYSIWYG form for our client's admin dashboard where he/she can write templates/edit them. Then when users do xyz action, xyz email is sent using the dynamically created templates.  

The link you sent me seems to suggest we should have users directly log in to the Sendgrid side and use the Sendgrid UI, which defeats the purpose of having all their tools in one place.

**Comment by thinkingserious** [comment]
Ah, thanks for clarifying the use case @sergio-rivas,

I do not believe we can create dynamic templates via API. I will double check with the team.

With Best Regards,

Elmer

**Comment by sagar-balapure** [comment]
Any update on creating dynamic templates via ruby/python. I tried creating template but unfortunately it always creates legacy template.

**Comment by sagar-balapure** [comment]
After referring API [doc ](https://sendgrid.api-docs.io/v3.0/transactional-templates) i got the solution.
There is param in request body called _"generation":"legacy/dynamic"_. by default value is "legacy". pass the value as "dynamic". this will create dynamic template of sendgrid.
So the request body looks like - 
```
data = {"name"=>"some_template_name","generation":"dynamic"}
sg = SendGrid::API.new(api_key: ENV[:sendgrid_apikey])
response = sg.client.templates.post(request_body: data)
puts response.status_code
puts response.body
puts response.headers
```


Hope this will help.

**Comment by childish-sambino** [comment]
Awesome! Thanks for following up @sagar-balapure!

Gonna consider this resolved.
