### ISSUE TITLE
Transactional email scheduling - send_at is ignored

### ISSUE THREAD

**Issue by AndreiDev** [sendgrid/sendgrid-ruby#377]
#### Issue Summary

Sending a transactional email based on a template with a `send_at` parameter ignores the `send_at`.
Using the example with the `send_at` parameter, but the email is sent right away.
```
require 'sendgrid-ruby'
include SendGrid

data = JSON.parse('{
  "personalizations": [
    {
      "to": [
        {
          "email": "test@example.com"
        }
      ],
      **"send_at": 1546089840,**
      "dynamic_template_data": {
        "subject": "Testing Templates",
	"name": "Example User",
        "city": "Denver"
      }
    }
  ],
  "from": {
    "email": "test@example.com"
  },
  "template_id": "d-2c214ac919e84170b21855cc129b4a5f"
}')
sg = SendGrid::API.new(api_key: ENV['SENDGRID_API_KEY'])
begin
    response = sg.client.mail._("send").post(request_body: data)
rescue Exception => e
    puts e.message
end
puts response.status_code
puts response.body
puts response.parsed_body
puts response.headers
```

Tried to add the `"send_at": 1546089840,` at the `template_id` level without any success - the email is sent right away.

Is email scheduling supported?

**Comment by thinkingserious** [comment]
Hello @AndreiDev,

Yes, email scheduling is supported. Could you please provide your [request body](https://github.com/sendgrid/sendgrid-ruby/blob/master/TROUBLESHOOTING.md#request-body)?

Thanks!

With Best Regards,

Elmer

**Comment by AndreiDev** [comment]
Hi @thinkingserious 

I'm not sure I understand what you mean.
The request body is the `data` variable.
```
data = JSON.parse('{
  "personalizations": [
    {
      "to": [
        {
          "email": "test@example.com"
        }
      ],
      **"send_at": 1546089840,**
      "dynamic_template_data": {
        "subject": "Testing Templates",
	"name": "Example User",
        "city": "Denver"
      }
    }
  ],
  "from": {
    "email": "test@example.com"
  },
  "template_id": "d-2c214ac919e84170b21855cc129b4a5f"
}')
```

Maybe you can give an example of a transactional email being scheduled using `send_at`?

Thanks,
Andrei.

**Comment by thinkingserious** [comment]
Hello @AndreiDev,

Are you scheduling more than 72 hours in advance? That is not supported.

With Best Regards,

Elmer

**Comment by ajfick** [comment]
I just ran into this issue as well. Is there a solution? Any email that I attempt to schedule using `send_at` seems to send immediately. Also, I don't see any mention of timezone in the documentation, is this intended to be in UTC?

**Comment by JefferyHus** [comment]
@ajfick sendGrid uses your profile timezone to execute all your scheduled requests. There is not a parameter to help you specify a timezone.

**Comment by childish-sambino** [comment]
More discussion here: https://github.com/sendgrid/sendgrid-nodejs/issues/1038

Generally speaking, when providing a unix timestamp it is time since UTC epoch.
