### ISSUE TITLE
cc and bcc is not working

### ISSUE THREAD

**Issue by aelor** [sendgrid/sendgrid-ruby#38]
I am trying to send emails using template api

````
client = SendGrid::Client.new(api_user: ENV['SENDGRID_USERNAME'], api_key: ENV['SENDGRID_PASSWORD'])
@user_emails = ['abc@abc.com', 'abc2@abc.com']

@header = Smtpapi::Header.new
@header.add_to(@user_emails)
@header.add_filter('templates', 'enable', 1)    # necessary for each time the template engine is used
@header.add_filter('templates', 'template_id', template_id)
mail = SendGrid::Mail.new do |m|
      m.to = @user_emails
      m.from = from
      m.from_name = fromname
      m.bcc = bcc
      m.subject = ' '
      m.smtpapi = @header
      m.html = '<img alt="" height="1" src="" style="display:none;" width="1" />'
    end
client.send(mail)
````
The to is working fine , but bcc is not working . Is it some kind of bug

**Comment by matt-hu** [comment]
I'm pretty sure it works now, I think it's not an issue anymore.

**Comment by aelor** [comment]
Its still not working @matt-hu . We ran a test just now.

**Comment by davidsavoya** [comment]
We have not been able to get this to work either @matt-hu . Both cc and bcc. We have tried switching on the bcc flag in our account settings as well and it doesn't seem to be the issue.

**Comment by davidsavoya** [comment]
@thinkingserious please see above.

**Comment by thinkingserious** [comment]
@aelor, @davidsavoya,

Are you using the new library? https://github.com/sendgrid/sendgrid-ruby/tree/v3beta

In either case, could you provide me with the code (credentials and sensitive data redacted)?

Thanks!

**Comment by davidsavoya** [comment]
No I am on version 1.1.6. 

```
def build_email(recipients, header_builder, files = {})
      attachments = files.map do |key, value|
        {name: key, file: value}
      end

      mail = SendGrid::Mail.new do |m|
        m.to = recipients
        m.bcc = "me@example.com"
        m.from = from_address
        m.subject = " "
        m.html = "<body></body>"
        m.attachments = attachments
      end

      mail.smtpapi = header_builder.build_header(recipients)
      mail
    end
```

then call client.send(mail) where ever we are using this. 

Everything else is working as expected.

**Comment by thinkingserious** [comment]
Thank you @davidsavoya,

We will take a look.

Also, could you show us the code for the header_builder?

**Comment by davidsavoya** [comment]
It is just adding our replacements in our email templates. Where we are doing add_substitution calls there and such. Not sure if this helps but here is a stripped down version. 

```class SomeHeaderBuilder
  def build_header(recipients)
    header_factory = HeaderFactory.new(recipients)

    header_factory.add_param(":welcome_message", "hey, how are ya?")

    header_factory.add_template_id(template_id)
    header_factory.header
  end

  private

  def template_id
    "12345"
  end
end
```

```
class HeaderFactory
  attr_reader :header

  def initialize(recipients, header = Smtpapi::Header.new)
    @recipients = recipients
    @header = header

    @header.add_to recipients if @header.to.empty?
  end

  def add_param(key, value)
    header.add_substitution(key, Array.new(@recipients.size, value))
  end

  def add_template_id(template_id)
    header.add_filter("templates", "enable", 1) # necessary for each time the template engine is used
    header.add_filter("templates", "template_id", template_id)
  end
end
```

**Comment by matt-hu** [comment]
my code is :

``` ruby
@mail = SendGrid::Mail.new do |m|
      m.to = @email
      m.from = "<#{ENV['SMTP_DEFAULT_FROM_EMAIL']}>"
      m.subject = (I18n.t 'invite_project_user.welcome_title', project_name: @project_name)
      m.bcc = ENV['BCC_MAIL'].to_s if @info['first']
      m.html = template.result(binding)
end
```

It works for me.

**Comment by matt-hu** [comment]
BTW, I am on v1.1.6, too.
The mail function works fine these days. 
And I can't tell what's wrong with your code, sorry.
I suggest you debug into `SendGrid::Mail.new` when you call it, to see what just happens. @davidsavoya

**Comment by davidsavoya** [comment]
When I build the mail object, I can see that '@bcc' gets built to be the string I want and when I call send on an the sendgrid client, the mail that I call it with has '@bcc' with the string email address I want. 

Is there anything on the response back that would give any clues?

**Comment by davidsavoya** [comment]
Is there anything in my account settings with SendGrid that needs to be adjusted?

**Comment by davidsavoya** [comment]
Playing around with this, I can remove my 'to' assignment from the mail class since I pass my recipients to 
```
 mail.smtpapi = header_builder.build_header(recipients)
```

which is building a Smtpapi::Header. It seems that who I am sending mail to is a result of who I add to the 'to' of the Smtpapi::Header. I don't see a way to add a bcc or cc to this class.

**Comment by davidsavoya** [comment]
Hey guys, I was able to get this working by adding a bcc filter on the header. I appreciate y'all looking into this. 

```
      header.add_filter("templates", "enable", 1) # necessary for each time the template engine is used
      header.add_filter("bcc", "email", "me@example.com")
```

**Comment by davidsavoya** [comment]
Do you think 
```
def smtpapi_json
      if !template.nil? && template.is_a?(Template)
        template.add_to_smtpapi(smtpapi)
      end

      smtpapi.to_json
    end
```
In  SendGrid::Mail could do something similar with the bcc by adding to the smtpapi json? If so, I would be happy to give it a go at home. LMK or feel free to close

**Comment by matt-hu** [comment]
@davidsavoya glad you find the work around.
for your last question, `In SendGrid::Mail could do something similar with the bcc by adding to the smtpapi json?` I digged into this before (just because my project only used stmpapi before and PM got the bcc requirement, OMG ). it seems there is no way to make it right with using stmpapi.

**Comment by thinkingserious** [comment]
Hello @matt-hu,

The new version of this library has come out of beta yesterday. It uses our new v3 /mail/send endpoint, which includes the SMTPAPI functionality without an external dependency.
