### ISSUE TITLE
Encoding for special characters not working in subject

### ISSUE THREAD

**Issue by abdulmunim101** [sendgrid/sendgrid-ruby#380]
#### Issue Summary

I have been using the sendgrid-ruby gem for sending emails. The subject of the email doesn't decode special characters properly.
Eg. Sending this subject for the email `How's it going` translates to this in the actual email `How&apos;s it going` 

#### Steps to Reproduce

  @body_json['personalizations'][0]['dynamic_template_data'] = {
      'email_title': @email_title,
      'content': @description,
      'subject': "How's it going",
      'button_url': @button_link,
      'customer_brand': @company.email_color || '#3F1DCB',
      'button_cta': @email_button,
      'customer_logo': @company.logo,
      'full_name': @user.full_name,
      'user_avatar_url': @user.picture
    }

`SendGrid::API.new(api_key: ENV['SENDGRID_API_KEY']).client.mail._('send').post(request_body: @body_json)`

I construct the json for post request to sendgrid with some code like above. The email goes in perfectly, it just doesn't show the special characters in subject correctly

#### Technical details:

* sendgrid-ruby Version: 4.0.8
* Ruby Version: 2.3.1

**Comment by thinkingserious** [comment]
Hello @abdulmunim101,

If you are using dynamic templates, then in your template, in the UI, you will need to use `{{{ subject }}} ` rather than `{{ subject }}`. Could you please try that?

Thanks!

With Best Regards,

Elmer

**Comment by abdulmunim101** [comment]
Thanks @thinkingserious - I contacted the sendgrid guys and they presented the same solution. Problem is resolved now. 

Thanks for the help.
