### ISSUE TITLE
undefined method `add_attachment` for <Mail::Message:0x00007fe505b13bf8>

### ISSUE THREAD

**Issue by gsum** [sendgrid/sendgrid-ruby#381]
#### Issue Summary

Was using sendgrid-ruby for a project and then was trying to add attachment and fllowed through the documentation but add_attachment method is undefined.
#### Steps to Reproduce

1. make a transactional template
2. sendmail method without mail helper class
3. user add_attachment for pdf

#### Technical details:

* sendgrid-ruby Version: 5.3.0
* Ruby Version: 2.5.3

**Comment by thinkingserious** [comment]
Hello @gsum,

I"m assuming you followed the [example here](https://github.com/sendgrid/sendgrid-ruby/blob/master/USE_CASES.md#adding-attachments). Could you please provide a code sample so that we may try and reproduce?

Thanks!

With Best Regards,

Elmer

**Comment by aqabawe** [comment]
@gsum I ran into the same issue, what I found out is that I need to scope the classes under the `SendGrid` namespace per the example @thinkingserious linked, which wasn't the case in my old code. I was using `Mail.new` instead of `SendGrid::Mail.new`.

**Comment by thinkingserious** [comment]
Thanks for sharing the solution @aqabawe!

Please let me know if this does not solve your issue @gsum.
