### ISSUE TITLE
group tag substitution not working for me

### ISSUE THREAD

**Issue by NikhilThombare-Cuelogic** [sendgrid/sendgrid-ruby#384]
Can someone help me to customize group tag something like inside email template? 

like these emails? `<a href="http://www.xyz.com:3000/email_preferences/unsubscribe?url=<%asm_group_unsubscribe_raw_url%>">Unsubscribe</a>`

**using substitution**
```
mail = SendGrid::Mail.new
mail.from = Email.new(email: 'test@example.com')
mail.subject = 'Hello World from the SendGrid Ruby Library'

personalization = Personalization.new
personalization.add_to(Email.new(email: 'nikhil@gmail.com', name: 'Example User'))

personalization.add_substitution(Substitution.new(key: 'Unsub_All', value: '<%asm_global_unsubscribe_raw_url%>'))

 mail.add_personalization(personalization)
 mail.add_content(Content.new(type: 'text/plain', value: 'some text here'))
 mail.add_content(Content.new(type: 'text/html', value: '<html><body>some text here</body></html>'))

sg = SendGrid::API.new(api_key: 'xyz')
mail.asm = ASM.new(group_id: 123)
mail.template_id = 'd-c4b017feb032402ea732b'

response = sg.client.mail._('send').post(request_body: mail.to_json)
puts response.status_code

```

> error: Substitutions may not be used with dynamic templating

#### Technical details:

* sendgrid-ruby Version: sendgrid-ruby (5.3.0)
* Ruby Version: ruby 2.4.5

**Comment by thinkingserious** [comment]
Hello @NikhilThombare-Cuelogic,

Could you please try using [this example](https://github.com/sendgrid/sendgrid-ruby/blob/master/USE_CASES.md#transactional-templates)?

With Best Regards,

Elmer

**Comment by NikhilThombare-Cuelogic** [comment]
Thanks for the reply 

I already tried this solution but didn't work 

```
mail = SendGrid::Mail.new
mail.template_id = TEMPLATE_ID # a non-legacy template id
mail.from = Email.new(email: 'nikhil@gmail.com')
subject = 'Dynamic Template Data Hello World from the SendGrid Ruby Library'
mail.subject = subject
personalization = Personalization.new
personalization.add_to(Email.new(email: 'nikhil.thombare@cuelogic.com', name: 'Example User'))
personalization.add_dynamic_template_data({
	    url_data: '<%asm_group_unsubscribe_raw_url%>'
	  })
mail.asm = ASM.new(group_id: 123)

mail.add_personalization(personalization)
mail.add_content(Content.new(type: 'text/plain', value: 'some text here'))
mail.add_content(Content.new(type: 'text/html', value: '<html><body>some text here</body></html>'))

api = SendGrid::API.new api_key: API_KEY
response = api.client.mail._('send').post request_body: mail.to_json
puts response.status_code
puts response.body
puts response.headers
```

email template:

  <html>
    <head>
      <title></title>
    </head>
    <body>
      1  
    <h3>{{url_data}}</h3>
    2
    <h1><%asm_group_unsubscribe_raw_url%></h1>
    </body>
</html>


but still not **url_data** treating as string 
o/p - <%asm_group_unsubscribe_raw_url%>

expected:  it should be url http://www.sendgrid.com/......   convert tag to sendgrid url.

**Comment by thinkingserious** [comment]
Hello @NikhilThombare-Cuelogic,

Perhaps [this](https://github.com/sendgrid/sendgrid-ruby/issues/59#issuecomment-417480271) could be the issue.
