### ISSUE TITLE
Does not support the majority of SendGrid v3 API

### ISSUE THREAD

**Issue by swifthand** [sendgrid/sendgrid-ruby#39]
Hello SendGrid friends,

After using SendGrid for a few years as a simple SMTP endpoint with a little bit of analytics baked in, I was excited to finally have the opportunity to dive deep into more advanced features, such as Advanced Suppression Management, Marketing Campaigns, and Threads.

Looking at this library, however, the majority of SendGrid's [Web API v3](https://sendgrid.com/docs/API_Reference/Web_API_v3/index.html) appears to be unsupported:
- Bounces
- Suppression Management
- Marketing Campaigns
- Categories
- Users/Subusers
- Stats

Are there any plans to support any of these through the sendgrid-ruby gem and/or will pull requests be accepted on those items?

My company really likes SendGrid and wish to know where it is best to apply our efforts:

1. Toward our own Ruby implementation of our needed features (particularly Suppression Management, Categories and Bounces).
2. Toward a merge into this project using similar code style and strategies (which might not even be advisable, given details of the v3 API and the current implementation of [`SendGrid::Client`](https://github.com/sendgrid/sendgrid-ruby/blob/master/lib/sendgrid/client.rb)).

**Comment by thinkingserious** [comment]
Hello @swifthand,

We are planning to both implement the Web API v3 endpoints across all our libraries and release an Open Source Standards Guide. The Guide will provide instructions on how to contribute and we will also be releasing a roadmap.

Right now, I suggest you utilize your own Ruby implementation. It will take some time (not too long, but probably too long for your needs) for us to roll out the Guide and commence work on implementing all of the Web API v3 endpoints on this library.

We have begun work implementing the Web API v3 endpoints on our Python, PHP and CSharp libraries, so you can look to those for inspiration and guidance. That said, after getting started with those libraries, we took a step back to create the Guide, utilizing lessons learned with implementing those three libraries and there will be some changes.

Thanks for supporting SendGrid! We look forward to collaborating with you!

Elmer Thomas
Developer Experience Engineer | Product

**Comment by swifthand** [comment]
Will do, thanks for the quick feedback!
