### ISSUE TITLE
How to send image via sendgrid from custom form on wix?

### ISSUE THREAD

**Issue by mrodavis** [sendgrid/sendgrid-ruby#390]
Hi, I am trying to send an image through sendgrid.  The image resides in the custom form created on my wix website.  The image is uploaded to the form via the user.  Does anyone know how to send an image from a form field?

* sendgrid-ruby Version: master (latest commit: [commit number])
* Ruby Version: 2.2

**Comment by thinkingserious** [comment]
Hello @mrodavis,

To send an attachment, [here](https://github.com/sendgrid/sendgrid-ruby/blob/master/USE_CASES.md#adding-attachments) is a code example that may help. 

You should be able to set `fpath` to the path to your image and for the `attachment.type` you would use something similar to `img/png`. [Here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Complete_list_of_MIME_types) is a reference of many mime types.

With best regards,

Elmer

**Comment by mrodavis** [comment]
Thank you so much, I will give it a try!
