### ISSUE TITLE
Error 400 when I try to run my production environment

### ISSUE THREAD

**Issue by dangerrg** [sendgrid/sendgrid-ruby#395]
#### Issue Summary
Hi,

I'm running my Rails 5.1.7 app (Ruby v.2.6.3) with SendGrid(6.0.0)+ Heroku.

I've set up a contact_us form for the Users to send a message (email). Add everything works perfectly well in the development environment with the basic Sendgrid setup. 

But, I'm having this ``error 400`` when I try to run my production environment:

`{"errors":[{"message":"The provided authorization grant is invalid, expired, or revoked","field":null,"help":null}]}
{"server"=>["nginx"], "date"=>["Sat, 16 Nov 2019 13:52:51 GMT"], "content-type"=>["application/json"], "content-length"=>["116"], "connection"=>["close"], "access-control-allow-origin"=>["https://sendgrid.api-docs.io"], "access-control-allow-methods"=>["POST"], "access-control-allow-headers"=>["Authorization, Content-Type, On-behalf-of, x-sg-elas-acl"], "access-control-max-age"=>["600"], "x-no-cors-reason"=>["https://sendgrid.com/docs/Classroom/Basics/API/cors.html"]}`

So, I try creating a new upgraded SENDGRID_API_KEY, but it still not working, I get the same error new error:

`{"errors":[{"message":"Invalid type. Expected: object, given: string.","field":"(root)","help":"http://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/errors.html#-Request-Body-Parameters"}]}
{"server"=>["nginx"], "date"=>["Sat, 16 Nov 2019 14:45:55 GMT"], "content-type"=>["application/json"], "content-length"=>["191"], "connection"=>["close"], "access-control-allow-origin"=>["https://sendgrid.api-docs.io"], "access-control-allow-methods"=>["POST"], "access-control-allow-headers"=>["Authorization, Content-Type, On-behalf-of, x-sg-elas-acl"], "access-control-max-age"=>["600"], "x-no-cors-reason"=>["https://sendgrid.com/docs/Classroom/Basics/API/cors.html"]}`

here is my code:
https://gist.github.com/dangerrg/358f763363cf1b4bd774e8f09ce165ab
```
class MessageMailer < ApplicationMailer
  require "sendgrid-ruby"
  include SendGrid

  def contact(message)
    @message = message

    from = Email.new(email: "no-reply@casineros-cubanos.com")
    to = Email.new(email: @message.email)
    subject = 'casineros cubanos Blog'
    content = Content.new(type: 'text/plain', value: "Hi dear #{@message.name}! Thanks for your massage, we will get back to you soon.")
    mail = SendGrid::Mail.new(from, subject, to, content)

    sg = SendGrid::API.new(api_key: ENV['SENDGRID_API_KEY'])
    begin # to read error messages
        response = sg.client.mail._("send").post(request_body: mail.to_json)
    rescue Exception => e
        puts e.message
    end

    puts response.status_code
    puts response.body
    puts response.headers

   end
end
```
Any help or hint would be appreciated.

Thanks

**Comment by childish-sambino** [comment]
Just tried your sample code and not getting an error and the email is received. Could you post the request body here?

https://github.com/sendgrid/sendgrid-ruby/blob/master/TROUBLESHOOTING.md#viewing-the-request-body

**Comment by dangerrg** [comment]
Hi,

Sorry, my delay I didn't receive your previous message. In my case, this feature still not working properly.

Is the **_body request_** related to the _html.text_ file?

**Comment by childish-sambino** [comment]
No the request body is just `mail.to_json`. Could you log that value and add it here (removing any sensitive bits)?

**Comment by dangerrg** [comment]
Actually,

It seems that I haven't set up any JSON file with body requests. So, I guess that might be my main issue, isn't it?

**Comment by childish-sambino** [comment]
This is the line in your code sample above:
```
response = sg.client.mail._("send").post(request_body: mail.to_json)
```
Are you able to log the value of the last part? `mail.to_json`

**Comment by luk4s** [comment]
Hello, I have same error in my app.
Its caused by double `to_json` "conversion", let me explain:
`SendGrid::Mail#from=` store in `@from` as "json string"
```ruby
    def from
      @from.nil? ? nil : @from.to_json
    end
```
=> then method `to_json` (SendGrid::Mail#to_json) return Hash with "`from => String` =>

request body looks like this:
```ruby
{"from"=>"{\"email\":\"lukas@easy.cz\"}", "subject"=>"subject", "personalizations"=>[{"to"=>["[{\"email\":\"lukas@easy.cz\"}]"]}], "content"=>["\"xxxx xxxx xxxx\""]}
```
As you can see, "from" is not a JSON object, but its a JSON string => Ruby in HTTP request do `.to_json` on this Hash => which "escape" json string so on server Sendgrid it arrives as a string instead on "Hash"....

My workaround:
```ruby
mail = SendGrid::Mail.new
body = mail.to_json
body["from"] = {email: "lukas@easy.cz"} # => Its important to set this as Hash with email, due `ruby_http_client-3.5.0/lib/ruby_http_client.rb:302` do `to_json` itself,
response = sg.client.mail._('send').post(request_body: body)
```

**Comment by childish-sambino** [comment]
@luk4s A Hash is not expected to be the type of `from`. It's expected to be of type `SendGrid:Email` which contains its own `to_json` implementation. The quick-start example demonstrates the proper usage: https://github.com/sendgrid/sendgrid-ruby#with-mail-helper-class
