### ISSUE TITLE
Method #send

### ISSUE THREAD

**Issue by muichkine** [sendgrid/sendgrid-ruby#40]
Hello guys,

 Overriding the `:send` method in ruby is a very bad idea. It can lead to very strange behaviors and stop anyone from pushing a bit the enveloppe by meta-programming `SendGrid::Client` objects or using them in any other way than a plain `client.send`.

And there are use to doing these stuffs :)

No big deal given the simplicity ofthe gem. But I think it's definitely worth pointing out.

Cheers.

**Comment by diazruy** [comment]
This just caused me a bit of confusion as I was working on https://github.com/sendgrid/sendgrid-ruby/pull/50 and trying to use `client.send` in order to DRY up the tests. Finally figured out a way to work around it, but it is bound to cause issues most likely.

**Comment by thinkingserious** [comment]
@muichkine,

Thanks for the feedback!

This is no longer an issue in the new version of our library, which will replace this one in a few weeks. You can check it out here: https://github.com/sendgrid/sendgrid-ruby/tree/v3beta

With Best Regards,

Elmer
