### ISSUE TITLE
Template caches recipient list

### ISSUE THREAD

**Issue by cyclotron3k** [sendgrid/sendgrid-ruby#41]
This did not do what I expected it to do, and caused a lot of trouble:

```
client    = SendGrid::Client.new(api_key: 'SG.abcdefg-AB.L0r3m1p5unaaaaaa')
template  = SendGrid::Template.new('88888888-8888-4000-8000-888888888888')

users.each do |user|

	recipient = SendGrid::Recipient.new user.email

	mailer = SendGrid::TemplateMailer.new(client, template, [recipient])

	mailer.mail({
		from:    "contact@company.com",
		subject: "Confidential information about your account",
		html:    "<h1>Some info</h1> ..."
	})

end
```

Spoiler alert: You'll end up sending A's email to A, B's email to B and A, C's email to C, B & A, etc, etc.

TemplateMailer adds `recipient` to a recipient list that is cached in `template`, and it is never cleared out. Recipients keep getting added to the recipient list stored in `template`.

Perhaps this is by design, but I think it is a counter-intuitive and dangerous design.

**Comment by thinkingserious** [comment]
Hello @cyclotron3k,

Thanks for reporting this issue to us!

I'm not sure if this is still a problem in our new library, which replaces this one in a few weeks, so I'll keep this issue open until I get a chance to check it out.

You can check out the new library here: https://github.com/sendgrid/sendgrid-ruby/tree/v3beta

Thanks for your support!

With Best Regards,

Elmer
