### ISSUE TITLE
Allow ruby_http_client 3.5.0 in version range

### ISSUE THREAD

**Issue by mkilling** [sendgrid/sendgrid-ruby#411]
### Issue Summary
sendgrid-ruby 6.1.0 caused this issue https://github.com/sendgrid/ruby-http-client/issues/117 to appear in our production environment. ruby-http-client has recently fixed the issue in version 3.5.0, but the current sendgrid-ruby release 6.1.1 (released at about the same time) still only allows for ruby-http-client ~> 3.4.0.

### Steps to Reproduce
1. Install sendgrid-ruby 6.1.1
2. Post an array to the Sendgrid API (see code snippet
3. Exception: `undefined method bytesize' for #Array:0x00007f11061d84e0` (see https://github.com/sendgrid/ruby-http-client/issues/117)

### Code Snippet
```ruby
SendGrid::API.new(api_key: API_KEY).client.contactdb.recipients.post(request_body: [])
```

### Exception/Log
```
undefined method bytesize' for #Array:0x00007f11061d84e0
```

### Technical details:
* sendgrid-ruby version: 6.1.1
* ruby version: 2.5.3

**Comment by childish-sambino** [comment]
Yup, looks like an issue with the version constraint. We should be allowing minor version bumps. Working on PR to address this.
