### ISSUE TITLE
i am getting the same issue in python when i am trying to add both plain text and html contents at the same time it is taking by default as html .

### ISSUE THREAD

**Issue by krishnakekan** [sendgrid/sendgrid-ruby#422]
### Issue Summary
A summary of the issue and the environment in which it occurs. If suitable, include the steps required to reproduce the bug. Please feel free to include screenshots, screencasts, or code examples.

### Steps to Reproduce
1. This is the first step
2. This is the second step
3. Further steps, etc.

### Code Snippet
```ruby
# paste code here
```

### Exception/Log
```
# paste exception/log here
```

### Technical details:
* sendgrid-ruby version:
* ruby version:

**Comment by krishnakekan** [comment]
I am using sendgrid latest with python 3.7

**Comment by childish-sambino** [comment]
The plain text content should be a plain version of the HTML content. It should not appear in conjunction with the HTML content.
