### ISSUE TITLE
Add support for Non-X-SMTPAPI Headers

### ISSUE THREAD

**Issue by jrpolidario** [sendgrid/sendgrid-ruby#43]
From [API docs](https://sendgrid.com/docs/API_Reference/Web_API/mail.html), there is support for `headers`.

My scenario required me to have both X-SMTPAPI's unique_args header, and Non-X-SMTPAPI custom header.

I could not find any way to add Non-X-SMTPAPI headers from either README.md nor from the [source code](https://github.com/sendgrid/sendgrid-ruby/blob/master/lib/sendgrid/mail.rb), because there is no `attr_accessor :headers`

From what I understand, this will entail merging both `Sendgrid::Mail` `@smtpapi` and `@headers` in the source code.

**Comment by thinkingserious** [comment]
Hello @jrpolidario,

This is no longer an issue in the new version of this library, which comes out of beta in a few weeks. You can check it out here: https://github.com/sendgrid/sendgrid-ruby/tree/v3beta

The new version uses the v3 /mail/send endpoint: https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html which includes the X-SMTPAPI settings and the new library supports the addition of your own custom headings.

Thanks for your support!

With Best Regards,

Elmer
