### ISSUE TITLE
Error in using the Mail Helper Class in sending mail

### ISSUE THREAD

**Issue by utkarsh1996** [sendgrid/sendgrid-ruby#438]
With the example of Mail Helper Class, I implemented in code and got this particular error

400
{"errors":[{"message":"The from object must be provided for every email send. It is an object that requires the email parameter, but may also contain a name parameter.  e.g. {\"email\" : \"example@example.com\"}  or {\"email\" : \"example@example.com\", \"name\" : \"Example Recipient\"}.","field":"from.email","help":"http://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/errors.html#message.from"},{"message":"The personalizations field is required and must have at least one personalization.","field":"personalizations","help":"http://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/errors.html#-Personalizations-Errors"},{"message":"Unless a valid template_id is provided, the content parameter is required. There must be at least one defined content block. We typically suggest both text/plain and text/html blocks are included, but only one block is required.","field":"content","help":"http://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/errors.html#message.content"}]}
{"server"=>["nginx"], "date"=>["Thu, 24 Sep 2020 05:12:50 GMT"], "content-type"=>["application/json"], "content-length"=>["980"], "connection"=>["close"], "access-control-allow-origin"=>["https://sendgrid.api-docs.io"], "access-control-allow-methods"=>["POST"], "access-control-allow-headers"=>["Authorization, Content-Type, On-behalf-of, x-sg-elas-acl"], "access-control-max-age"=>["600"], "x-no-cors-reason"=>["https://sendgrid.com/docs/Classroom/Basics/API/cors.html"]}

Even though I gave all the required info like from, to, content.

My code:
from = Email.new(email: 'testmail@gmail.com')
      to = Email.new(email: 'totestmail@gmail.com')
      subject = 'Sending with SendGrid is Fun'
      content = Content.new(type: 'text/plain', value: 'and easy to do anywhere, even with Ruby')
      mail = Mail.new(from, subject, to, content)
      sg = SendGrid::API.new(api_key: 'my API key')
      response = sg.client.mail._('send').post(request_body: mail.to_json) //giving error on this line
      puts response.status_code
      puts response.body
      puts response.headers

**Comment by futura** [comment]
I got the same result. Was this ever resolved?

**Comment by tom-spalding** [comment]
Hi, I can reproduce this as well.

Test script:

```ruby
#!/usr/bin/env ruby

# using SendGrid's Ruby Library
# https://github.com/sendgrid/sendgrid-ruby
require 'sendgrid-ruby'
include SendGrid

# https://www.twilio.com/docs/sendgrid/api-reference/mail-send/errors#from-address-errors
from = Email.new(email: 'support@workemail.com', name: "Work Support")
to = Email.new(email: 'me@gmail.com', name: "Me")
subject = 'Hello, you were sent a new message'
content = Content.new(type: 'text/plain', value: 'Log in to your account to view the message')
mail = Mail.new(from, subject, to, content)

sg = SendGrid::API.new(api_key: ENV['SENDGRID_API_KEY'])

puts "\nDEBUG JSONIFIED REQUEST\n"
puts mail.to_json

response = sg.client.mail._('send').post(request_body: mail.to_json)

puts "\nSTATUS\n"
puts response.status_code

puts "\nBODY\n"
puts response.body

puts "\nHEADERS\n"
puts response.headers
```

Debug Output:
```
DEBUG JSONIFIED REQUEST
{"body":{"boundary":null,"preamble":null,"epilogue":null,"charset":"US-ASCII","part_sort_order":["text/plain","text/enriched","text/html","multipart/alternative"],"parts":[],"raw_source":"","ascii_only":true,"encoding":"7bit"},"body_raw":null,"separate_parts":false,"text_part":null,"html_part":null,"errors":null,"header":[{"name":"#\u003cSendGrid","unparsed_value":":Email:0x00007f098795b7c0\u003e","charset":"UTF-8","field":{"errors":[],"name":"#\u003cSendGrid","element":null,"value":":Email:0x00007f098795b7c0\u003e","charset":"UTF-8"}}],"charset":"UTF-8","defaulted_charset":true,"smtp_envelope_from":null,"smtp_envelope_to":null,"perform_deliveries":true,"raise_delivery_errors":true,"delivery_handler":null,"delivery_method":{"settings":{"address":"localhost","port":25,"domain":"localhost.localdomain","user_name":null,"password":null,"authentication":null,"enable_starttls":null,"enable_starttls_auto":true,"openssl_verify_mode":null,"ssl":null,"tls":null,"open_timeout":5,"read_timeout":5}},"transport_encoding":"Mail::Encodings::SevenBit","mark_for_delete":false,"raw_source":"#\u003cSendGrid::Email:0x00007f098795b7c0\u003e"}

STATUS
400

BODY
{"errors":[{"message":"The from object must be provided for every email send. It is an object that requires the email parameter, but may also contain a name parameter.  e.g. {\"email\" : \"example@example.com\"}  or {\"email\" : \"example@example.com\", \"name\" : \"Example Recipient\"}.","field":"from.email","help":"http://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/errors.html#message.from"},{"message":"The personalizations field is required and must have at least one personalization.","field":"personalizations","help":"http://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/errors.html#-Personalizations-Errors"},{"message":"Unless a valid template_id is provided, the content parameter is required. There must be at least one defined content block. We typically suggest both text/plain and text/html blocks are included, but only one block is required.","field":"content","help":"http://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/errors.html#message.content"}]}

HEADERS
{"server" => ["nginx"], "date" => ["Thu, 27 Mar 2025 04:54:29 GMT"], "content-type" => ["application/json"], "content-length" => ["980"], "connection" => ["close"], "access-control-allow-origin" => ["https://sendgrid.api-docs.io"], "access-control-allow-methods" => ["POST"], "access-control-allow-headers" => ["Authorization, Content-Type, On-behalf-of, x-sg-elas-acl"], "access-control-max-age" => ["600"], "x-no-cors-reason" => ["https://sendgrid.com/docs/Classroom/Basics/API/cors.html"], "strict-transport-security" => ["max-age=31536000; includeSubDomains"], "content-security-policy" => ["frame-ancestors 'none'"], "cache-control" => ["no-cache"], "x-content-type-options" => ["no-sniff"], "referrer-policy" => ["strict-origin-when-cross-origin"]}
```

Something in the example code is bugged. If we change this to be written in JSON, I can get an email to succeed.

Workaround from example code:

```ruby
data = JSON.parse('{
  "personalizations": [
    {
      "to": [
        {
          "email": "me@duck.com"
        }
      ],
      "subject": "Sending with Twilio SendGrid is Fun"
    }
  ],
  "from": {
    "email": "support@workemail.com"
  },
  "content": [
    {
      "type": "text/plain",
      "value": "and easy to do anywhere, even with Ruby"
    }
  ]
}')
sg = SendGrid::API.new(api_key: ENV['SENDGRID_API_KEY'])
response = sg.client.mail._("send").post(request_body: data)
```

**Comment by tom-spalding** [comment]
Update: It looks like there was a simple issue in the recommended sample code. I've updated the docs in this PR to include the namespaced fixes https://github.com/sendgrid/sendgrid-ruby/pull/505.
