### ISSUE TITLE
Does this SDK supports email address validation?

### ISSUE THREAD

**Issue by emanuelhfarias** [sendgrid/sendgrid-ruby#442]
I'm a bit confused, there are two API docs for Sendgrid V3: [one](https://sendgrid.com/docs/API_Reference/Web_API_v3/index.html
) and [two](https://sendgrid.api-docs.io/v3.0)

What is the difference? I see in the README that this project follows [one](https://sendgrid.com/docs/API_Reference/Web_API_v3/index.html
), but this API does't have **Email Address Validation** feature from Pro Plan and docs [two](https://sendgrid.api-docs.io/v3.0/email-address-validation/validate-an-email) has.

I've looked for this feature in ruby SDK but didn't find, so I end up implementing the ugly way:
```ruby
require 'uri'
require 'net/http'

url = URI("https://api.sendgrid.com/v3/validations/email")

http = Net::HTTP.new(url.host, url.port)
http.use_ssl = true
http.verify_mode = OpenSSL::SSL::VERIFY_NONE

request = Net::HTTP::Post.new(url)
request["authorization"] = 'Bearer <<YOUR_API_KEY_HERE>>'
request["content-type"] = 'application/json'
request.body = "{\"email\":\"john.doe@gmial.com\",\"source\":\"signup\"}"

response = http.request(request)
```
Is there any plans to support this? or at least some guide so I can integrate this feature in this SDK

Thanks

**Comment by childish-sambino** [comment]
[Two](https://sendgrid.api-docs.io/v3.0) is the one you should use. The other should be removed at some point.

You can simplify things a bit using this library:
```
data = "{\"email\":\"john.doe@gmial.com\",\"source\":\"signup\"}"
sg = SendGrid::API.new(api_key: ENV['SENDGRID_API_KEY'])
response = sg.client._("validations/email").post(request_body: data)
```

**Comment by emanuelhfarias** [comment]
@childish-sambino wow, thanks.
I think this solves my problem. I'm closing this issue.
