### ISSUE TITLE
How do I send an email to a list of users?

### ISSUE THREAD

**Issue by DmitryBarskov** [sendgrid/sendgrid-ruby#444]
If I have some category or some list of users in SendGrid, how do I send an email to this category/list without listing all their emails in API request? Is it possible?

In UI I create a single send and choose a list, I can see total recipients count.

**Comment by childish-sambino** [comment]
You can use the Single Send API: https://sendgrid.com/docs/for-developers/sending-email/single-sends-2020-update/
