### ISSUE TITLE
Request: Make it possible to pass http_options config when initialize API

### ISSUE THREAD

**Issue by hoangtuanictvn** [sendgrid/sendgrid-ruby#449]
### Feature Request:
The http_options can pass to the SendGrid::Client when initialize. However, I can't give it as a param when initializing the new SendGrid::API at this time. So I hope that it is possible to add http_options to the initialize method of SendGrid::API as below.

```
client = SendGrid::API.new(api_key: api_key, http_options: {open_timeout: 30, read_timeout: 30})
```

**Comment by JenniferMah** [comment]
This issue has been added to our internal backlog to be prioritized. Pull requests and +1s on the issue summary will help it move up the backlog.
