### ISSUE TITLE
Subuser support

### ISSUE THREAD

**Issue by jeffblake** [sendgrid/sendgrid-ruby#45]
Hi,

I need to be able send email through a subuser/account. I don't see that support documented or in the source code.

**Comment by amitsaxena** [comment]
@jeffblake were you able to do this using the root API key and `impersonate_user`? It doesn't look like we can do this unless we use an API key for the subuser. This API does not seem to support `impersonate_user` either:
https://sendgrid.api-docs.io/v3.0/mail-send/v3-mail-send
