### ISSUE TITLE
Is sendgrid-ruby still ruby 2.2. compatible?

### ISSUE THREAD

**Issue by platphorm** [sendgrid/sendgrid-ruby#452]
https://github.com/sendgrid/sendgrid-ruby/blob/865a2accaa11aa990e188fc4f018be619590b52c/lib/sendgrid/helpers/mail/personalization.rb#L79

The gem has a single, recently introduced, safe navigation operator that breaks ruby 2.2.

**Comment by thinkingserious** [comment]
Hello @platphorm,

The lowest version of ruby we support today is 2.4.

With best regards,

Elmer

**Comment by platphorm** [comment]
Good to know, thanks @thinkingserious 
The gemspec does have:
`  spec.required_ruby_version = '>= 2.2'
`
