### ISSUE TITLE
Support add attachment into SendGrid::TemplateMailer

### ISSUE THREAD

**Issue by gurgelrenan** [sendgrid/sendgrid-ruby#46]
Hello guys. 

Currently I can add a attachment into a `Mail` object like well described in **Attachments** section:
```mail.add_attachment('/tmp/report.pdf', 'july_report.pdf')```
Nice, I understand! My question is about this same approach but **working with templates**.

As described in section **Working with Templates** there is `SendGrid::Recipient` Class that supports `add_substitution` method, but is there a way to pass a `attachment` to a `SendGridRecipient` object? This feature could be a good ideia to a pull request?

I hope you understand my question and I really appreciate if you can help me with this.

**Comment by thinkingserious** [comment]
Hello @gurgelrenan,

With the v2 version of our /mail/send endpoint, the attachments are sent per email: https://sendgrid.com/docs/API_Reference/Web_API/mail.html, in v3: https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html attachments can be included with a group of personalizations.

To better understand what you are trying to do, could you please provide a code snippet with the desired functionality?

Thanks!

Elmer

**Comment by gurgelrenan** [comment]
Version 3 will solve my problem! Thanks!
