### ISSUE TITLE
SendGrid::DuplicatePersonalizationError

### ISSUE THREAD

**Issue by netwire88** [sendgrid/sendgrid-ruby#461]
Hi, I'm using the latest build and having issues with 2 related scenarios, see https://github.com/sendgrid/sendgrid-ruby/issues/445#issuecomment-785196150:

1. upper vs. lower case - if I have `test1@example.com` and `TEST1@EXAMPLE.COM` in 1 field, i.e. `to`, `cc`, `bcc`, then the error is raised
2. to/cc/bcc fields - if I have `test1@example.com` in `to` field and `cc` field, then it doesn't work. Similarly with `to` and `bcc`, and `cc` & `bcc`

**Comment by thinkingserious** [comment]
Hello @netwire88,

[This error is raised](https://github.com/sendgrid/sendgrid-ruby/blob/37c0b756f1def40073e442165f3fbde08b054752/lib/sendgrid/helpers/mail/personalization.rb#L75) whenever you have a duplicate email across `to`, `cc` or `bcc`. Please make sure that you have no duplicates across `to`, `cc` or `bcc` and note that duplication check is not case sensitive. 

With best regards,

Elmer
