### ISSUE TITLE
Bad username / password

### ISSUE THREAD

**Issue by rohandey** [sendgrid/sendgrid-ruby#464]
### Issue Summary
Using this old sendgrid-ruby version for a legacy app, suddenly it started to throw error 
SendGrid::Exception: {"errors":["Bad username / password"],"message":"error"}

Is there any change to how api calls are made or we need to make some changes for this work again.

### Code Snippet
```ruby
sendgrid = SendGrid::Client.new do |c|
  c.api_user = 'apikey'
  c.api_key = 'SG.****************migc'
end

email = SendGrid::Mail.new do |m|
  m.to      = "to@example.com"
  m.from    = "you@youremail.com"
  m.subject = "Test Send"
  m.html    = "Go"
end

sendgrid.send(email)
```

### Exception/Log
```
SendGrid::Exception: {"errors":["Bad username / password"],"message":"error"}
```

### Technical details:
* sendgrid-ruby version: (0.0.3)
* ruby version: 2.3.3

Urgent help required.

Thank You

**Comment by thinkingserious** [comment]
Hello @rohandey,

Yes, the [method of authentication](https://sendgrid.com/docs/for-developers/sending-email/upgrade-your-authentication-method-to-api-keys) has changed.

My recommendation is to update to the latest version of this library, then your code would look something like this:

```ruby
require 'sendgrid-ruby'
include SendGrid

from = SendGrid::Email.new(email: 'test@example.com')
to = SendGrid::Email.new(email: 'test@example.com')
subject = 'Sending with Twilio SendGrid is Fun'
content = SendGrid::Content.new(type: 'text/plain', value: 'and easy to do anywhere, even with Ruby')
mail = SendGrid::Mail.new(from, subject, to, content)

sg = SendGrid::API.new(api_key: ENV['SENDGRID_API_KEY'])
response = sg.client.mail._('send').post(request_body: mail.to_json)
```

With best regards,

Elmer

**Comment by rohandey** [comment]
Hi @thinkingserious 
Thank you, this worked. What is the best way to sets  headers under this
SendGrid::Mail.new(from, subject, to, content)

Thanks
Rohan

**Comment by rohandey** [comment]
Hi @thinkingserious 

To be more clear I am not able to do add_tos to message. Previously we were sending news letters by appending array of emails like this
header = Smtpapi::Header.new
header.set_tos(email_arr)

What would be the new way with the current api? 

Thanks
Rohan

**Comment by thinkingserious** [comment]
Ah, you may need a more flexible approach. Please see [this full example](https://github.com/sendgrid/sendgrid-ruby/blob/fb998ee8a4f59991c15096bc682d9caba580b792/examples/helpers/mail/example.rb#L21). Or, [this example](https://github.com/sendgrid/sendgrid-ruby/blob/fb998ee8a4f59991c15096bc682d9caba580b792/use-cases/transactional-templates.md#with-mail-helper-class), if you would like to use dynamic templates.

**Comment by rohandey** [comment]
Thank You @thinkingserious  ... It worked :)
