### ISSUE TITLE
Dynamic Templates overwritting list styles

### ISSUE THREAD

**Issue by ramonpm** [sendgrid/sendgrid-ruby#469]
### Issue Summary
We're using the Dynamic Templates features. Customers use our Rich HTML tool for creating the content how they want to look like, and when it's related to Lists, Sendgrid's internals are exporting the below which overwrites the styles from our tool. 

```
ul ul ul ul  {

      list-style-type: disc !important;

    }

    ol ol {

      list-style-type: lower-roman !important;

    }

    ol ol ol {

      list-style-type: lower-latin !important;

    }

    ol ol ol ol {

      list-style-type: decimal !important;

    }

```

Is there a way to stop that?

I've asked the same thing on Sendgrid Support page, but the agent said he's not aware of a way to do what I wanted and encouraged me to post a new issue here.

### Steps to Reproduce
1. Create a Dynamic template
2. Send a json with HTML with ordered lists on it with multiple levels
3. notice the email you receive the list will be formatted by those overwritten styles, whereas we expected to have the default styles from our Rich HTML tool.

### Code Snippet
n/a

### Exception/Log
n/A

### Technical details:
n/a

**Comment by JenniferMah** [comment]
Hi @ramonpm 
Could you reply with the code that you are currently using to send json with HTML ordered lists and which version of Sendgrid-ruby you are using?

**Comment by eshanholtz** [comment]
Closing this issue due to lack of response. If you'd like further help, please reopen the issue with the information requested.
