### ISSUE TITLE
The link to be notified of releases and breaking changes is returning a 500 from Heroku

### ISSUE THREAD

**Issue by nickhammond** [sendgrid/sendgrid-ruby#475]
The link to be notified of releases and breaking changes is returning a 500 from Heroku.

https://github.com/sendgrid/sendgrid-ruby
![image](https://user-images.githubusercontent.com/17698/145439543-99452331-348f-43bf-8a80-de3fe3030fa0.png)

https://dx.sendgrid.com/newsletter/ruby
![image](https://user-images.githubusercontent.com/17698/145439600-4d4cd168-daa3-424d-93a3-a889e4e572b4.png)

**Comment by shwetha-manvinkurke** [comment]
@nickhammond we don't support the newsletters anymore. The link has now been removed.
