### ISSUE TITLE
Send generated file as attachment

### ISSUE THREAD

**Issue by juggy** [sendgrid/sendgrid-ruby#48]
It seems the add_attachment method only works with files. What about generated attachments that live in memory? How can I send those?

**Comment by gurgelrenan** [comment]
@juggy Do you think that this issue is related to #46 ?

**Comment by thinkingserious** [comment]
Hello @juggy,

Could you give me an example code snippet? I'll give a try.

Note that this library will be replaced in a few weeks with this one: https://github.com/sendgrid/sendgrid-ruby/tree/v3beta. It supports our v3 /mail/send endpoint which handles attachments differently: https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html

Thanks!

Elmer
