### ISSUE TITLE
reply_to has no effect

### ISSUE THREAD

**Issue by coderdave** [sendgrid/sendgrid-ruby#52]
I'm setting the `reply_to` but when you click to reply to the email, it's replying to the `to` email. Am I doing something wrong?

**Comment by thinkingserious** [comment]
Hello @coderdave,

Could you please provide us with a code snippet so we can try to reproduce?

Also, this library will be replaced by the new version in a few weeks, you can check it out here: https://github.com/sendgrid/sendgrid-ruby/tree/v3beta

With Best Regards,

Elmer

**Comment by coderdave** [comment]
I'm just setting up a basic hash. I would like to send from info@mycutsapp.com but let them "reply_to" a different address, but it doesn't work. (Also the from_name isn't work either)

```ruby  
def send_it
  # send from info@mycutsapp.com if it's coming from a yahoo.com account :(
  from = self.from.include?("@yahoo.com") ? "info@mycutsapp.com" : self.from
  email = {
    from: from,
    from_name: self.from_name, # sendgrid isn't using the name set here, it uses the from email address
    reply_to: self.from, # no affect
    to: self.to.split(",").uniq,
    bcc: self.bcc.present? ? self.bcc.split(",").uniq : nil,
    subject: self.subject,
    text: strip_tags(self.message),
    html: self.message
  }

  MailerJob.new.async.perform("SendgridMailer", nil, email)
end
```

**Comment by thinkingserious** [comment]
Hello @coderdave,

Thanks for the additional information.

Where are you setting up the SendGrid::Mail object? In the MailerJob? If so, can I take a look at that code?

Thanks!

Elmer

**Comment by coderdave** [comment]
```ruby
  sendgrid = SendGrid::Client.new do |c|
    c.api_key = ENV["SENDGRID_APIKEY"]
  end
  email = arg
  sendgrid.send email
```

**Comment by thinkingserious** [comment]
`email` needs to be a SendGrid::Mail object. Please see: https://github.com/sendgrid/sendgrid-ruby#usage

**Comment by coderdave** [comment]
Ah, ok, I'll try that. Thanks.

**Comment by thinkingserious** [comment]
Thanks! Please let us know how it goes.

**Comment by coderdave** [comment]
I finally got around to upgrading to v3. When I tested using reply_to, it still doesn't work.

`mail.reply_to = SendGrid::Email.new(email: 'davidsanderson101@yahoo.com')`

I get the email (to my gmail account) which is fine (and the custom name works) but when I try to reply to the email, it doesn't respect the reply_to I set up. It uses the regular reply email address that I used.

Is there something else I need to set?

**Comment by thinkingserious** [comment]
@coderdave,

Before you make the call to `API`, could you please provide the output of:
`puts JSON.pretty_generate(mail.to_json)`

**Comment by coderdave** [comment]
`[43] pry(main)> puts JSON.pretty_generate(mail.to_json)`
```javascript
{
  "from": {
    "email": "info@mycutsapp.com",
    "name": "bing bong berry"
  },
  "subject": "hopefully can reply to",
  "personalizations": [
    {
      "to": [
        {
          "email": "coderdave@gmail.com"
        }
      ]
    }
  ],
  "content": [
    {
      "type": "text/plain",
      "value": "Hello, Email!"
    }
  ],
  "reply_to": {
    "email": "davidsanderson101@yahoo.com",
    "name": "bing bong berry"
  }
}

**Comment by thinkingserious** [comment]
Please try putting that payload in a file named `post.json`

and run the following (after substituting your API key):

```bash
curl -X "POST" "https://api.sendgrid.com/v3/mail/send" \
        -H "Authorization: Bearer $SENDGRID_API_KEY"  \
        -H "Content-Type: application/json" \
        -d @post.json
```

**Comment by coderdave** [comment]
Same effect, email went through but it replies to "info@mycutsapp.com"

**Comment by thinkingserious** [comment]
Hmm, I can not reproduce the error with Gmail as the client. Do you mind sharing the raw headers of the email you receive in Gmail?

**Comment by coderdave** [comment]
Ok, I see what's going on. It looks like the reply-to is being set but unfortunately, gmail doesn't respect it. That's too bad. Are there any workarounds for that?

![hopefully_can_reply_to_-_coderdave_gmail_com_-_gmail](https://cloud.githubusercontent.com/assets/964751/17253637/99f37798-557f-11e6-8645-583e95c3f131.png)

**Comment by coderdave** [comment]
Update: I figured it out. I had my yahoo address set up in my gmail settings under "Send mail as"! So gmail was seeing that and used my gmail account instead.

Thanks for the help.

**Comment by thinkingserious** [comment]
Thanks for following up with your solution!
