### ISSUE TITLE
Sendgrid adding :default attachment

### ISSUE THREAD

**Issue by kempchee** [sendgrid/sendgrid-ruby#54]
When inlining an image based on the code example:

mail = SendGrid::Mail.new do |m|
  m.to = 'test@sendgrid.com'
  m.from = 'taco@cat.limo'
  m.subject = 'Hello world!'
  m.text = 'I heard you like the beach.'
  m.html = 'I heard you like the beach <div><img src="cid:beach"></div>'
end
mail.add_content('/tmp/beach.jpg', 'beach')
result = client.send(mail)

This generates a ":default" attachment which is a file with a single "0" in it when opened in a text editor.  The image gets inserted as expected.

**Comment by thinkingserious** [comment]
Thanks @kempchee,

We have added this to our backlog.

**Comment by matt-hu** [comment]
Hi @kempchee 
I already submit a pull request https://github.com/sendgrid/sendgrid-ruby/pull/47 for this issue. Please take a look. :-)

**Comment by thinkingserious** [comment]
Awesome, thank you!

**Comment by thinkingserious** [comment]
Please see the comment in the pull request. Thanks!
