### ISSUE TITLE
Using TemplateMailer to send email without a body

### ISSUE THREAD

**Issue by wmantegna** [sendgrid/sendgrid-ruby#56]
```
{"errors":["Missing email body"],"message":"error"}
```

My goal is to use the sendgrid-ruby gem to send a template without using an email body (the template should be the body). I receive the above error when using TemplateMailer.

I tried duplicating the code internal to the gem to see if I could work around it, but am still receiving the same error. Here's my code:

```
mail_defaults = { from: 'my@email.com', from_name: 'Admin', subject: 'Email is great' }
mail = SendGrid::Mail.new(mail_defaults)
mail.template = SendGrid::Template.new('my_template_id')

client = SendGrid::Client.new(api_user: ENV['SENDGRID_USERNAME'], api_key: ENV['SENDGRID_PASSWORD'])
client.send(mail.to_h)
```

Is there a best practice for this that I am missing? Or could this be a bug?

**Comment by thinkingserious** [comment]
Please try setting a non-empty string for the body value.

**Comment by wmantegna** [comment]
I've tried using 'hello' as the 'html' value, and I get the following response:
```
hello

This is my SendGrid Template
This is a substitution: bill
```

My goal is to only send the Template in the email, so that a non-technical person can use the SendGrid WYSIWYG editor to maintain the template over time. In the above example, I only want the last two lines of that email to be seen by the recipient.

**Comment by thinkingserious** [comment]
Can you do '<%body%>'?

**Comment by wmantegna** [comment]
The <%body%> tag is the first line in my template. Looks like if I move this tag to the bottom that the html text I pass in displays at the bottom of the email, which I can work with.

One last question, is there a way to remove the <%body%> tag from the Template and still have it work, or to replace it entirely? I'm hoping to be able to do as much of the email design as possible in the WYSIWYG editor.

**Comment by thinkingserious** [comment]
No, you must have the <%body%> tag.

Thanks for sharing your workaround. I'll push your feedback up to the product team.

Thanks!

**Comment by wmantegna** [comment]
Thanks to you as well!
