### ISSUE TITLE
Substitutions in a template

### ISSUE THREAD

**Issue by ashwinputhige** [sendgrid/sendgrid-ruby#58]
Question:

To substitute parameters, like -first_name-, -last_name-, etc, the only option is to use SMTP API as specified here([using-sendgrids-x-smtpapi-header](https://github.com/sendgrid/sendgrid-ruby#using-sendgrids-x-smtpapi-header)). Is that correct?

I did not see any option to set substitutions directly on the Sendgrid::Mail object.
```
mail = SendGrid::Mail.new
mail.subs = 'IS_IT_POSSIBLE_TO_SECIFY_SUBSTITUTIONS_HERE'
```

**Comment by gurgelrenan** [comment]
You could use like describe here too https://github.com/sendgrid/sendgrid-ruby#working-with-templates

**Comment by ashwinputhige** [comment]
Thank you for your response @gurgelrenan 

But in that API, after creating Recipients, Template and Client, the document says that you have to set the HTML while creating the TemplateMailer.

```
mail_defaults = {
  from: 'admin@email.com',
  html: '<h1>I like email</h1>',
  text: 'I like email',
  subject: 'Email is great'
}
```

This is what threw me off. Why set HTML when the `template` has html already?

**Comment by gurgelrenan** [comment]
Yeah, for me look strange too, but I have searched I found this approach: 

```
mail_defaults = {
      from: 'no-reply@email.com',
      from_name: 'Admin',
      subject: "My subject",
      html: ' ',
      text: ' '
    }
```

Put HTML and Text with a `' '` empty string. It works for me.

**Comment by ashwinputhige** [comment]
Thanks @gurgelrenan
