### ISSUE TITLE
SendGrid's X-SMTPAPI Header - delivering to multiple addresses with template and subs

### ISSUE THREAD

**Issue by simicic** [sendgrid/sendgrid-ruby#60]
Hi,
I am unable to send emails to multiple users with the predefined template and substitutions. Code is as follows:

```
client = SendGrid::Client.new(api_key: ENV['SENDGRID_API'])
header = Smtpapi::Header.new
header.add_to(recipients_emails) // array of emails
header.add_substitution('-invitation_text-', invitation_texts) // arrays of customised texts
header.add_substitution('-landing_url-', landing_urls) // arrays of customised links
header.add_filter('templates', 'enable', 1)
header.add_filter('templates', 'template_id', ENV['BULK_EMAIL_TEMPLATE']) // template that has <% body %> only, I want the substitution to be done from my email html and text parameter

mail = SendGrid::Mail.new(email.except(:to)) // email has subject from, subject, text and html
mail.smtpapi = header
client.send(mail)
```
It always sends the proper email for the first recipient, but not for the rest.
Am I missing something obvious? 
Thank you!

**Comment by thinkingserious** [comment]
Could you try examining the contents of the header object with `header.to_json`?

**Comment by thinkingserious** [comment]
Hello @simicic,

We have a new v3 /mail/send API to make this easier: https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html

The new version of this library supports that endpoint: https://github.com/sendgrid/sendgrid-nodejs/blob/master/examples/helpers/mail/example.js#L15

Please let us know if you need additional help.
