### ISSUE TITLE
How to set a default from?

### ISSUE THREAD

**Issue by tiagoovieira** [sendgrid/sendgrid-ruby#62]
I created a method called

```
def default_from
  'A name <email@someaddress.com>'
end
```

But when an email is sent, in the mailbox, the sender name is `email` but I want to show `A name`.
Do I do that in the application or I have to configure in sendgrid itself?

**Comment by thinkingserious** [comment]
Hello @tiagoovieira,

If your are using the library, you will set the from name: https://github.com/sendgrid/sendgrid-ruby/blob/master/lib/sendgrid/mail.rb#L7 in addition to the from email.

Thanks!

Elmer
