### ISSUE TITLE
Multiple substitutions in one method call?

### ISSUE THREAD

**Issue by ridget** [sendgrid/sendgrid-ruby#65]
Hi there,

Ive noted from the readme that the current way to handle multiple substitutions is to make multiple calls to `add_substitution`. Would there be any interest in supporting an `add_substitutions` method, which could take a hash and reduce the need to call this multiple times?

**Comment by thinkingserious** [comment]
Hi @ridget,

I think that is a good idea, here is how we implement it now in the new library: https://github.com/sendgrid/sendgrid-csharp/blob/v3beta/SendGrid/SendGrid/Helpers/Mail/Mail.cs#L1272. 

Are you interested in providing a pull request or would you like us to implement it? If it's the former, please sign our [CLA](https://github.com/sendgrid/sendgrid-csharp/blob/v3beta/CONTRIBUTING.md#cla) and make your pull request against our [v3beta branch](https://github.com/sendgrid/sendgrid-csharp/tree/v3beta), if it's the latter we will leave this ticket open and add it to our backlog.

Thanks!

Elmer
