### ISSUE TITLE
Running "Hello Email" sample code gets a 400 error response from the API

### ISSUE THREAD

**Issue by safetymonkey** [sendgrid/sendgrid-ruby#67]
#### Issue Summary

I am attempting to set up my Sendgrid integration and as a first step I copied the Hello Email code on this project's root page, changed the email address to be valid, and then ran it in the Rails console. (The environment variable for my API key is valid, as well.) I get the following error:
`2.3.1 :040 >   response = sg.client.mail._('send').post(request_body: mail.to_json)
 => #<SendGrid::Response:0x007f9df0fdfa80 @status_code="400", @body="{\"errors\":[{\"message\":\"Invalid type. Expected: object, given: string.\",\"field\":\"(root)\",\"help\":\"http://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/errors.html#-Request-Body-Parameters\"}]}", @headers="{\"server\"=>[\"nginx\"], \"date\"=>[\"Mon, 20 Jun 2016 19:29:20 GMT\"], \"content-type\"=>[\"application/json\"], \"content-length\"=>[\"191\"], \"connection\"=>[\"close\"], \"x-frame-options\"=>[\"DENY\"]}">`
#### Steps to Reproduce
1. Copy "Hello Email" code into text editor.
2. Replace to: email address with valid personal email address.
3. Paste the modified code into the Rails console.
#### Technical details:
- sendgrid-ruby Version: 3.0.4
- Ruby Version: 2.3.1

**Comment by thinkingserious** [comment]
Hello @safetymonkey,

Could you please let me know what the return value of mail.to_json is? Thanks!

**Comment by safetymonkey** [comment]
```
2.3.1 :013 > mail.to_json
 => "{\"body\":{\"boundary\":null,\"preamble\":null,\"epilogue\":null,\"charset\":\"US-ASCII\",\"part_sort_order\":[\"text/plain\",\"text/enriched\",\"text/html\"],\"parts\":[],\"raw_source\":\"\",\"encoding\":\"7bit\"},\"body_raw\":null,\"separate_parts\":false,\"text_part\":null,\"html_part\":null,\"errors\":null,\"header\":[{\"charset\":\"UTF-8\",\"name\":\"#\\u003cSendGrid\",\"raw_value\":\"#\\u003cSendGrid::Email:0x007f845b13e570\\u003e\",\"value\":\":Email:0x007f845b13e570\\u003e\",\"field\":{\"errors\":[],\"charset\":\"UTF-8\",\"name\":\"#\\u003cSendGrid\",\"length\":null,\"tree\":null,\"element\":null,\"value\":\":Email:0x007f845b13e570\\u003e\"}}],\"charset\":\"UTF-8\",\"defaulted_charset\":true,\"smtp_envelope_from\":null,\"smtp_envelope_to\":null,\"perform_deliveries\":true,\"raise_delivery_errors\":true,\"delivery_handler\":null,\"delivery_method\":{\"settings\":{\"address\":\"localhost\",\"port\":25,\"domain\":\"localhost.localdomain\",\"user_name\":null,\"password\":null,\"authentication\":null,\"enable_starttls_auto\":true,\"openssl_verify_mode\":null,\"ssl\":null,\"tls\":null}},\"transport_encoding\":{},\"mark_for_delete\":false,\"raw_source\":\"#\\u003cSendGrid::Email:0x007f845b13e570\\u003e\"}"
```

Interestingly, I was able to get the code to succeed in IRB but not in the Rails console. I suppose this points to a problem with my environment setup but the error message returned from the API was frustratingly vague.

**Comment by safetymonkey** [comment]
It looks like there is something in the Rails console that is conflicting with Sendgrid that isn't happening in IRB. In the console the mail.class is `Mail::Message` and in IRB it's `SendGrid::Mail`.

This looks like a local setup issue so feel free to resolve, although if you have any helpful ideas I'd be all ears

**Comment by safetymonkey** [comment]
Alright, I figured it out. It's an embarrassing "LRN 2 code n00b" moment. Mail.new is being hijacked in Rails by ActionMailer. Instead of trying to figure out how to hand that back to the Sendgrid gem I can just specify `SendGrid::Mail.new` and that does the trick.

Sorry for the dumb question. I'll resolve the issue.

**Comment by thinkingserious** [comment]
Not dumb at all, and it's greatly appreciated that you took the time to share the solution. I'm sure you'll help someone who is having a similar issue in the future.

**Comment by christianroy** [comment]
Hello, n00b here. :) Had a similar issue in my production environment (but worked fine in dev), this thread helped me a lot. So just confirming "you'll help someone who is having a similar issue in the future". Thanks a lot @safetymonkey.

**Comment by safetymonkey** [comment]
I'm happy to try and help if you can provide more info on exactly what you're seeing.

**Comment by christianroy** [comment]
Oh don't worry @safetymonkey, I solved my problem by specifying `SendGrid::Mail.new` like you did. I was just thanking you for your documentation efforts back in June...

**Comment by safetymonkey** [comment]
Ah. I'm glad it helped!

**Comment by VictorAcatrinei** [comment]
Would this fix be something that can be added to the documentation or in some place that can be visible for even more people?

**Comment by thinkingserious** [comment]
Great idea @VictorAcatrinei,

We will get it added to the TROUBLESHOOTING.md document.

**Comment by senyoAsamoah** [comment]
@safetymonkey - thanks a lot, run into similar issue implementing sendgrid on my local dev and coming across his thread and your solution helped

**Comment by thedanotto** [comment]
@safetymonkey never woulda figured it out with you!!! Can't believe this hasn't been updated in their documentation

**Comment by thinkingserious** [comment]
Hi @thedanotto!

Thanks for following up with some feedback!

If you don't mind, to help us improve, could you share the places you looked before you arrived here? 

With Best Regards,

Elmer

**Comment by pieterb82** [comment]
Was creating a rake task to test the mailer, which gave the same error. Fixed it with adding the SendGrid:: before all the lines with New. Thanks @safetymonkey!
