### ISSUE TITLE
Question about variable substitution using the Mail helper

### ISSUE THREAD

**Issue by safetymonkey** [sendgrid/sendgrid-ruby#68]
This is basically the same question as #58 but I'm afraid I didn't understand the answer there.

I'm trying to use the Mail object in this gem to hit the Web v3 API, but I can't seem to get variable substitution working. Is my only option to use the SMTP API or am I missing something?

My template has the following included in it:  `-templatevar-`

My `mail.to_json` looks like this:
`{"from"=>{"email"=>"no-reply@mysite.com"}, "subject"=>"Trying out substitutions", "personalizations"=>[{"to"=>[{"email"=>my-address@gmail.com"}]}], "content"=>[{"type"=>"text/html", "value"=>"A variable should go right here: -variable-"}], "template_id"=>"ZZZZZ", "sections"=>{"%variable%"=>"Percent sub", "-variable-"=>"Dash sub", "-templatevar-"=>"Dash sub on template var"}}`

I've been banging my head against this and feel like I'm missing something critical here. Thanks in advance for any help!

**Comment by thinkingserious** [comment]
Hello @safetymonkey,

Have you taken a look at the example here? https://github.com/sendgrid/sendgrid-ruby/blob/master/examples/helpers/mail/example.rb#L35 or if you prefer not to use the helper: https://github.com/sendgrid/sendgrid-ruby/blob/master/USAGE.md#post-mailsend

Thanks!

**Comment by safetymonkey** [comment]
Yeah, I've definitely looked at that. The example file isn't really as explicit as I'd like. I've tried both:

`p.substitutions = Substitution.new(key: '-variable-', value: 'Personalization replacement for dashes in text')`
and
`p.substitutions = Substitution.new(key: '%variable%', value: 'Personalization replacement for percent signs in text')`

Neither appears to work. My template has `-variable-` in it per the Sendgrid documentation: https://sendgrid.com/docs/API_Reference/SMTP_API/substitution_tags.html. Granted, that documentation is for the SMTP_API. The closest I've gotten is that the `-variable-` personalization substitution causes that text to disappear in the delivered email but it isn't replacing it with the new text.

I am confused about the difference between substitutions as part of a Personalization object versus those that are attached directly to the Mail object. What is the difference between https://github.com/sendgrid/sendgrid-ruby/blob/master/examples/helpers/mail/example.rb#L35 and https://github.com/sendgrid/sendgrid-ruby/blob/master/examples/helpers/mail/example.rb#L81?

Thanks for your help!

**Comment by thinkingserious** [comment]
Hello @safetymonkey,

The full documentation on the endpoint can be found here: https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html

Can you please provide us with the source code you are using to generate the request object? I'm thinking your issue is related to this one: https://github.com/sendgrid/sendgrid-java/issues/114

**Comment by safetymonkey** [comment]
Alright, well, this is frustrating/embarassing. I was mainly experimenting in the Rails console; I took everything I had been doing in there and copied/pasted it into a text editor and then when I re-ran it everything worked. I can only assume there was some order-of-oprations problem in what I was doing. In the interests of posterity I'm posting everything I did here. Sorry to be a nuisance and thanks for the help!

**Template:**
```
Template variable! 
Dashes: -templatevar-
Percent: %templatevar-

<%body%>
```

**Code being executed:**
```
include SendGrid

from = Email.new(email: 'no-reply@example.com')
to = Email.new(email: 'myemail@gmail.com')
subject = 'SendGrid email teplate test'
message = 'API variables: Percent signs (%apivar%), Dashes (-apivar-)'
content = Content.new(type: 'text/html', value: message)
mail = SendGrid::Mail.new(from, subject, to, content)
mail.template_id = '590b0c26-0c00-475c-b703-de8613d59db2'

# Substitutions via Personalization
personalization = Personalization.new
personalization.to = Email.new(email: 'myemail+personalization@gmail.com')
personalization.substitutions = Substitution.new(
  key: '%templatevar%', value: 'Replacement for percent sign templatevar'
)
personalization.substitutions = Substitution.new(
  key: '-templatevar-', value: 'Replacement for dash sign templatevar'
)

sg = SendGrid::API.new(api_key: ENV['SENDGRID_API_KEY'])
response = sg.client.mail._('send').post(request_body: mail.to_json)
```

**JSON output from that mail object:**
```
{
  "from": {
    "email": "no-reply@example.com"
  },
  "subject": "SendGrid email teplate test",
  "personalizations": [
    {
      "to": [
        {
          "email": "jon.grover@gmail.com"
        }
      ]
    },
    {
      "to": [
        {
          "email": "myemail+personalization@gmail.com"
        }
      ],
      "substitutions": {
        "%templatevar%": "Replacement for percent sign templatevar",
        "-templatevar-": "Replacement for dash sign templatevar",
        "%apivar%": "Replacement for percent sign apivar",
        "-apivar-": "Replacement for dash sign apivar"
      }
    }
  ],
  "content": [
    {
      "type": "text/html",
      "value": "API variables: Percent signs (%apivar%), Dashes (-apivar-)"
    }
  ],
  "template_id": "590b0c26-0c00-475c-b703-de8613d59db2"
}
```

**Resulting email:**
```
Template variable! 
Dashes: Replacement for dash sign templatevar
Percent: Replacement for percent sign templatevar

API variables: Percent signs (Replacement for percent sign apivar), Dashes (Replacement for dash sign apivar)
```

**Comment by thinkingserious** [comment]
Thanks for taking the time to share your final solution!

**Comment by garethson** [comment]
@safetymonkey Thanks for the detailed writeup. I ran into issues upgrading to the new API as well, for some reason using `*variable_name*` simply doesn't work with the new version. Using `-variable_name-` does seem to work. 👍

**Comment by kpalania** [comment]
I am using the latest version of the gem (5.1.0) and am running into similar substitution issues :( 

The mail is sent successfully, and it finds the template I am using but simply does not replace the placeholders. Any thoughts?

**Comment by thinkingserious** [comment]
Hi @kpalania,

Do you mind sharing the relevant code?

Thanks!

Elmer

**Comment by kpalania** [comment]
Absolutely, here it is @thinkingserious :

```
include SendGrid
API_KEY="REPLACE"
TEMPLATE_ID="REPLACE"

mail=SendGrid::Mail.new
mail.template_id = TEMPLATE_ID
mail.from = Email.new(email: "REPLACE")
mail.subject = "REPLACE"
personalization = Personalization.new
personalization.add_to SendGrid::Email.new(email: "REPLACE")
personalization.add_substitution Substitution.new key: "__user_name__", value: "REPLACE"
personalization.add_substitution Substitution.new key: "%username%", value: "REPLACE"
mail.add_personalization personalization
mail.add_content SendGrid::Content.new(type: 'text/html', value: "this is the body!")
api = SendGrid::API.new api_key: API_KEY
response = api.client.mail._('send').post request_body: mail.to_json
puts response.status_code
puts response.body
puts response.headers
```

**Comment by thinkingserious** [comment]
Maybe the issue is the substitution characters, could you please try using dashes like so: https://github.com/sendgrid/sendgrid-ruby/blob/master/USE_CASES.md#transactional_templates

**Comment by kpalania** [comment]
Actually I had tried that as well (though my example didn't include it) along with a bunch of other special characters at random but none of them worked for me.

**Comment by kpalania** [comment]
I tried some of the older versions of the gem as well and they don't work for me either (went all the way back to 4.0.8).

Is it possible something changed with how SendGrid is handling this? I see some changes in their UI (design/code view) but tried creating newer templates just to eliminate any issues with my existing templates - still the same problem.

**Comment by thinkingserious** [comment]
Could you please try again now? It seems there was an issue with our servers that should now be resolved.

**Comment by kpalania** [comment]
Works like magic now, @thinkingserious! Thanks much!
