### ISSUE TITLE
No upgrade notes for 3.0?

### ISSUE THREAD

**Issue by dbackeus** [sendgrid/sendgrid-ruby#69]
The note in the changelog regarding `Breaking change to support the v3 Web API` doesn't help the upgrade process much.

Any chance of some documentation on upgrading from 2.x?

**Comment by thinkingserious** [comment]
Hello @dbackeus,

Following are some resources that should help:

- Migrating: https://sendgrid.com/docs/Classroom/Send/v3_Mail_Send/how_to_migrate_from_v2_to_v3_mail_send.html

- v3 Web API: https://sendgrid.com/docs/API_Reference/Web_API_v3/index.html

- Example Code: https://github.com/sendgrid/sendgrid-ruby/tree/master/examples

- Mail Send Helper: https://github.com/sendgrid/sendgrid-ruby/blob/master/examples/helpers/mail/example.rb

- Mail Send Without the Helper: https://github.com/sendgrid/sendgrid-ruby/blob/master/examples/mail/mail.rb#L26

- Usage Documentation: https://github.com/sendgrid/sendgrid-ruby/blob/master/USAGE.md

If you have further questions, please let us know.

Thanks!

With Best Regards,

Elmer
