### ISSUE TITLE
Invalid user name and password exception handling

### ISSUE THREAD

**Issue by mledom** [sendgrid/sendgrid-ruby#7]
We started using this gem for simple email sending. During the building phase I came across an error because I did not have my configuration setup properly. The error from SendGrid was "{\"message\": \"error\", \"errors\": [\"Bad username / password\"]}". 

When the gem raises the error the message is being passed straight to the SendGrid::Exception class. Should the exception parse the json string and parse the error message out and do something like:
j = JSON.parse( message )
return super(j.try( :[], 'error' )) if ( message.try( :[], 'message' ) == 'error' && message.try(:[], 'error'.present?)
super( message )

**Comment by thinkingserious** [comment]
Hello @mledom,

This library will be replaced by this one in a few weeks: https://github.com/sendgrid/sendgrid-ruby/tree/v3beta

Please let us know if you continue to experience this issue.

With Best Regards,

Elmer
