### ISSUE TITLE
Sender Identities API End Point Location?

### ISSUE THREAD

**Issue by rovermicrover** [sendgrid/sendgrid-ruby#73]
#### Issue Summary & Steps to Reproduce

I can't find the following end point in the ruby gem Docs
https://sendgrid.com/docs/API_Reference/Web_API_v3/Marketing_Campaigns/sender_identities.html

As a result I made my best guess and tried

``` ruby
SENDGRID_API.client.senders.post(request_body: {
   "nickname" => "Alert",
   "from" => {
     "email" => "no-reply@alerts.mydomain.com",
     "name" => "Alert"
   }
})
```

But, I get a 403 error, even though other end points are working fine, and I have given the API Key full permissions.

Am I not using the correct end point? I believe I am following the pattern.

Also I have already whitelisted the domain the email is coming from.
#### Technical details:
- sendgrid-ruby latest version
- Ruby Version: 2.3.1

**Comment by thinkingserious** [comment]
Hello @rovermicrover,

I'm not sure about the status of that endpoint. I have put in a question to find out. As soon as I learn more, I will respond here.

Otherwise, you may want to reach out to https://support.sendgrid.com.

Thanks!

**Comment by thinkingserious** [comment]
Hello @rovermicrover,

I believe this may be the endpoint you are looking for: https://sendgrid.com/docs/API_Reference/Web_API_v3/Marketing_Campaigns/sender_identities.html#-Create-a-Sender-Identity-POST

**Comment by rovermicrover** [comment]
Yes that was the link to the API end point I posted above. My question is if I am invoking it correctly using the ruby gem or not. 

The reason I am asking is that that end point is missing from the usage doc for this gem. See below
https://github.com/sendgrid/sendgrid-ruby/blob/master/USAGE.md

**Comment by thinkingserious** [comment]
Thanks for the quick response, I will verify.

**Comment by thinkingserious** [comment]
@rovermicrover,

It looks like you are missing a few required fields:

"address", "city", and "country"

Please give that a try and let us know. Thanks!

**Comment by rovermicrover** [comment]
Still 403 Forbidden. I assume that if the problem was with missing fields I would have been getting a 422 Unprocessable Entity with validate errors returned.

I have reached out to support and opened a ticket. I can't even create a sender via the web interface, throws an error message of "cannot retrieve your sender identities" when i try to go the index of senders.

**Comment by thinkingserious** [comment]
@rovermicrover,

Thanks for opening a ticket. If you don't mind, please let us know the resolution.
