### ISSUE TITLE
substitutions with transactional templates is broken

### ISSUE THREAD

**Issue by 34code** [sendgrid/sendgrid-ruby#80]
#### Issue Summary

substitutions with transactional templates is broken

#### Steps to Reproduce

1. create a transactional template
2. create some substitution vars with %user_name% or user_name format
3. Try to send email using example code (v3 api)

variables should be replaced properly in the transactional template. This is badly broken. Also %var% inside things like href="%var%" or src="%var%" are not respected at all when trying to save in the code editor online on sendgrid.com. The template removes the % symbols after saving.

#### Technical details:

* sendgrid-ruby Version: master
* Ruby Version: 2.2.3

**Comment by thinkingserious** [comment]
@34code,

Could you please provide the relevant source code? I can not reproduce.

This is what I have in the template:

<html>
<head></head>
<body>
Hello %name%,
<br/>
<br/>
%city%
<br/>
<br/>
<a href="%var%">%value%</a>
<br/>
<br/>
With Best Regards,
<br/>
<br/>
Your Library Tester
</body>
</html>

And here is my source code:

```ruby
require 'sendgrid-ruby'
include SendGrid
require 'json'

def hello_world
  mail = Mail.new
  mail.from = Email.new(email: 'dx@sendgrid.com')
  mail.subject = 'Hello World from the SendGrid Ruby Library'
  p = Personalization.new
  p.to = Email.new(email: 'elmer@sendgrid.com')
  p.substitutions = Substitution.new(key: '%name%', value: 'Elmer Thomas')
  p.substitutions = Substitution.new(key: '%city%', value: 'Denver')
  p.substitutions = Substitution.new(key: '%var%', value: 'http://www.sendgrid.com')
  p.substitutions = Substitution.new(key: '%value%', value: 'SendGrid.com')
  mail.personalizations = p
  # This will no longer be a requirement soon
  mail.contents = Content.new(type: 'text/html', value: 'test')
  mail.template_id = '13b8f94f-bcae-4ec6-b752-70d6cb59f932'

  sg = SendGrid::API.new(api_key: ENV['SENDGRID_API_KEY'], host: 'https://api.sendgrid.com')
  response = sg.client.mail._('send').post(request_body: mail.to_json)
  puts response.status_code
  puts response.body
  puts response.headers
end

hello_world
```

And the resulting email:

http://www.screencast.com/t/MXHgvQ3k

**Comment by 34code** [comment]
And this is a transactional template on sendgrid.com correct? I wanted to see if the %something% (% symbols) are absolutely required. If yes, the visual code editor on sendgrid.com doesn't store % if you have one for a %user_name% and one for a %link% within html tags.

This results in substitution errors I believe. 

But I'll try once again with the latest rubygem and let you know if this is continuing to happen.

**Comment by thinkingserious** [comment]
@34code,

Yes, I created the template here: https://sendgrid.com/templates

You do not have to use % symbols. I usually use -variable-.

Can you share the template that is giving you grief? I was not able to reproduce using the template above. Thanks!

**Comment by 34code** [comment]
now on 4.0.0 and 4.0.1 on rails5 ..

excerpt from interactive console .. its not recognizing sendgrid methods now :(

```
>> u = Mail.new
=> #<Mail::Message:70328442340080, Multipart: false, Headers: >
>> u.template_id = "foo"
!! #<NoMethodError: undefined method `template_id=' for #<Mail::Message:70328442340080, Multipart: false, Headers: >>
>> u.methods
=> [:delivery_handler, :delivery_handler=, :perform_deliveries, :perform_deliveries=, :raise_delivery_errors, :raise_delivery_errors=, :register_for_delivery_notification, :inform_observers, :inform_interceptors, :deliver, :deliver!, :delivery_method, :reply, :<=>, :==, :raw_source, :set_envelope, :raw_envelope, :envelope_from, :envelope_date, :header=, :header, :headers, :errors, :bcc, :bcc=, :cc, :cc=, :comments, :comments=, :content_description, :content_description=, :content_disposition, :content_disposition=, :content_id, :content_id=, :content_location, :content_location=, :content_transfer_encoding, :content_transfer_encoding=, :content_type, :content_type=, :date, :date=, :transport_encoding, :transport_encoding=, :from, :from=, :in_reply_to, :in_reply_to=, :keywords, :keywords=, :message_id, :message_id=, :mime_version, :mime_version=, :received, :received=, :references, :references=, :reply_to, :reply_to=, :resent_bcc, :resent_bcc=, :resent_cc, :resent_cc=, :resent_date, :resent_date=, :resent_from, :resent_from=, :resent_message_id, :resent_message_id=, :resent_sender, :resent_sender=, :resent_to, :resent_to=, :return_path, :return_path=, :sender, :sender=, :smtp_envelope_from, :smtp_envelope_from=, :smtp_envelope_to, :smtp_envelope_to=, :subject, :subject=, :to, :to=, :default, :body=, :body, :body_encoding, :body_encoding=, :destinations, :from_addrs, :to_addrs, :cc_addrs, :bcc_addrs, :[]=, :[], :method_missing, :header_fields, :has_message_id?, :has_date?, :has_mime_version?, :has_content_type?, :has_charset?, :has_content_transfer_encoding?, :has_transfer_encoding?, :add_message_id, :add_date, :add_mime_version, :add_content_type, :add_charset, :add_content_transfer_encoding, :add_transfer_encoding, :transfer_encoding, :mime_type, :message_content_type, :charset, :charset=, :main_type, :sub_type, :mime_parameters, :content_type_parameters, :multipart?, :multipart_report?, :delivery_status_report?, :delivery_status_part, :bounced?, :action, :final_recipient, :error_status, :diagnostic_code, :remote_mta, :retryable?, :boundary, :parts, :attachments, :has_attachments?, :html_part, :text_part, :html_part=, :text_part=, :add_part, :part, :add_file, :convert_to_multipart, :ready_to_send!, :encode!, :encoded, :without_attachments!, :to_yaml, :to_s, :inspect, :decoded, :read, :decode_body, :attachment?, :attachment, :filename, :all_parts, :find_first_mime_type, :skip_deletion, :mark_for_delete=, :is_marked_for_delete?, :text?, :atom_safe?, :quote_atom, :quote_phrase, :token_safe?, :quote_token, :dquote, :unquote, :paren, :unparen, :bracket, :unbracket, :escape_paren, :uri_escape, :uri_unescape, :uri_parser, :match_to_s, :capitalize_field, :constantize, :dasherize, :underscoreize, :map_lines, :map_with_index, :to_json, :psych_to_yaml, :to_yaml_properties, :blank?, :present?, :presence, :to_param, :to_query, :acts_like?, :duplicable?, :deep_dup, :in?, :presence_in, :instance_values, :instance_variable_names, :as_json, :with_options, :html_safe?, :to_imap_date, :methods, :private_methods, :protected_methods, :public_methods, :singleton_methods, :pry, :__binding__, :dclone, :`, :require_or_load, :require_dependency, :load_dependency, :unloadable, :pretty_print, :pretty_print_cycle, :pretty_print_instance_variables, :pretty_print_inspect, :try, :try!, :nil?, :===, :=~, :!~, :eql?, :hash, :class, :singleton_class, :clone, :dup, :itself, :taint, :tainted?, :untaint, :untrust, :untrusted?, :trust, :freeze, :frozen?, :instance_variables, :instance_variable_get, :instance_variable_set, :instance_variable_defined?, :remove_instance_variable, :instance_of?, :kind_of?, :is_a?, :tap, :send, :public_send, :respond_to?, :extend, :display, :method, :public_method, :singleton_method, :define_singleton_method, :object_id, :to_enum, :enum_for, :gem, :class_eval, :pretty_inspect, :ai, :awesome_inspect, :awesome_print, :byebug, :debugger, :suppress_warnings, :equal?, :!, :!=, :instance_eval, :instance_exec, :__send__, :__id__]
```

**Comment by 34code** [comment]
Oops -- it seems I need to Prefix with `SendGrid:: ` to get some of these methods working inside the UserMailer in rails.

But I can confirm that the web editor is eating up the %'s inside href tags. not good if you plan to use % for variable substitutions.

I think this issue can be closed if the web-editor code-view is fixed for transactional templates.

**Comment by thinkingserious** [comment]
@34code,

Are you saying that the following code should have the href tag eaten?

```html
<html>
<head></head>
<body>
Hello %name%,
<br/>
<br/>
%city%
<br/>
<br/>
<a href="%var%">%value%</a>
<br/>
<br/>
With Best Regards,
<br/>
<br/>
Your Library Tester
</body>
</html>
```

In my case, the tag remains unmodified.

**Comment by 34code** [comment]
%var_something% at least in my template (inside href "" quotes)

**Comment by thinkingserious** [comment]
@34code,

Do you mind sending us (dx@sendgrid.com) before and after screenshots so I can file the bug report?

**Comment by 34code** [comment]
![cursor_and_sendgrid_marketing_campaigns](https://cloud.githubusercontent.com/assets/930787/17320532/e9889dd0-5848-11e6-9886-2e1e09a32199.png)

Cannot specify custom "image_path" to be dynamically replaced when trying to enter a responsive image widget.

**Comment by thinkingserious** [comment]
Hello @34code,

Our support team will be able to help with that one. Please reach out via https://support.sendgrid.com.

Thanks!

**Comment by themoor88** [comment]
Hello @34code and @thinkingserious,

Did you two figure out a solution to this? I am having the same problems for my emails as well. The older version of this gem seemed to work fine for transactional emails but didn't provide support for adding recipients to the contacts DB. The newer version works great for adding recipients but is not consistent with substitutions for transactional emails.

I have tried using -email- and %email% in all of my substitutions and the emails being sent sometimes have the substitutions or sometimes don't. It is not consistent. Any ideas?

Here is my application mailer
```
# frozen_string_literal: true
class ApplicationMailer < ActionMailer::Base
  include SendGrid
  # rubocop:disable Metrics/AbcSize
  def sendgrid_send(options = {})
    # Reverse merge here provides us with default paramaters
    options.reverse_merge! to: Figaro.env.override_send_to_email,
                           subject:  %w(development integration).include?(Rails.env) ? "[#{Rails.env}]" : ' ',
                           substitutions: {}

    # Build up paramters for instantiating a new Mail object
    from = Email.new(email: Figaro.env.sendgrid_from_email, name: Figaro.env.sendgrid_from_name)
    subject = options[:subject]
    content = Content.new(type: 'text/html', value: Figaro.env.sendgrid_from_name)

    # A personlization object can have substitutions
    personalization = Personalization.new

    options[:substitutions].each do |k, v|
      personalization.substitutions = Substitution.new(key: k.to_s, value: v)
    end

    # Always use the override_send_to_email if it exists
    to = personalization.to = if Figaro.env.override_send_to_email.present?
                                Email.new(email: Figaro.env.override_send_to_email)
                              else
                                Email.new(email: options[:to])
                              end

    # Setup the Mail object, add personalizations and templates
    mail = Mail.new(from, subject, to, content)
    mail.personalizations = personalization
    mail.template_id = options[:template_id]

    # Setup the mailer
    mailer = SendGrid::API.new(api_key: Figaro.env.sendgrid_api_key)

    # Send the email
    mailer.client.mail._('send').post(request_body: mail.to_json)
  end
  # rubocop:enable Metrics/AbcSize
end
```

Cheers,
Wajid

**Comment by thinkingserious** [comment]
Hello @themoor88,

I believe the issue is with this code: `mail = Mail.new(from, subject, to, content)`

When you use that constructor, it creates a personalization for you and is generally used for simple hello world type emails.

Please do this instead: https://github.com/sendgrid/sendgrid-ruby/blob/master/examples/helpers/mail/example.rb#L21

To help debug, it's useful to print the value of `mail.to_json` to make sure the generated JSON is correct, per: https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html

Thanks!

**Comment by themoor88** [comment]
Hello @thinkingserious 

Thanks a lot for the fix. It works like a charm now!

Cheers,
Wajid

**Comment by thinkingserious** [comment]
Thanks for following up :)

**Comment by Elyahou** [comment]
I have the same issue. Using substititutions and it only works sometimes. I always check my generated json and all seems ok, the substition tags are here. But they are getting replaced in the template only sometimes... What can I do for this ?

**Comment by thinkingserious** [comment]
Hi @Elyahou,

Do you mind creating a new issue with this along with an example that we can try to reproduce? 

Thanks!

With Best Regards,

Elmer
