### ISSUE TITLE
Delete Recipient without id

### ISSUE THREAD

**Issue by maxsieben** [sendgrid/sendgrid-ruby#82]
I want to ask if it's possible to delete an existing recipient, without using the id.

I found this example: https://github.com/sendgrid/sendgrid-ruby/blob/master/examples/contactdb/contactdb.rb#L213

However it doesn't say, which attributes for data are required when calling: sg.client.contactdb.recipients.delete(request_body: data) .

Is it possible to delete an recipient by passing in an email address or do I need to pass the recipients id in the data object?

**Comment by thinkingserious** [comment]
You need to pass the recipient ID, please see: https://sendgrid.com/docs/API_Reference/Web_API_v3/Marketing_Campaigns/contactdb.html#Delete-Recipient-DELETE

You did find a bug though, the example is incomplete and I'll leave this ticket open until we fix it.

**Comment by thinkingserious** [comment]
Fixed: https://github.com/sendgrid/sendgrid-ruby/releases/tag/v4.0.2

Thanks again!
