### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by MincePie** [sendgrid/sendgrid-ruby#83]
#### Issue Summary

I'm struggling to understand the documentation for how to get started using WebAPI v3.

The authentication section of the getting started section says "  To use keys, you must set a plain text header named “Authorization” with the contents of the header being “Bearer XXX” where XXX is your API Secret Key." https://sendgrid.com/docs/API_Reference/Web_API_v3/How_To_Use_The_Web_API_v3/authentication.html

Q1: Where & how do I set this text header?

The transactional templates overview says "Including the template ID in the templates parameter of the Web API v3 Mail Send endpoint"  This page has a link to Ruby libraries, which in turn links to this gem.

Q2: Where and how do I include a template ID in the endpoint?

The sendgrid-ruby gem documentation has an example for various ways to use the gem. The examples for General v3 Web API Usage distinguish between cases where fluent influence is or is not used. Googling fluent influence doesnt lead me to any enlightenment. 

Q3: What is fluent influence? How do I determine whether or not I should be using it?

If I do pick a General v3 Web API Usage option, 

where in my app do I write these lines?

```
 require 'sendgrid-ruby'
sg = SendGrid::API.new(api_key: ENV['SENDGRID_API_KEY'])
response = sg.client._("suppression/bounces").get()
puts response.status_code
puts response.body
puts response.headers

```

Once I've figured out how and where to write the above lines, how do I ask my app to send a template email that I have made in Sendgrid's transactional templates section?

Thank you very much for your help in getting started.
#### Technical details:

gem 'sendgrid-ruby'
gem 'sendgrid-rails', '~> 2.0'
gem 'mail'
ruby "2.3.0"

**Comment by thinkingserious** [comment]
Hi @MincePie!

Thanks for reaching out to us! Following are the answers to your questions:

Q1: This library handles that for you with this call: `sg = SendGrid::API.new(api_key: ENV['SENDGRID_API_KEY'])
`

Q2: Here is some example code for sending a template:

```ruby
sg = SendGrid::API.new(api_key: ENV['SENDGRID_API_KEY'])

email = SendGrid::Mail.new
email.from = SendGrid::Email.new(email: "test@example.com", name: "Example Name")
email.subject = "Your Email's Subject"

p = SendGrid::Personalization.new
p.to = SendGrid::Email.new(email: "test@example.com", name: "Example User")
p.substitutions = SendGrid::Substitution.new(key: "key1", value: "value1")
p.substitutions = SendGrid::Substitution.new(key: "key2", value: "value2")

email.personalizations = p
email.template_id = "[YOUR TEMPLATE ID]"

response = sg.client.mail._('send').post(request_body: email.to_json)

puts response.status_code
puts response.body
puts response.headers
```

Q3: Here are some details about fluent interfaces: https://sendgrid.com/blog/using-ruby-to-implement-a-fluent-interface-to-any-restful-api. In your case, I would not worry about it.

You would add this code right after the point in your code where you would like to trigger the email.

Please let me know if you have further questions.

With Best Regards,

Elmer

**Comment by pmackay** [comment]
@thinkingserious I'd like to clarify, is the `sendgrid-rails` gem that @MincePie lists above needed at all? My understanding is the `sendgrid-ruby` gem is completely separate.

**Comment by thinkingserious** [comment]
@pmackay,

Good catch. No, that is a third party library not related to ours.
