### ISSUE TITLE
How Can I Create The Attachement Content Base64 Encoded?

### ISSUE THREAD

**Issue by maxpark-jd** [sendgrid/sendgrid-ruby#84]
#### Issue Summary

attaching a pdf or a zip file. 
Used code: 
Base64.encode64(File.binread(file_path))
If Base64.encode64 cannot create a proper attachment content, then which library/method I should use to get a proper content which will be accepted by Sendgrid web api v3?

#### Steps to Reproduce

I get this error:
{\"errors\":[{\"message\":\"The attachment content must be base64 encoded.\",\"field\":\"attachments.0.content\",\"help\":\"http://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/errors.html#message.attachments.content\"}]}

#### Technical details:

* sendgrid-ruby Version: 4.0.2
* Ruby Version: 2.2.3

**Comment by thinkingserious** [comment]
Hello @maxpark-jd,

Thanks for reaching out!

Please try: http://ruby-doc.org/stdlib-2.3.1/libdoc/base64/rdoc/Base64.html#method-i-strict_encode64 as `Base64.encode64` adds a newline.

Thanks!

**Comment by maxpark-jd** [comment]
Thank you @thinkingserious! It worked like a charm.

**Comment by thinkingserious** [comment]
@maxpark-jd,

Sorry you had to deal with that. We will be enhancing our mail helper to hide this sort of detail from you.

**Comment by maxpark-jd** [comment]
awe thanks for kind words.

**Comment by ienders** [comment]
@thinkingserious +1 to handling this in both the sendgrid-ruby client and having a slightly less strict API on the server side. This caused a mild amount of frustration and dropped sends, as we can't rely on the Mail gem's encoding out of the box. Regardless, thanks for the advice. :)

**Comment by thinkingserious** [comment]
Thanks for the feedback @ienders!

I will add your vote to the backlog item.
