### ISSUE TITLE
Upgrading from 1.x to 4.x breaks BCC email setting configuration

### ISSUE THREAD

**Issue by jeffblake** [sendgrid/sendgrid-ruby#85]
#### Issue Summary

I've sent in a ticket to support@sendgrid.com and am just getting generic replies.. not much help there, so I thought I'd post here...

In SendGrid, Settings > Mail Settings > BCC is configured.

I migrated 1.x to 4.x, wrote the new code, tested it, everything works great.

The only problem is that now my BCC (sends a copy of every email sent) is now broken: there is no subject or to address for the email, but the body is  there. I thought it had something to do with personalizations, so I set the subject on both the SendGrid::Mail object and the Personalization object, no effect.

![screen shot 2016-08-08 at 3 44 18 pm](https://cloud.githubusercontent.com/assets/620564/17526938/3cf3cd8e-5e1e-11e6-8ba3-ce3c2b1599ed.png)

Desired effect:

My BCC address receives the exact email that the recipient received, including body, subject, to field, etc. 

#### Technical details:

* sendgrid-ruby Version: 4.0.2
* Ruby Version: 2.3

**Comment by thinkingserious** [comment]
Hello @jeffblake,

This is a known bug in the API and is currently in our backlog for repair. The current workaround is to apply a BCC directly within the personalizations field. 

Once the fix is deployed, I will notify you here.

Thanks!

With Best Regards,

Elmer

**Comment by jeffblake** [comment]
Any luck on this? I use my log email account to search emails quite often, and not being able to see the to email or subject is killing me. Appreciate it.

**Comment by thinkingserious** [comment]
Hi @jeffblake,

The fix is currently in progress by one of our engineering teams in this current sprint. I can't say for sure when it will be done, but it looks like it will be soon.

Thanks for checking in!

**Comment by thinkingserious** [comment]
@jeffblake,

This issue is now fixed and deployed to production. Please let me know if you continue to see any issues. Thanks for your patience!

**Comment by jeffblake** [comment]
Confirmed working! Thank you
