### ISSUE TITLE
Unexpected Mail instance `categories`, `categories=` behavior

### ISSUE THREAD

**Issue by subvertallchris** [sendgrid/sendgrid-ruby#86]
#### Issue Summary

`SendGrid::Mail` categories behavior makes it too easy to set empty values. 
#### Steps to Reproduce

Instantiate a new instance

```
sg_mail = SendGrid::Mail.new
```

I know it will end up being an Arrary, so try to add something to it...

```
sg_mail.categories << 'foo'
# NoMethodError: undefined method `<<' for nil:NilClass
```

Oh, `categories` starts nil. I guess we need to instantiate it?

```
sg_mail.categories = []
sg_mail.categories
=> [nil]
```

An Array with `nil` in it. ???

More misleading is that if someone expects it to accept the String category, it will not complain, it will just add `nil`

```
sg_mail.categories = 'foo'
=> "foo"

sg_mail.categories
=> [nil, nil]
```

Despite its own awareness that it is an Array and its delegation of methods, it doesn't actually let me treat it like an array, so I don't have a clear way of fixing this.

```
sg_mail.categories.compact
=> []

sg_mail.categories
=> [nil, nil]
```

You could improve this by doing two things:
- New instances of `Sendgrid::Mail` should set `categories` to an empty Array. If nothing else, that would let callers know to treat it like an array and avoid `categories=` in the first place.

``` ruby
    def categories
      @categories ||= []
    end
```

https://github.com/sendgrid/sendgrid-ruby/blob/master/lib/sendgrid/helpers/mail/mail.rb#L908
- Fix `categories=`. I don't think that [what you have defined](https://github.com/sendgrid/sendgrid-ruby/blob/master/lib/sendgrid/helpers/mail/mail.rb#L905) works at all. When you call `[string]` on a String, you just select that pattern from the string. So if someone did do this:

``` ruby
# I guess this was what you had in mind?
sg_mail.categories = { categories: 'foo' }

# It would become this:
{ category: 'foo' }.to_json
=> "{\"category\":\"foo\"}"

# And then you're just pulling the word `category` out of it and storing it in your array
"{\"category\":\"foo\"}"['category']
=> "category"
```

This is also why calling `categories=` results in `nil` entries: it converts everything to a String with `to_json` and then `whatever_your_string_is['categories']` always returns nil.
#### Technical details:
- sendgrid-ruby Version: 4.0.2
- Ruby Version: 2.2.3

**Comment by thinkingserious** [comment]
Excellent feedback @subvertallchris!

We would like to offer you some swag. Please email us at dx@sendgrid.com referencing this ticket with your mailing address and T-shirt size.

For this issue to rise up in our queue, we need +1s, comments or a pull request with a signed CLA.

Thanks!

**Comment by tkbky** [comment]
Related issue: #95

**Comment by thinkingserious** [comment]
Please follow progress on this issue here: #95

Thanks!
