### ISSUE TITLE
templates and sections

### ISSUE THREAD

**Issue by manpreetminhas** [sendgrid/sendgrid-ruby#87]
#### I have the following piece of code

`mail = SendGrid::Mail.new`
`mail.template_id = "23c0c52c-853e-414c-8ee7-bca11f3eae4a"`
`mail.sections = Section.new(key: 'section_1', value: 'Substitution Text for Section 1')`
`mail.sections = Section.new(key: 'section_2', value: 'Substitution Text for Section 2')`

How to do I use these two sections (section_1 and section_2) in my template?

I am able to use substitutions through Personalization

`personalization = Personalization.new`
`personalization.to = Email.new(email: deal.email)`
`personalization.subject = "#{deal.transactionType.camelcase} Email"`
`personalization.substitutions = Substitution.new(key:'customer_name', value:deal.name)`
`personalization.substitutions = Substitution.new(key:'pds_link', value: 'some_link')`
 `personalization.substitutions = Substitution.new(key:'fsg_link', value: 'some_link')`
`mail.personalizations = personalization`

And in my template i use these substitutions 
`<td>`
`<div>`
`<span>Dear customer_name</span>`
`<span>Please find attached a link to your PDS and FSG documents.</span>`
`</div>`
`<div>`
`<a href="pds_link">PDS Document</a>`
`</div>`
`<div>`
`<a href="fsg_link">FSG Document</a>`
`</div>`
`<div>`
`<span>Your payment receipt number</span>`
`</div>`
`<div>`
`<span>qpr_number</span>`
`</div>`
`</td>`

And it looks good. But I don't know how to get the sections working. I want to have conditionals but am not sure how to implement it. Is it possible to get some sample template HTML with sections defined/working?
#### Technical details:
- sendgrid-ruby Version: master (latest commit: [commit number])
- Ruby Version: 2.2

**Comment by thinkingserious** [comment]
@manpreetminhas,

For substitutions in templates, the personalization.substitutions method is correct.

For sections, please see: https://sendgrid.com/docs/API_Reference/SMTP_API/section_tags.html
