### ISSUE TITLE
explain how to use smtpapi gem

### ISSUE THREAD

**Issue by nquinlan** [sendgrid/sendgrid-ruby#9]
It'd be nifty if you could include an example of how to use [sendgridJP/smtpapi-ruby](https://github.com/sendgridJP/smtpapi-ruby), before throwing people over to it.

**Comment by rbin** [comment]
@eddiezane what do you think about this buddy?

**Comment by nquinlan** [comment]
Even just one or two examples would be good, not telling people how to use it, means that people need to look at the code to find the accessor.

I know I always need to look back at old code to figure out how I'm supposed to access the header.
