### ISSUE TITLE
Create New subuser along with API Key

### ISSUE THREAD

**Issue by gmhawash** [sendgrid/sendgrid-ruby#90]
#### Issue Summary

I want to use the v3 API to create a subuser and then create an API Key for that subuser.  The documentation about API Keys (https://sendgrid.com/docs/API_Reference/Web_API_v3/API_Keys/index.html#Generate-a-new-API-Key-for-the-authenticated-user-POST) indicates that I can generate an API key for the `authenticated user`.   However, the only way that I can see to authenticate is through an API key (which is non existent for a new subuser).  Is this a catch 22!!!

How can I do this using version 3 of the API?
#### Technical details:
- sendgrid-ruby Version: 4.0.3
- Ruby Version: 2.2

**Comment by thinkingserious** [comment]
Hello @gmhawash,

It looks like that feature is not available right now. I will double check and if it is indeed not available, I'll put in a feature request with our product team.

**Comment by todociber** [comment]
There new news on this functionality?

**Comment by gmhawash** [comment]
I was able to add the following to the header "On-behalf-of" => 'subuser name' and create the API key for that subuser.

**Comment by thinkingserious** [comment]
Thanks for the follow up @gmhawash!
