### ISSUE TITLE
Mails not delivered to email ids with UTF-8 characters

### ISSUE THREAD

**Issue by arunkumarsundaramurthy** [sendgrid/sendgrid-ruby#91]
#### Issue Summary

Mail is not delivered to email ids with UTF-8 characters. Those mails are marked as "Drop" in the Activity Feed. UTF-8 characters are allowed in email ids (http://stackoverflow.com/questions/3844431/are-email-addresses-allowed-to-contain-non-alphanumeric-characters).
#### Steps to Reproduce
1. Try sending mail to example的@test.com
#### Technical details:
- sendgrid-ruby Version: 3.0.5
- Ruby Version: 2.2.3

**Comment by thinkingserious** [comment]
Hello @arunkumarsundaramurthy,

Thanks for the heads up! We will investigate.

**Comment by thinkingserious** [comment]
Hello @arunkumarsundaramurthy,

Currently, this is expected behavior.

I have passed along your feedback to our product team.

With Best Regards,

Elmer

**Comment by randy-girard** [comment]
Hello, is there any update on this?

Thx

**Comment by thinkingserious** [comment]
Hello @randy-girard,

Thanks for reaching out.

This is not currently on our roadmap for implementation.

With Best Regards,

Elmer

**Comment by johnklein** [comment]
+1 for adding it to the road map.

**Comment by thinkingserious** [comment]
Thanks @johnklein!

**Comment by fuelxc** [comment]
this seems like a serious flaw as https://tools.ietf.org/html/rfc6530 https://tools.ietf.org/html/rfc6531  https://tools.ietf.org/html/rfc6532 and https://tools.ietf.org/html/rfc6533 allows for international characters

Google adopted these RFC's in 2014

there are domains that use UTF-8 .भारत is a TLD that you are unable to send to in its entirety.

**Comment by thinkingserious** [comment]
Thanks for the additional feedback @fuelxc,

I have passed along your feedback to our product team. 

With Best Regards,

Elmer

**Comment by Mange** [comment]
Any update to this?

This prevents some users from using our apps and they have been using their email addresses for *years* so we cannot expect them to migrate to another address just to use our apps.

I get this might be uncommon in majority-English-speaking countries, but imagine for a second that a large email provider disallowed you from using "w" in your email addresses. That would be very problematic for English-speaking countries.

**Comment by thinkingserious** [comment]
Internal tracking ID: MP-6256

**Comment by thinkingserious** [comment]
@Mange 

Thanks for the additional context. I have forwarded this information along internally and we will update this thread as progress is made or information received.
