### ISSUE TITLE
How to use subsituation variable inside ruby tag <% %>?

### ISSUE THREAD

**Issue by ved54321** [sendgrid/sendgrid-ruby#93]
Hi,
I have added sendgrid_substitute  '-user_id-' ,user_ids , i can used -user_id- inside my view like Hi -user_id- but i want to use like ,`Hi <% -user_id %>`. Please help me.

**Comment by thinkingserious** [comment]
Hello @ved54321,

Can you provide us with the relevant source code so that we can reproduce the issue?

Thanks!
