### ISSUE TITLE
Create a Inbound Parse data parser

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-ruby#97]
Acceptance Criteria:
- Implement all the functions [here](https://github.com/sendgrid/sendgrid-python/blob/master/sendgrid/helpers/inbound/parse.py).

Reference:
- https://github.com/sendgrid/sendgrid-python/blob/master/sendgrid/helpers/inbound/parse.py
- https://sendgrid.com/docs/Classroom/Basics/Inbound_Parse_Webhook/setting_up_the_inbound_parse_webhook.html
- https://sendgrid.com/docs/API_Reference/Webhooks/parse.html

**Comment by awwa** [comment]
[In my pull request](https://github.com/sendgrid/sendgrid-ruby/pull/114/files#diff-bea922085aa2613fda7576bc5a07dec9R17), Sinatra automatically parse the multiple/form-data to json. So no need to parse the data manually. You can get the data from `params` variable.
How about this implementations?

**Comment by thinkingserious** [comment]
Hi @awwa, 

I'll go ahead and review your PR. Thanks!

**Comment by thinkingserious** [comment]
done: https://github.com/sendgrid/sendgrid-ruby/tree/master/lib/sendgrid/helpers/inbound
